In [11]:
import pandas as pd

In [13]:
df = pd.read_parquet("pipeline/checkpoints/stage1_playlists_@OfficialYuGiOhTCG.parquet")
df

,Playlist Title,Video Count,Playlist ID
0,Chaos Origins,5,PLc1vyOIGc2qXR_Ym2ulQU-JQAwsL6mUs1
1,Battles of Legend: Glorious Gallery,3,PLc1vyOIGc2qU8wh9cPNF82OcKnw5IFccF
2,Blazing Dominion,4,PLc1vyOIGc2qXHIlcNpiK5UnxcUp02mkE-
3,Rarity Collection V,6,PLc1vyOIGc2qW7vPoPEzFNxnV54Q2qIOV6
4,Legendary Modern Decks 2026,5,PLc1vyOIGc2qX01LHO_FEuNuoA_XuYaoxU
...,...,...,...
118,Yu-Gi-Oh! 2015 North American WCQ,24,PLc1vyOIGc2qXKkGwYHOU-m5dBqMU8FDpt
119,How To Play Tutorials,5,PLc1vyOIGc2qVb3yvIXCuRD9wEH4YgGGhf
120,Yu-Gi-Oh! 150th YCS Columbus,15,PLc1vyOIGc2qVerc4qlE4na0TZRH0oRUix
121,YGO 2015 Products,12,PLc1vyOIGc2qUW0RKRuakuSJE2OXhtq8oN
122,2013 North American WCQ,3,PLc1vyOIGc2qX9_zN-CyG1_GTPOvinQZ3Q

In [14]:
df = pd.read_parquet("pipeline/checkpoints/stage1_playlists_@YuGiOhCardEU.parquet")
df

,Playlist Title,Video Count,Playlist ID
0,Yu-Gi-Oh! TCG | Chaos Origins Unboxing Series,21,PLIm0Rt8gzRbusJI2gZfgTOYXDp8DyhL-U
1,Yu-Gi-Oh! TCG | Battles of Legend: Glorious Ga...,22,PLIm0Rt8gzRbskxI-lI7pC0klGQw5FLGBI
2,Yu-Gi-Oh! TCG | Blazing Dominion Unboxing Series,22,PLIm0Rt8gzRbtYPRjkHV_z8WgY1I42EJdc
3,Yu-Gi-Oh! Rarity Collection,4,PLIm0Rt8gzRbv2hsmR9PrFpmOlwSKVDArh
4,Yu-Gi-Oh! TCG Rarity Collection 5 Reveals!,21,PLIm0Rt8gzRbuQw2N4O0oOvc5gOnPUO8dz
...,...,...,...
128,YCS Madrid | Yu-Gi-Oh! Championship Series Madrid,16,PLIm0Rt8gzRbtE1wXv0kUYBP4GeNUnpFdg
129,YCS Milan | Yu-Gi-Oh! Championship Series Milan,18,PLIm0Rt8gzRbu5uULuK4WArO6Ii3VRo12L
130,YCS Prague | Yu-Gi-Oh! Championship Series Prague,32,PLIm0Rt8gzRbu5rDW3wVN5G_Zcg_G53RB9
131,WCQ: EC2015 | 2015 Yu-Gi-Oh! TCG WCQ: European...,60,PLIm0Rt8gzRbss2nX1mixsDYj4CpmZ8ugW
132,YCS Bochum | Yu-Gi-Oh! Championship Series Bochum,38,PLIm0Rt8gzRbudSiIYYy2neWhQqecruQNU

In [17]:
df = pd.read_parquet("pipeline/checkpoints/OfficialYuGiOhTCG_parsed.parquet")
df

,Clean Title,Year,Category,Video Count,Playlist ID,Playlist Title
0,World Championship,2019,Advanced,26,PLc1vyOIGc2qUclsFSVx6fWVI0pI9TQDUp,Yu-Gi-Oh! World Championship 2019
1,WCQ,2015,Advanced,24,PLc1vyOIGc2qXKkGwYHOU-m5dBqMU8FDpt,Yu-Gi-Oh! 2015 North American WCQ
2,WCQ,2023,Advanced,23,PLc1vyOIGc2qWFXx4GRFFbiv3AR1wxD3yV,Dueling Archives: North American WCQ 2023
3,Other,Unknown,Advanced,18,PLc1vyOIGc2qX-zEOY_FPbKQtkJVyd-5jM,Dueling Archives: NAWCQ Indianapolis
4,WCQ,2024,Advanced,18,PLc1vyOIGc2qUPQ3Al4_8S6QJ__QFSVAaO,Dueling Archives: 2024 WCQ Austin
5,Other,2025,Advanced,18,PLc1vyOIGc2qUy8UruoP-7uEa-cgG6KRjO,Dueling Archives: YCS Houston 2025
6,Other,2025,Advanced,18,PLc1vyOIGc2qVR3zjIHAQmLCdrtFEDZT99,Dueling Archives - YCS Orlando 2025
7,Other,2025,Advanced,17,PLc1vyOIGc2qUdrzkwxpyWPF7hEA-4nxYM,Dueling Archives: YCS Providence 2025
8,Other,2024,Advanced,17,PLc1vyOIGc2qXZj0ml7PjZVotk9u4BKL8Z,Dueling Archives: 2024 YCS Raleigh
9,Other,Unknown,Advanced,16,PLc1vyOIGc2qW5Sc7c0ZFOtfPYr4Z5t8Bi,"Dueling Archives: 250th YCS: Los Angeles, CA"
10,Other,2024,Advanced,16,PLc1vyOIGc2qVH_lI0WeiyavM_XOAQoCnH,Dueling Archives: YCS Sacramento 2024
11,Other,2024,Advanced,15,PLc1vyOIGc2qVGiERh0olzUkkdjXVBzNi3,Dueling Archives - YCS Anaheim 2024
12,Other,2024,Advanced,15,PLc1vyOIGc2qVxjActmFOJHlVit2Y06w0C,Dueling Archives: 2024 YCS Indianapolis
13,Other,Unknown,Advanced,15,PLc1vyOIGc2qVerc4qlE4na0TZRH0oRUix,Yu-Gi-Oh! 150th YCS Columbus
14,World Championship,2017,Advanced,13,PLc1vyOIGc2qVsXghcP-IRPwbIg9yiDTrc,Yu-Gi-Oh! 2017 World Championship
15,Other,2020,Advanced,7,PLc1vyOIGc2qUwKZvwkAIZrfMup6QHDs-1,Remote Duel Invitational - TCG (8/22 - 8/23/2020)
16,WCQ,2024,Advanced,4,PLc1vyOIGc2qVX6ZJxab88NnmgUIZLDiLe,Dueling Archives: 2024 WQP Austin
17,World Championship,2024,Advanced,4,PLc1vyOIGc2qUluBlrVlUuTANCWpSAHjGa,Yu-Gi-Oh! World Championship 2024
18,WCQ,2013,Advanced,3,PLc1vyOIGc2qX9_zN-CyG1_GTPOvinQZ3Q,2013 North American WCQ
19,WCQ,2019,Advanced,3,PLc1vyOIGc2qXas2XPsp4wKpJDjshieo0N,Yu-Gi-Oh! 2019 North America WCQ
20,Other,2017,Advanced,3,PLc1vyOIGc2qVA85mAij71b89eAbdruY1u,"YCS San Diego (Nov 18-19, 2017)"
21,Other,2020,Advanced,2,PLc1vyOIGc2qXdSd5bAVaFUp3BTGDZPwgd,Team YCS Las Vegas 2020
22,Other,Unknown,Advanced,2,PLc1vyOIGc2qUpHELcFLe4ZE-JVw2enn54,Yu-Gi-Oh! Championship Series
23,Dragon Duel,2024,Advanced,1,PLc1vyOIGc2qUM7r-X3Abizu4s8qnfQwzG,Dueling Archives: 2024 WCQ Austin Dragon Duel ...

In [18]:
df = pd.read_parquet("pipeline/checkpoints/YuGiOhCardEU_parsed.parquet")
df

,Clean Title,Year,Category,Video Count,Playlist ID,Playlist Title
0,Other,2018,Advanced,78,PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl,YCS Bochum 2018 | Yu-Gi-Oh! Championship Serie...
1,WCQ,2015,Advanced,60,PLIm0Rt8gzRbss2nX1mixsDYj4CpmZ8ugW,WCQ: EC2015 | 2015 Yu-Gi-Oh! TCG WCQ: European...
2,WCQ,2016,Advanced,57,PLIm0Rt8gzRbvYYuWPcfcb1ZNQLCoPT5vm,WCQ: EC2016 | 2016 WCQ: European Championship
3,WCQ,2017,Advanced,54,PLIm0Rt8gzRbsHq8NXVNrIejQoUN3nMFfo,2017 WCQ: EC | 2017 WCQ: European Championship
4,Other,2018,Advanced,50,PLIm0Rt8gzRbvNmWVsRbgwdxXWcX1EXxh0,YCS Milan 2018 | Yu-Gi-Oh! Championship Series...
...,...,...,...,...,...,...
64,World Championship,2019,Advanced,7,PLIm0Rt8gzRbsxRacuVerQ4REzU6zRQFXt,Yu-Gi-Oh! World Championship 2019 - Berlin
65,Other,2021,Advanced,7,PLIm0Rt8gzRbtMPDnLGYFII_tUVnRM5ScA,Remote Duel Yu-Gi-Oh! Championship Series 2021...
66,Dragon Duel,2018,Advanced,7,PLIm0Rt8gzRbuauJOWCGiWGDMbOrK_4lZz,2018 Yu-Gi-Oh! TCG Dragon Duel World Championship
67,World Championship,2024,Advanced,6,PLIm0Rt8gzRbvlG2IvMeWgyI8VNEMLnuQ_,Yu-Gi-Oh! World Championship Series 2024
68,WCQ,2014,Advanced,1,PLIm0Rt8gzRbtTio1RMkWdRH9bkRNmX-Gh,WCQ: EC2014 | Yu-Gi-Oh! TCG WCQ: European Cham...

In [102]:
df = pd.read_parquet("pipeline/checkpoints/stage4_videos.parquet")
display(df)

,Playlist ID,Video ID,Title,Video Description,Clean Title,Year,Category,Playlist Title
0,PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl,s224f2XCeMo,YCS Bochum 2018: Welcome,"Footage recorded from Yu-Gi-Oh! YCS Bochum, he...",YCS Bochum,2018,YCS,YCS Bochum 2018 | Yu-Gi-Oh! Championship Serie...
1,PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl,UCaUi0WUV0A,YCS Bochum 2018: Event Spotlight,"Footage recorded from Yu-Gi-Oh! YCS Bochum, he...",YCS Bochum,2018,YCS,YCS Bochum 2018 | Yu-Gi-Oh! Championship Serie...
2,PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl,y8aTolgLcww,YCS Bochum 2018: Quick Questions,"Footage recorded from Yu-Gi-Oh! YCS Bochum, he...",YCS Bochum,2018,YCS,YCS Bochum 2018 | Yu-Gi-Oh! Championship Serie...
3,PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl,gr2n8RxtnBQ,YCS Bochum 2018: Meta Discussion,"Footage recorded from Yu-Gi-Oh! YCS Bochum, he...",YCS Bochum,2018,YCS,YCS Bochum 2018 | Yu-Gi-Oh! Championship Serie...
4,PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl,s68iNKx-chM,YCS Bochum 2018: Giant Card Spotlight,"Footage recorded from Yu-Gi-Oh! YCS Bochum, he...",YCS Bochum,2018,YCS,YCS Bochum 2018 | Yu-Gi-Oh! Championship Serie...
...,...,...,...,...,...,...,...,...
2019,PLc1vyOIGc2qXdSd5bAVaFUp3BTGDZPwgd,JjLkFrsrVy0,[Day 2] Team Yu-Gi-Oh! Championship Series - L...,Welcome to the Team Yu-Gi-Oh! Championship Ser...,YCS Las Vegas,2020,YCS,Team YCS Las Vegas 2020
2020,PLc1vyOIGc2qXdSd5bAVaFUp3BTGDZPwgd,jzDasFfd9BU,[Day 1] Team Yu-Gi-Oh! Championship Series - L...,Welcome to the Team Yu-Gi-Oh! Championship Ser...,YCS Las Vegas,2020,YCS,Team YCS Las Vegas 2020
2021,PLc1vyOIGc2qUpHELcFLe4ZE-JVw2enn54,CC4DnsceYTc,[Day 2] Yu-Gi-Oh! Championship Series - Pasade...,Welcome to the Yu-Gi-Oh! Championship Series i...,YCS,Unknown,YCS,Yu-Gi-Oh! Championship Series
2022,PLc1vyOIGc2qUpHELcFLe4ZE-JVw2enn54,3PS-97G3lBM,[Day 1] Yu-Gi-Oh! Championship Series - Pasade...,Welcome to the Yu-Gi-Oh! Championship Series i...,YCS,Unknown,YCS,Yu-Gi-Oh! Championship Series
2023,PLc1vyOIGc2qUM7r-X3Abizu4s8qnfQwzG,YrWkAofAm_E,"2024 North America Dragon Duel: Austin, TX// F...",Dragon Duel Final Match replay from 2024 WCQ A...,NA World Championship Austin Dragon Duel Finals,2024,Dragon Duel,Dueling Archives: 2024 WCQ Austin Dragon Duel ...

In [136]:
import pandas as pd
import re

RE_MATCH_INDICATOR = re.compile(  r'\bround\s*\d+|\btop\s*\d+|\bfinals?\b|\bsemi[-\s]?finals?\b|\bvs\.?\b|\b\d+(?:st|nd|rd|th)\s+place\b', re.IGNORECASE) 
RE_EXCLUDE = re.compile(r'\bannouncement\b|\binterview\b|\bdiscussion\b|\bvlog\b|\bdeck\s*profile\b', re.IGNORECASE)
RE_VS_PATTERN = re.compile(r'\bvs\.?\b', re.IGNORECASE)
RE_PLACEMENT = re.compile(r'\b\d+(?:st|nd|rd|th)\s+place\b', re.IGNORECASE)

df = pd.read_parquet("pipeline/checkpoints/stage4_videos.parquet")

match_mask   = df["Title"].str.contains(RE_MATCH_INDICATOR, na=False)
exclude_mask = df["Title"].str.contains(RE_EXCLUDE, na=False)

matches = df[match_mask & ~exclude_mask]
dropped = df[~match_mask | exclude_mask]

print(f"Kept: {len(matches)}")
print(f"Dropped: {len(dropped)}")

Kept: 1379
Dropped: 645

In [141]:
RE_LIVESTREAM_DAY = re.compile(r'\bday\s*[123]\b', re.IGNORECASE)

livestreams = dropped[dropped["Title"].str.contains(RE_LIVESTREAM_DAY, na=False)]
dropped_remaining = dropped[~dropped["Title"].str.contains(RE_LIVESTREAM_DAY, na=False)]

print(f"Livestreams: {len(livestreams)}")
print(f"Dropped (remaining): {len(dropped_remaining)}")

Livestreams: 63
Dropped (remaining): 582

In [140]:
dropped[dropped['Title'].str.contains('World')]['Title'].unique()

array(['The Road to Worlds',
       'Yu-Gi-Oh! World Championship Qualifier Utrecht 2017',
       'Yu-Gi-Oh! World Championship 2025 - President Emmanuel Macron\xa0Introduction',
       'Livestream | Yu-Gi-Oh! World Championship Master Duel 2025 | Day 1',
       'Livestream | Yu-Gi-Oh! World Championship Master Duel and Duel Links 2025 | Day 2',
       'Livestream | Yu-Gi-Oh! World Championship OCG/TCG 2025 | Day 2',
       'Yu-Gi-Oh! WCS 2025 | TCG World Championship Day 1 Impressions',
       'Yu-Gi-Oh! WCS 2025 | How to qualify for the World Championship? | Sebastian Lemke & Billy Brake',
       'Livestream | Yu-Gi-Oh! European World Championship Qualifier Berlin 2025 – Day 2',
       'Livestream | Yu-Gi-Oh! European World Championship Qualifier Berlin 2025 – Day 1',
       'Livestream | World Qualifying Points Play Off |\xa0Yu-Gi-Oh! European  WCQ Berlin 2025',
       'Livestream | Yu-Gi-Oh! European World Championship Qualifier Berlin 2024 – Day 2',
       'Livestream | Yu-Gi-Oh! European World Championship Qualifier Berlin 2024 – Day 1',
       '2018 Yu-Gi-Oh! TCG World Championship - Augmented-Reality Duel',
       '2018 Yu-Gi-Oh! TCG World Championship - Finalists Introduction',
       'Yu-Gi-Oh! World Championship 2018 [Qualifiers: Live Broadcast]',
       'Livestream | 2023 European World Championship Qualifier  – Day 2',
       'Livestream | 2023 European World Championship Qualifier – Day 1',
       '2014 World Championship: Behind The Scenes',
       '2014 Yu-Gi-Oh! TCG World Championship: Rimini City Tour',
       '[JP] 2017 World Championship | Exhibition Match | Augmented Reality Duel',
       '🔴 Livestream [DAY 1] – Yu-Gi-Oh! World Championship 2019 – Berlin',
       '🔴 Livestream [DAY 2]– Yu-Gi-Oh! World Championship 2019 – Berlin',
       'Yu-Gi-Oh! World Championship 2019 Recap',
       'How I got Invited to Worlds? All That You Want to Know FAQ - WCS 2019',
       'WCS 2019 Pre-Event Interview Raphael Neven, Galileo, Gabriel Vargas Breaks Down Worlds List',
       'Yu-Gi-Oh! World Championship Qualifier - Awards Ceremony',
       '[JP] 2017 World Championship Exhibition Match: Augmented Reality Duel',
       'Yu-Gi-Oh! TRADING CARD GAME World Championship 2024 – Day 1',
       'Yu-Gi-Oh! MASTER DUEL World Championship 2024 – Day 1',
       'Yu-Gi-Oh! DUEL LINKS World Championship 2024 – Day 1',
       'Yu-Gi-Oh! DUEL LINKS | MASTER DUEL | TCG World Championship 2024 – Day 2',
       'Yu-Gi-Oh! TRADING CARD GAME 2013 World Championship Message',
       'Yu-Gi-Oh! TCG 2019 North America World Championship Qualifier - Day 1',
       'Yu-Gi-Oh! TCG 2019 North America World Championship Qualifier - Day 3',
       'Yu-Gi-Oh! TCG 2019 North America World Championship Qualifier - Day 2'],
      dtype=object)

In [157]:
df = pd.read_parquet("pipeline/checkpoints/stage5_matches.parquet")
df

,Playlist ID,Video ID,Title,Video Description,Clean Title,Year,Category,Playlist Title
0,PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl,gtY3Gm81ckc,YCS Bochum 2018: Round 1 Feature Match,"Footage recorded from Yu-Gi-Oh! YCS Bochum, he...",YCS Bochum,2018,YCS,YCS Bochum 2018 | Yu-Gi-Oh! Championship Serie...
1,PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl,Lpam8Aii1vM,YCS Bochum 2018: Round 2 Feature Match,"Footage recorded from Yu-Gi-Oh! YCS Bochum, he...",YCS Bochum,2018,YCS,YCS Bochum 2018 | Yu-Gi-Oh! Championship Serie...
2,PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl,wRwnUvpcyKA,YCS Bochum 2018: Round 3 Feature Match,"Footage recorded from Yu-Gi-Oh! YCS Bochum, he...",YCS Bochum,2018,YCS,YCS Bochum 2018 | Yu-Gi-Oh! Championship Serie...
3,PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl,tpR87uZpnfU,YCS Bochum 2018: Round 4 Feature Match,"Footage recorded from Yu-Gi-Oh! YCS Bochum, he...",YCS Bochum,2018,YCS,YCS Bochum 2018 | Yu-Gi-Oh! Championship Serie...
4,PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl,Dwp_1bljFLo,YCS Bochum 2018: Round 5 Feature Match,"Footage recorded from Yu-Gi-Oh! YCS Bochum, he...",YCS Bochum,2018,YCS,YCS Bochum 2018 | Yu-Gi-Oh! Championship Serie...
...,...,...,...,...,...,...,...,...
1374,PLc1vyOIGc2qVX6ZJxab88NnmgUIZLDiLe,ZrD5_lg5ioc,"2024 North America WQP: Austin, TX // Top 16 -...",WQP Austin Top 16 Match Replay between George ...,WQP Austin,2024,WQP,Dueling Archives: 2024 WQP Austin
1375,PLc1vyOIGc2qVX6ZJxab88NnmgUIZLDiLe,ZkyHjeRmmPs,"2024 North America WQP: Austin, TX // Top 8 - ...",WQP Austin Top 8 Match Replay between Logan J....,WQP Austin,2024,WQP,Dueling Archives: 2024 WQP Austin
1376,PLc1vyOIGc2qVX6ZJxab88NnmgUIZLDiLe,FIhfBEclMv0,"2024 North America WQP: Austin, TX // Semi Fin...",WQP Austin Semi Final Match Replay between Geo...,WQP Austin,2024,WQP,Dueling Archives: 2024 WQP Austin
1377,PLc1vyOIGc2qVX6ZJxab88NnmgUIZLDiLe,-y24Ncvio-o,"2024 North America WQP: Austin, TX // Semi Fin...",WQP Austin Semi Final Match Replay between Log...,WQP Austin,2024,WQP,Dueling Archives: 2024 WQP Austin
1378,PLc1vyOIGc2qUM7r-X3Abizu4s8qnfQwzG,YrWkAofAm_E,"2024 North America Dragon Duel: Austin, TX// F...",Dragon Duel Final Match replay from 2024 WCQ A...,NA World Championship Austin Dragon Duel Finals,2024,Dragon Duel,Dueling Archives: 2024 WCQ Austin Dragon Duel ...

In [158]:
df = pd.read_parquet("pipeline/checkpoints/livestreams.parquet")
df

,Playlist ID,Video ID,Title,Video Description,Clean Title,Year,Category,Playlist Title
0,PLIm0Rt8gzRbvYYuWPcfcb1ZNQLCoPT5vm,MqK7qRQbbj4,WCQ Berlin: Impressions Day 2,Yu-Gi-Oh! TRADING CARD GAME\r\n © 1996 Kazuki ...,EU World Championship Qualifer,2016,World Championship,WCQ: EC2016 | 2016 WCQ: European Championship
1,PLIm0Rt8gzRbvYYuWPcfcb1ZNQLCoPT5vm,bUStmUogIY8,WCQ Berlin: Impressions Day 1,Yu-Gi-Oh! TRADING CARD GAME\r\n © 1996 Kazuki ...,EU World Championship Qualifer,2016,World Championship,WCQ: EC2016 | 2016 WCQ: European Championship
2,PLIm0Rt8gzRbuI3ij0C4yrfAQb8tMbtCt8,HmtSUuOGztM,Livestream | Yu-Gi-Oh! Championship Series Bol...,Watch the day 2 livestream of Yu-Gi-Oh! Champi...,YCS Bologna,2025,YCS,YCS Bologna 2025
3,PLIm0Rt8gzRbuI3ij0C4yrfAQb8tMbtCt8,pIvUeWm9lWU,Livestream | Yu-Gi-Oh! Championship Series Bol...,Watch the day 1 livestream of Yu-Gi-Oh! Champi...,YCS Bologna,2025,YCS,YCS Bologna 2025
4,PLIm0Rt8gzRbvUqBmSmnIEr9nTIFuqAW_F,CtMLNdRJ3u4,Livestream | Yu-Gi-Oh! World Championship Mast...,"©2020 Studio Dice／SHUEISHA, TV TOKYO, KONAMI\n...",World Championship Paris France,2025,World Championship,"Yu-Gi-Oh! World Championship 2025 - Paris, France"
...,...,...,...,...,...,...,...,...
58,PLc1vyOIGc2qVA85mAij71b89eAbdruY1u,IA6scolIkt0,Yu-Gi-Oh! TCG - YCS San Diego 2017 Day 2,,YCS San Diego,2017,YCS,"YCS San Diego (Nov 18-19, 2017)"
59,PLc1vyOIGc2qXdSd5bAVaFUp3BTGDZPwgd,JjLkFrsrVy0,[Day 2] Team Yu-Gi-Oh! Championship Series - L...,Welcome to the Team Yu-Gi-Oh! Championship Ser...,YCS Las Vegas,2020,YCS,Team YCS Las Vegas 2020
60,PLc1vyOIGc2qXdSd5bAVaFUp3BTGDZPwgd,jzDasFfd9BU,[Day 1] Team Yu-Gi-Oh! Championship Series - L...,Welcome to the Team Yu-Gi-Oh! Championship Ser...,YCS Las Vegas,2020,YCS,Team YCS Las Vegas 2020
61,PLc1vyOIGc2qUpHELcFLe4ZE-JVw2enn54,CC4DnsceYTc,[Day 2] Yu-Gi-Oh! Championship Series - Pasade...,Welcome to the Yu-Gi-Oh! Championship Series i...,YCS,Unknown,YCS,Yu-Gi-Oh! Championship Series
62,PLc1vyOIGc2qUpHELcFLe4ZE-JVw2enn54,3PS-97G3lBM,[Day 1] Yu-Gi-Oh! Championship Series - Pasade...,Welcome to the Yu-Gi-Oh! Championship Series i...,YCS,Unknown,YCS,Yu-Gi-Oh! Championship Series

In [155]:
df[df['Title'].str.contains('WQP:', na=False)]

,Playlist ID,Video ID,Title,Video Description,Clean Title,Year,Category,Playlist Title
1374,PLc1vyOIGc2qVX6ZJxab88NnmgUIZLDiLe,ZrD5_lg5ioc,"2024 North America WQP: Austin, TX // Top 16 -...",WQP Austin Top 16 Match Replay between George ...,WQP Austin,2024,WCQ,Dueling Archives: 2024 WQP Austin
1375,PLc1vyOIGc2qVX6ZJxab88NnmgUIZLDiLe,ZkyHjeRmmPs,"2024 North America WQP: Austin, TX // Top 8 - ...",WQP Austin Top 8 Match Replay between Logan J....,WQP Austin,2024,WCQ,Dueling Archives: 2024 WQP Austin
1376,PLc1vyOIGc2qVX6ZJxab88NnmgUIZLDiLe,FIhfBEclMv0,"2024 North America WQP: Austin, TX // Semi Fin...",WQP Austin Semi Final Match Replay between Geo...,WQP Austin,2024,WCQ,Dueling Archives: 2024 WQP Austin
1377,PLc1vyOIGc2qVX6ZJxab88NnmgUIZLDiLe,-y24Ncvio-o,"2024 North America WQP: Austin, TX // Semi Fin...",WQP Austin Semi Final Match Replay between Log...,WQP Austin,2024,WCQ,Dueling Archives: 2024 WQP Austin