In [11]:
import pandas as pd

In [13]:
df = pd.read_parquet("pipeline/checkpoints/stage1_playlists_@OfficialYuGiOhTCG.parquet")
df

,Playlist Title,Video Count,Playlist ID
0,Chaos Origins,5,PLc1vyOIGc2qXR_Ym2ulQU-JQAwsL6mUs1
1,Battles of Legend: Glorious Gallery,3,PLc1vyOIGc2qU8wh9cPNF82OcKnw5IFccF
2,Blazing Dominion,4,PLc1vyOIGc2qXHIlcNpiK5UnxcUp02mkE-
3,Rarity Collection V,6,PLc1vyOIGc2qW7vPoPEzFNxnV54Q2qIOV6
4,Legendary Modern Decks 2026,5,PLc1vyOIGc2qX01LHO_FEuNuoA_XuYaoxU
...,...,...,...
118,Yu-Gi-Oh! 2015 North American WCQ,24,PLc1vyOIGc2qXKkGwYHOU-m5dBqMU8FDpt
119,How To Play Tutorials,5,PLc1vyOIGc2qVb3yvIXCuRD9wEH4YgGGhf
120,Yu-Gi-Oh! 150th YCS Columbus,15,PLc1vyOIGc2qVerc4qlE4na0TZRH0oRUix
121,YGO 2015 Products,12,PLc1vyOIGc2qUW0RKRuakuSJE2OXhtq8oN
122,2013 North American WCQ,3,PLc1vyOIGc2qX9_zN-CyG1_GTPOvinQZ3Q

In [14]:
df = pd.read_parquet("pipeline/checkpoints/stage1_playlists_@YuGiOhCardEU.parquet")
df

,Playlist Title,Video Count,Playlist ID
0,Yu-Gi-Oh! TCG | Chaos Origins Unboxing Series,21,PLIm0Rt8gzRbusJI2gZfgTOYXDp8DyhL-U
1,Yu-Gi-Oh! TCG | Battles of Legend: Glorious Ga...,22,PLIm0Rt8gzRbskxI-lI7pC0klGQw5FLGBI
2,Yu-Gi-Oh! TCG | Blazing Dominion Unboxing Series,22,PLIm0Rt8gzRbtYPRjkHV_z8WgY1I42EJdc
3,Yu-Gi-Oh! Rarity Collection,4,PLIm0Rt8gzRbv2hsmR9PrFpmOlwSKVDArh
4,Yu-Gi-Oh! TCG Rarity Collection 5 Reveals!,21,PLIm0Rt8gzRbuQw2N4O0oOvc5gOnPUO8dz
...,...,...,...
128,YCS Madrid | Yu-Gi-Oh! Championship Series Madrid,16,PLIm0Rt8gzRbtE1wXv0kUYBP4GeNUnpFdg
129,YCS Milan | Yu-Gi-Oh! Championship Series Milan,18,PLIm0Rt8gzRbu5uULuK4WArO6Ii3VRo12L
130,YCS Prague | Yu-Gi-Oh! Championship Series Prague,32,PLIm0Rt8gzRbu5rDW3wVN5G_Zcg_G53RB9
131,WCQ: EC2015 | 2015 Yu-Gi-Oh! TCG WCQ: European...,60,PLIm0Rt8gzRbss2nX1mixsDYj4CpmZ8ugW
132,YCS Bochum | Yu-Gi-Oh! Championship Series Bochum,38,PLIm0Rt8gzRbudSiIYYy2neWhQqecruQNU

In [17]:
df = pd.read_parquet("pipeline/checkpoints/OfficialYuGiOhTCG_parsed.parquet")
df

,Clean Title,Year,Category,Video Count,Playlist ID,Playlist Title
0,World Championship,2019,Advanced,26,PLc1vyOIGc2qUclsFSVx6fWVI0pI9TQDUp,Yu-Gi-Oh! World Championship 2019
1,WCQ,2015,Advanced,24,PLc1vyOIGc2qXKkGwYHOU-m5dBqMU8FDpt,Yu-Gi-Oh! 2015 North American WCQ
2,WCQ,2023,Advanced,23,PLc1vyOIGc2qWFXx4GRFFbiv3AR1wxD3yV,Dueling Archives: North American WCQ 2023
3,Other,Unknown,Advanced,18,PLc1vyOIGc2qX-zEOY_FPbKQtkJVyd-5jM,Dueling Archives: NAWCQ Indianapolis
4,WCQ,2024,Advanced,18,PLc1vyOIGc2qUPQ3Al4_8S6QJ__QFSVAaO,Dueling Archives: 2024 WCQ Austin
5,Other,2025,Advanced,18,PLc1vyOIGc2qUy8UruoP-7uEa-cgG6KRjO,Dueling Archives: YCS Houston 2025
6,Other,2025,Advanced,18,PLc1vyOIGc2qVR3zjIHAQmLCdrtFEDZT99,Dueling Archives - YCS Orlando 2025
7,Other,2025,Advanced,17,PLc1vyOIGc2qUdrzkwxpyWPF7hEA-4nxYM,Dueling Archives: YCS Providence 2025
8,Other,2024,Advanced,17,PLc1vyOIGc2qXZj0ml7PjZVotk9u4BKL8Z,Dueling Archives: 2024 YCS Raleigh
9,Other,Unknown,Advanced,16,PLc1vyOIGc2qW5Sc7c0ZFOtfPYr4Z5t8Bi,"Dueling Archives: 250th YCS: Los Angeles, CA"
10,Other,2024,Advanced,16,PLc1vyOIGc2qVH_lI0WeiyavM_XOAQoCnH,Dueling Archives: YCS Sacramento 2024
11,Other,2024,Advanced,15,PLc1vyOIGc2qVGiERh0olzUkkdjXVBzNi3,Dueling Archives - YCS Anaheim 2024
12,Other,2024,Advanced,15,PLc1vyOIGc2qVxjActmFOJHlVit2Y06w0C,Dueling Archives: 2024 YCS Indianapolis
13,Other,Unknown,Advanced,15,PLc1vyOIGc2qVerc4qlE4na0TZRH0oRUix,Yu-Gi-Oh! 150th YCS Columbus
14,World Championship,2017,Advanced,13,PLc1vyOIGc2qVsXghcP-IRPwbIg9yiDTrc,Yu-Gi-Oh! 2017 World Championship
15,Other,2020,Advanced,7,PLc1vyOIGc2qUwKZvwkAIZrfMup6QHDs-1,Remote Duel Invitational - TCG (8/22 - 8/23/2020)
16,WCQ,2024,Advanced,4,PLc1vyOIGc2qVX6ZJxab88NnmgUIZLDiLe,Dueling Archives: 2024 WQP Austin
17,World Championship,2024,Advanced,4,PLc1vyOIGc2qUluBlrVlUuTANCWpSAHjGa,Yu-Gi-Oh! World Championship 2024
18,WCQ,2013,Advanced,3,PLc1vyOIGc2qX9_zN-CyG1_GTPOvinQZ3Q,2013 North American WCQ
19,WCQ,2019,Advanced,3,PLc1vyOIGc2qXas2XPsp4wKpJDjshieo0N,Yu-Gi-Oh! 2019 North America WCQ
20,Other,2017,Advanced,3,PLc1vyOIGc2qVA85mAij71b89eAbdruY1u,"YCS San Diego (Nov 18-19, 2017)"
21,Other,2020,Advanced,2,PLc1vyOIGc2qXdSd5bAVaFUp3BTGDZPwgd,Team YCS Las Vegas 2020
22,Other,Unknown,Advanced,2,PLc1vyOIGc2qUpHELcFLe4ZE-JVw2enn54,Yu-Gi-Oh! Championship Series
23,Dragon Duel,2024,Advanced,1,PLc1vyOIGc2qUM7r-X3Abizu4s8qnfQwzG,Dueling Archives: 2024 WCQ Austin Dragon Duel ...

In [18]:
df = pd.read_parquet("pipeline/checkpoints/YuGiOhCardEU_parsed.parquet")
df

,Clean Title,Year,Category,Video Count,Playlist ID,Playlist Title
0,Other,2018,Advanced,78,PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl,YCS Bochum 2018 | Yu-Gi-Oh! Championship Serie...
1,WCQ,2015,Advanced,60,PLIm0Rt8gzRbss2nX1mixsDYj4CpmZ8ugW,WCQ: EC2015 | 2015 Yu-Gi-Oh! TCG WCQ: European...
2,WCQ,2016,Advanced,57,PLIm0Rt8gzRbvYYuWPcfcb1ZNQLCoPT5vm,WCQ: EC2016 | 2016 WCQ: European Championship
3,WCQ,2017,Advanced,54,PLIm0Rt8gzRbsHq8NXVNrIejQoUN3nMFfo,2017 WCQ: EC | 2017 WCQ: European Championship
4,Other,2018,Advanced,50,PLIm0Rt8gzRbvNmWVsRbgwdxXWcX1EXxh0,YCS Milan 2018 | Yu-Gi-Oh! Championship Series...
...,...,...,...,...,...,...
64,World Championship,2019,Advanced,7,PLIm0Rt8gzRbsxRacuVerQ4REzU6zRQFXt,Yu-Gi-Oh! World Championship 2019 - Berlin
65,Other,2021,Advanced,7,PLIm0Rt8gzRbtMPDnLGYFII_tUVnRM5ScA,Remote Duel Yu-Gi-Oh! Championship Series 2021...
66,Dragon Duel,2018,Advanced,7,PLIm0Rt8gzRbuauJOWCGiWGDMbOrK_4lZz,2018 Yu-Gi-Oh! TCG Dragon Duel World Championship
67,World Championship,2024,Advanced,6,PLIm0Rt8gzRbvlG2IvMeWgyI8VNEMLnuQ_,Yu-Gi-Oh! World Championship Series 2024
68,WCQ,2014,Advanced,1,PLIm0Rt8gzRbtTio1RMkWdRH9bkRNmX-Gh,WCQ: EC2014 | Yu-Gi-Oh! TCG WCQ: European Cham...

In [102]:
df = pd.read_parquet("pipeline/checkpoints/stage4_videos.parquet")
display(df)

,Playlist ID,Video ID,Title,Video Description,Clean Title,Year,Category,Playlist Title
0,PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl,s224f2XCeMo,YCS Bochum 2018: Welcome,"Footage recorded from Yu-Gi-Oh! YCS Bochum, he...",YCS Bochum,2018,YCS,YCS Bochum 2018 | Yu-Gi-Oh! Championship Serie...
1,PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl,UCaUi0WUV0A,YCS Bochum 2018: Event Spotlight,"Footage recorded from Yu-Gi-Oh! YCS Bochum, he...",YCS Bochum,2018,YCS,YCS Bochum 2018 | Yu-Gi-Oh! Championship Serie...
2,PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl,y8aTolgLcww,YCS Bochum 2018: Quick Questions,"Footage recorded from Yu-Gi-Oh! YCS Bochum, he...",YCS Bochum,2018,YCS,YCS Bochum 2018 | Yu-Gi-Oh! Championship Serie...
3,PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl,gr2n8RxtnBQ,YCS Bochum 2018: Meta Discussion,"Footage recorded from Yu-Gi-Oh! YCS Bochum, he...",YCS Bochum,2018,YCS,YCS Bochum 2018 | Yu-Gi-Oh! Championship Serie...
4,PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl,s68iNKx-chM,YCS Bochum 2018: Giant Card Spotlight,"Footage recorded from Yu-Gi-Oh! YCS Bochum, he...",YCS Bochum,2018,YCS,YCS Bochum 2018 | Yu-Gi-Oh! Championship Serie...
...,...,...,...,...,...,...,...,...
2019,PLc1vyOIGc2qXdSd5bAVaFUp3BTGDZPwgd,JjLkFrsrVy0,[Day 2] Team Yu-Gi-Oh! Championship Series - L...,Welcome to the Team Yu-Gi-Oh! Championship Ser...,YCS Las Vegas,2020,YCS,Team YCS Las Vegas 2020
2020,PLc1vyOIGc2qXdSd5bAVaFUp3BTGDZPwgd,jzDasFfd9BU,[Day 1] Team Yu-Gi-Oh! Championship Series - L...,Welcome to the Team Yu-Gi-Oh! Championship Ser...,YCS Las Vegas,2020,YCS,Team YCS Las Vegas 2020
2021,PLc1vyOIGc2qUpHELcFLe4ZE-JVw2enn54,CC4DnsceYTc,[Day 2] Yu-Gi-Oh! Championship Series - Pasade...,Welcome to the Yu-Gi-Oh! Championship Series i...,YCS,Unknown,YCS,Yu-Gi-Oh! Championship Series
2022,PLc1vyOIGc2qUpHELcFLe4ZE-JVw2enn54,3PS-97G3lBM,[Day 1] Yu-Gi-Oh! Championship Series - Pasade...,Welcome to the Yu-Gi-Oh! Championship Series i...,YCS,Unknown,YCS,Yu-Gi-Oh! Championship Series
2023,PLc1vyOIGc2qUM7r-X3Abizu4s8qnfQwzG,YrWkAofAm_E,"2024 North America Dragon Duel: Austin, TX// F...",Dragon Duel Final Match replay from 2024 WCQ A...,NA World Championship Austin Dragon Duel Finals,2024,Dragon Duel,Dueling Archives: 2024 WCQ Austin Dragon Duel ...

In [136]:
import pandas as pd
import re

RE_MATCH_INDICATOR = re.compile(  r'\bround\s*\d+|\btop\s*\d+|\bfinals?\b|\bsemi[-\s]?finals?\b|\bvs\.?\b|\b\d+(?:st|nd|rd|th)\s+place\b', re.IGNORECASE) 
RE_EXCLUDE = re.compile(r'\bannouncement\b|\binterview\b|\bdiscussion\b|\bvlog\b|\bdeck\s*profile\b', re.IGNORECASE)
RE_VS_PATTERN = re.compile(r'\bvs\.?\b', re.IGNORECASE)
RE_PLACEMENT = re.compile(r'\b\d+(?:st|nd|rd|th)\s+place\b', re.IGNORECASE)

df = pd.read_parquet("pipeline/checkpoints/stage4_videos.parquet")

match_mask   = df["Title"].str.contains(RE_MATCH_INDICATOR, na=False)
exclude_mask = df["Title"].str.contains(RE_EXCLUDE, na=False)

matches = df[match_mask & ~exclude_mask]
dropped = df[~match_mask | exclude_mask]

print(f"Kept: {len(matches)}")
print(f"Dropped: {len(dropped)}")

Kept: 1379
Dropped: 645

In [141]:
RE_LIVESTREAM_DAY = re.compile(r'\bday\s*[123]\b', re.IGNORECASE)

livestreams = dropped[dropped["Title"].str.contains(RE_LIVESTREAM_DAY, na=False)]
dropped_remaining = dropped[~dropped["Title"].str.contains(RE_LIVESTREAM_DAY, na=False)]

print(f"Livestreams: {len(livestreams)}")
print(f"Dropped (remaining): {len(dropped_remaining)}")

Livestreams: 63
Dropped (remaining): 582

In [140]:
dropped[dropped['Title'].str.contains('World')]['Title'].unique()

array(['The Road to Worlds',
       'Yu-Gi-Oh! World Championship Qualifier Utrecht 2017',
       'Yu-Gi-Oh! World Championship 2025 - President Emmanuel Macron\xa0Introduction',
       'Livestream | Yu-Gi-Oh! World Championship Master Duel 2025 | Day 1',
       'Livestream | Yu-Gi-Oh! World Championship Master Duel and Duel Links 2025 | Day 2',
       'Livestream | Yu-Gi-Oh! World Championship OCG/TCG 2025 | Day 2',
       'Yu-Gi-Oh! WCS 2025 | TCG World Championship Day 1 Impressions',
       'Yu-Gi-Oh! WCS 2025 | How to qualify for the World Championship? | Sebastian Lemke & Billy Brake',
       'Livestream | Yu-Gi-Oh! European World Championship Qualifier Berlin 2025 – Day 2',
       'Livestream | Yu-Gi-Oh! European World Championship Qualifier Berlin 2025 – Day 1',
       'Livestream | World Qualifying Points Play Off |\xa0Yu-Gi-Oh! European  WCQ Berlin 2025',
       'Livestream | Yu-Gi-Oh! European World Championship Qualifier Berlin 2024 – Day 2',
       'Livestream | Yu-Gi-Oh! European World Championship Qualifier Berlin 2024 – Day 1',
       '2018 Yu-Gi-Oh! TCG World Championship - Augmented-Reality Duel',
       '2018 Yu-Gi-Oh! TCG World Championship - Finalists Introduction',
       'Yu-Gi-Oh! World Championship 2018 [Qualifiers: Live Broadcast]',
       'Livestream | 2023 European World Championship Qualifier  – Day 2',
       'Livestream | 2023 European World Championship Qualifier – Day 1',
       '2014 World Championship: Behind The Scenes',
       '2014 Yu-Gi-Oh! TCG World Championship: Rimini City Tour',
       '[JP] 2017 World Championship | Exhibition Match | Augmented Reality Duel',
       '🔴 Livestream [DAY 1] – Yu-Gi-Oh! World Championship 2019 – Berlin',
       '🔴 Livestream [DAY 2]– Yu-Gi-Oh! World Championship 2019 – Berlin',
       'Yu-Gi-Oh! World Championship 2019 Recap',
       'How I got Invited to Worlds? All That You Want to Know FAQ - WCS 2019',
       'WCS 2019 Pre-Event Interview Raphael Neven, Galileo, Gabriel Vargas Breaks Down Worlds List',
       'Yu-Gi-Oh! World Championship Qualifier - Awards Ceremony',
       '[JP] 2017 World Championship Exhibition Match: Augmented Reality Duel',
       'Yu-Gi-Oh! TRADING CARD GAME World Championship 2024 – Day 1',
       'Yu-Gi-Oh! MASTER DUEL World Championship 2024 – Day 1',
       'Yu-Gi-Oh! DUEL LINKS World Championship 2024 – Day 1',
       'Yu-Gi-Oh! DUEL LINKS | MASTER DUEL | TCG World Championship 2024 – Day 2',
       'Yu-Gi-Oh! TRADING CARD GAME 2013 World Championship Message',
       'Yu-Gi-Oh! TCG 2019 North America World Championship Qualifier - Day 1',
       'Yu-Gi-Oh! TCG 2019 North America World Championship Qualifier - Day 3',
       'Yu-Gi-Oh! TCG 2019 North America World Championship Qualifier - Day 2'],
      dtype=object)

In [157]:
df = pd.read_parquet("pipeline/checkpoints/stage5_matches.parquet")
df

,Playlist ID,Video ID,Title,Video Description,Clean Title,Year,Category,Playlist Title
0,PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl,gtY3Gm81ckc,YCS Bochum 2018: Round 1 Feature Match,"Footage recorded from Yu-Gi-Oh! YCS Bochum, he...",YCS Bochum,2018,YCS,YCS Bochum 2018 | Yu-Gi-Oh! Championship Serie...
1,PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl,Lpam8Aii1vM,YCS Bochum 2018: Round 2 Feature Match,"Footage recorded from Yu-Gi-Oh! YCS Bochum, he...",YCS Bochum,2018,YCS,YCS Bochum 2018 | Yu-Gi-Oh! Championship Serie...
2,PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl,wRwnUvpcyKA,YCS Bochum 2018: Round 3 Feature Match,"Footage recorded from Yu-Gi-Oh! YCS Bochum, he...",YCS Bochum,2018,YCS,YCS Bochum 2018 | Yu-Gi-Oh! Championship Serie...
3,PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl,tpR87uZpnfU,YCS Bochum 2018: Round 4 Feature Match,"Footage recorded from Yu-Gi-Oh! YCS Bochum, he...",YCS Bochum,2018,YCS,YCS Bochum 2018 | Yu-Gi-Oh! Championship Serie...
4,PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl,Dwp_1bljFLo,YCS Bochum 2018: Round 5 Feature Match,"Footage recorded from Yu-Gi-Oh! YCS Bochum, he...",YCS Bochum,2018,YCS,YCS Bochum 2018 | Yu-Gi-Oh! Championship Serie...
...,...,...,...,...,...,...,...,...
1374,PLc1vyOIGc2qVX6ZJxab88NnmgUIZLDiLe,ZrD5_lg5ioc,"2024 North America WQP: Austin, TX // Top 16 -...",WQP Austin Top 16 Match Replay between George ...,WQP Austin,2024,WQP,Dueling Archives: 2024 WQP Austin
1375,PLc1vyOIGc2qVX6ZJxab88NnmgUIZLDiLe,ZkyHjeRmmPs,"2024 North America WQP: Austin, TX // Top 8 - ...",WQP Austin Top 8 Match Replay between Logan J....,WQP Austin,2024,WQP,Dueling Archives: 2024 WQP Austin
1376,PLc1vyOIGc2qVX6ZJxab88NnmgUIZLDiLe,FIhfBEclMv0,"2024 North America WQP: Austin, TX // Semi Fin...",WQP Austin Semi Final Match Replay between Geo...,WQP Austin,2024,WQP,Dueling Archives: 2024 WQP Austin
1377,PLc1vyOIGc2qVX6ZJxab88NnmgUIZLDiLe,-y24Ncvio-o,"2024 North America WQP: Austin, TX // Semi Fin...",WQP Austin Semi Final Match Replay between Log...,WQP Austin,2024,WQP,Dueling Archives: 2024 WQP Austin
1378,PLc1vyOIGc2qUM7r-X3Abizu4s8qnfQwzG,YrWkAofAm_E,"2024 North America Dragon Duel: Austin, TX// F...",Dragon Duel Final Match replay from 2024 WCQ A...,NA World Championship Austin Dragon Duel Finals,2024,Dragon Duel,Dueling Archives: 2024 WCQ Austin Dragon Duel ...

In [158]:
df = pd.read_parquet("pipeline/checkpoints/livestreams.parquet")
df

,Playlist ID,Video ID,Title,Video Description,Clean Title,Year,Category,Playlist Title
0,PLIm0Rt8gzRbvYYuWPcfcb1ZNQLCoPT5vm,MqK7qRQbbj4,WCQ Berlin: Impressions Day 2,Yu-Gi-Oh! TRADING CARD GAME\r\n © 1996 Kazuki ...,EU World Championship Qualifer,2016,World Championship,WCQ: EC2016 | 2016 WCQ: European Championship
1,PLIm0Rt8gzRbvYYuWPcfcb1ZNQLCoPT5vm,bUStmUogIY8,WCQ Berlin: Impressions Day 1,Yu-Gi-Oh! TRADING CARD GAME\r\n © 1996 Kazuki ...,EU World Championship Qualifer,2016,World Championship,WCQ: EC2016 | 2016 WCQ: European Championship
2,PLIm0Rt8gzRbuI3ij0C4yrfAQb8tMbtCt8,HmtSUuOGztM,Livestream | Yu-Gi-Oh! Championship Series Bol...,Watch the day 2 livestream of Yu-Gi-Oh! Champi...,YCS Bologna,2025,YCS,YCS Bologna 2025
3,PLIm0Rt8gzRbuI3ij0C4yrfAQb8tMbtCt8,pIvUeWm9lWU,Livestream | Yu-Gi-Oh! Championship Series Bol...,Watch the day 1 livestream of Yu-Gi-Oh! Champi...,YCS Bologna,2025,YCS,YCS Bologna 2025
4,PLIm0Rt8gzRbvUqBmSmnIEr9nTIFuqAW_F,CtMLNdRJ3u4,Livestream | Yu-Gi-Oh! World Championship Mast...,"©2020 Studio Dice／SHUEISHA, TV TOKYO, KONAMI\n...",World Championship Paris France,2025,World Championship,"Yu-Gi-Oh! World Championship 2025 - Paris, France"
...,...,...,...,...,...,...,...,...
58,PLc1vyOIGc2qVA85mAij71b89eAbdruY1u,IA6scolIkt0,Yu-Gi-Oh! TCG - YCS San Diego 2017 Day 2,,YCS San Diego,2017,YCS,"YCS San Diego (Nov 18-19, 2017)"
59,PLc1vyOIGc2qXdSd5bAVaFUp3BTGDZPwgd,JjLkFrsrVy0,[Day 2] Team Yu-Gi-Oh! Championship Series - L...,Welcome to the Team Yu-Gi-Oh! Championship Ser...,YCS Las Vegas,2020,YCS,Team YCS Las Vegas 2020
60,PLc1vyOIGc2qXdSd5bAVaFUp3BTGDZPwgd,jzDasFfd9BU,[Day 1] Team Yu-Gi-Oh! Championship Series - L...,Welcome to the Team Yu-Gi-Oh! Championship Ser...,YCS Las Vegas,2020,YCS,Team YCS Las Vegas 2020
61,PLc1vyOIGc2qUpHELcFLe4ZE-JVw2enn54,CC4DnsceYTc,[Day 2] Yu-Gi-Oh! Championship Series - Pasade...,Welcome to the Yu-Gi-Oh! Championship Series i...,YCS,Unknown,YCS,Yu-Gi-Oh! Championship Series
62,PLc1vyOIGc2qUpHELcFLe4ZE-JVw2enn54,3PS-97G3lBM,[Day 1] Yu-Gi-Oh! Championship Series - Pasade...,Welcome to the Yu-Gi-Oh! Championship Series i...,YCS,Unknown,YCS,Yu-Gi-Oh! Championship Series

In [177]:
df = pd.read_parquet("pipeline/checkpoints/stage5_matches.parquet")  # adjust to your actual stage5 output filename
llm_input = df[["Video ID", "Title", "Video Description"]].copy()
llm_input["Video Description"] = llm_input["Video Description"].str[:200]  # trim long descriptions

In [183]:
from groq import Groq
import os
import json
import pandas as pd
from dotenv import load_dotenv
load_dotenv()

client = Groq(api_key=os.getenv("GROQ_API_KEY"))

sample = llm_input.sample(n=20, random_state=56)
sample_records = sample[["Video ID", "Title", "Video Description"]].to_dict("records")

prompt = """
You are a Yu-Gi-Oh! feature match classification system.

You will receive a JSON array of videos. For EVERY video in the input, return EXACTLY ONE object in the output array.

A feature match is a real recorded duel between two identifiable players.
Livestreams, vlogs, deck profiles, promos, interviews, and commentary-only videos are NOT feature matches.

IMPORTANT: Titles containing round/bracket stage indicators (e.g. "Round X", "Top X", "Quarterfinal", 
"Semi-Final", "Final") almost always indicate a feature match, even if player names are not present 
in the title or description. Player names being unavailable does NOT mean it's not a match — 
set player_1/player_2/deck_1/deck_2 to null in that case, but still mark is_match as true.

Return ONLY a valid JSON array, one object per input video, in the same order, using this schema:

{
  "video_id": string,
  "is_match": true or false,
  "tournament": string or null,
  "round": string or null,
  "player_1": string or null,
  "deck_1": string or null,
  "player_2": string or null,
  "deck_2": string or null
}

RULES:
- ALWAYS include "video_id" exactly as given in the input.
- If is_match is false, set all other fields to null.
- Round must be formatted exactly like: "Round 1", "Top 32", "Finals", "Semi-Final", "Quarterfinal"
- Tournament should be the event name (e.g. "YCS London 2024")
- Do NOT guess missing players or decks — use null if unknown

INPUT:
""" + json.dumps(sample_records)

response = client.chat.completions.create(
    model="llama-3.1-8b-instant",
    messages=[{"role": "user", "content": prompt}],
    temperature=0,
    max_tokens=8192
)

content = response.choices[0].message.content.strip()

# strip markdown code fences if present
if content.startswith("```"):
    content = content.split("```")[1]
    if content.startswith("json"):
        content = content[4:]
    content = content.strip()

parsed = json.loads(content)
results_df = pd.DataFrame(parsed)
results_df

,video_id,is_match,tournament,round,player_1,deck_1,player_2,deck_2
0,QZ6RLokEP2c,True,WCQ 2017 Utrecht,None,Noah Riffel,Zoodiac,Reuben Baron,Zoodiac
1,ISsuUwHMeK4,True,YCS Utrecht 2022,Round 4,Niklas A.,Runick Spright,Sebastian F.,P.U.N.K
2,843BaEKEcwk,True,EU WQP Playoff Berlin 2025,Round 1,Ben K.,Vanquish Soul,Danilo S.,Mementotlan
3,KywLxddxPEk,True,YCS Dortmund 2022,TOP 8,Mario A.,Floowandereeze,Eteeyen I.,Ishizu Tearlaments
4,Sr5-PQxpT5c,True,YCS Bologna 2024,Round 11,Dinh-Kha B.,Fiendsmith Kashtira,Vincenzo C.,Bystial Centur-Ion
5,QFmOS8P6XEo,False,None,None,None,None,None,None
6,-ZvcNaV70pM,True,YCS 2017 Prague,Round 1,Christian Habicht,Zoodiac,Danny Goldmann,Paleozoic
7,fHfd7DRvEdc,True,YCS 2017 Prague,Top 4,Joshua Schmidt,60 Cards Paleozoic,Jawed Sayeed Chowdhury,60 Cards Infernoid Zoodiac
8,VolgsU2bLZ4,True,Italian OPEN May 2024,Round 3,Zuccatelli J.,Branded Despia,Cefola A.,Floowandereeze
9,p2CWlEL-k1E,True,YCS London 2017,Round 7,Mirko Zanelli,None,John Lascelles,None
10,iJSPfEkubQc,True,Ultimate Time Wizard 2010 YCS Birmingham 2025,Round 8,Frogs,None,Blackwing,None
11,5UxWdxmr95U,True,2018 WCQ: European Championship - Berlin,Top 16,Simon Franke,Gouki,Jake Quinse,Gouki
12,6pxaxWCxyqg,True,"2025 North America YCS Houston, TX",Top 16,Aditya D.,None,Bryce S.,None
13,8DQggTHhukI,True,2024 World Championship Series - Duel Links Ru...,Final,Voltalon,None,QunatumCubes,None
14,lFyEaeG2FcY,True,YCS Bochum 2018,Round 7,Stefan Frankowski,None,Dinh Khang Pham,None
15,Ldklbb5NgBw,True,2017 World Championship,Semi Final,Marcello Barberi,None,Shen-Fei Milton Chua,None
16,AHbxLTJiF_o,True,Italian OPEN May 2024,Round 8,Pastore M.,Melodious,Kelly C.,Snake-Eye
17,MH_esuOgueI,True,"2025 North America YCS Houston, TX",Semi Final 2,Pascal M.,None,Kevin Z.,None
18,-cGqaoYXRfU,True,Yu-Gi-Oh! TCG Italian OPEN January 2025,Round 2,Nusca A.,Melodious,Barsacchi D.,Eldlich
19,9DMxJgAPFIY,False,None,None,None,None,None,None

In [229]:
prompt_template = """
You are a Yu-Gi-Oh! feature match classification system.

You will receive a JSON array of videos. For EVERY video in the input, return EXACTLY ONE object in the output array.

A feature match is a real recorded duel between two identifiable players.
Livestreams, vlogs, deck profiles, promos, interviews, and commentary-only videos are NOT feature matches.

IMPORTANT: Titles containing round/bracket stage indicators (e.g. "Round X", "Top X", "Quarterfinal", 
"Semi-Final", "Final") almost always indicate a feature match, even if player names are not present 
in the title or description. Player names being unavailable does NOT mean it's not a match — 
set player_1/player_2/deck_1/deck_2 to null in that case, but still mark is_match as true.

Return ONLY a valid JSON array, one object per input video, in the same order, using this schema:

{
  "video_id": string,
  "is_match": true or false,
  "tournament": string or null,
  "round": string or null,
  "player_1": string or null,
  "deck_1": string or null,
  "player_2": string or null,
  "deck_2": string or null
}


RULES:
- ALWAYS include "video_id" exactly as given in the input.
- If is_match is false, set all other fields to null.
- Round must be formatted exactly like: "Round 1", "Top 32", "Finals", "Semi-Final", "Quarterfinal"
- Tournament should be the event name (e.g. "YCS London 2024")
- Do NOT guess missing players or decks — use null if unknown
- DO NOT write Python or JavaScript.
- DO NOT explain.
- DO NOT wrap in ```json.
- DO NOT write any text before or after the JSON.
- The first character of your response MUST be [
- The last character of your response MUST be ]

INPUT:
"""

def safe_parse_json(content: str):
    if content.startswith("```"):
        content = content.split("```")[1]
        if content.startswith("json"):
            content = content[4:]
        content = content.strip()

    try:
        return json.loads(content)
    except json.JSONDecodeError as e:
        print(f"JSON parse failed: {e}")
        print(f"Raw content (last 300 chars): {content[-300:]}")
        return None

In [233]:
import time

all_results = []
chunk_size = 10
rows = llm_input.to_dict("records")
total_chunks = -(-len(rows) // chunk_size)

for i in range(0, len(rows), chunk_size):
    chunk_id = i // chunk_size + 1
    chunk = rows[i:i + chunk_size]

    print(f"Processing chunk {chunk_id}/{total_chunks}")

    chunk_prompt = prompt_template + json.dumps(chunk, ensure_ascii=False)

    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[{"role": "user", "content": chunk_prompt}],
        temperature=0,
        max_tokens=1000,
        response_format={"type": "json_object"}
    )

    content = response.choices[0].message.content.strip()
    parsed = safe_parse_json(content)

    if parsed is not None:
        all_results.extend(parsed)
        print(f"  ✓ {len(parsed)} rows returned")
    else:
        print(f"  ✗ chunk {chunk_id} failed — skipping")

    if i + chunk_size < len(rows):  # don't sleep after the last chunk
        time.sleep(30)
        # break

results_df = pd.DataFrame(all_results)
print(f"\nTotal rows processed: {len(results_df)} / {len(rows)}")

Processing chunk 1/138
  ✓ 10 rows returned
Processing chunk 2/138
  ✓ 10 rows returned
Processing chunk 3/138
  ✓ 10 rows returned
Processing chunk 4/138
  ✓ 10 rows returned
Processing chunk 5/138
  ✓ 10 rows returned
Processing chunk 6/138
  ✓ 10 rows returned
Processing chunk 7/138
  ✓ 10 rows returned
Processing chunk 8/138
  ✓ 10 rows returned
Processing chunk 9/138
  ✓ 10 rows returned
Processing chunk 10/138
  ✓ 10 rows returned
Processing chunk 11/138
  ✓ 10 rows returned
Processing chunk 12/138
  ✓ 10 rows returned
Processing chunk 13/138
  ✓ 10 rows returned
Processing chunk 14/138
  ✓ 10 rows returned
Processing chunk 15/138
  ✓ 10 rows returned
Processing chunk 16/138
  ✓ 10 rows returned
Processing chunk 17/138
  ✓ 10 rows returned
Processing chunk 18/138
  ✓ 10 rows returned
Processing chunk 19/138
  ✓ 10 rows returned
Processing chunk 20/138
  ✓ 10 rows returned
Processing chunk 21/138
  ✓ 10 rows returned
Processing chunk 22/138
  ✓ 10 rows returned
Processing chunk 23/138
  ✓ 10 rows returned
Processing chunk 24/138
  ✓ 10 rows returned
Processing chunk 25/138
  ✓ 10 rows returned
Processing chunk 26/138
  ✓ 10 rows returned
Processing chunk 27/138
  ✓ 10 rows returned
Processing chunk 28/138
  ✓ 10 rows returned
Processing chunk 29/138
  ✓ 10 rows returned
Processing chunk 30/138
  ✓ 10 rows returned
Processing chunk 31/138
  ✓ 10 rows returned
Processing chunk 32/138

RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kw2wctxxekn9jf2z6prmcb89` service tier `on_demand` on tokens per day (TPD): Limit 100000, Used 98180, Requested 2388. Please try again in 8m10.752s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

In [232]:
results_df

,video_id,is_match,tournament,round,player_1,deck_1,player_2,deck_2
0,gtY3Gm81ckc,True,YCS Bochum 2018,Round 1,Jörg Müller,None,Eugen Heidt,None
1,Lpam8Aii1vM,True,YCS Bochum 2018,Round 2,Phillip Weldinger,None,Meicel Neugebauer,None
2,wRwnUvpcyKA,True,YCS Bochum 2018,Round 3,Carmelo Buttiglieri,None,Adam Chamberlain,None
3,tpR87uZpnfU,True,YCS Bochum 2018,Round 4,Jordan Gallacher,None,Steffen Friedow,None
4,Dwp_1bljFLo,True,YCS Bochum 2018,Round 5,Loan Cite-Mielle,None,David Schmidt,None
5,hkJI_gl53hY,True,YCS Bochum 2018,Round 6,Jakob Geigenberger,None,Viktor Trautwein,None
6,lFyEaeG2FcY,True,YCS Bochum 2018,Round 7,Stefan Frankowski,None,Dinh Khang Pham,None
7,vHk2Ze_AxqA,True,YCS Bochum 2018,Round 8,Timothy Cox,None,Bastien Magnee,None
8,X9M7wHqHqzY,True,YCS Bochum 2018,Round 9,Tomas Tuvillo,None,Georgior Kotogluo,None
9,3xxBoLE-MiU,True,YCS Bochum 2018,Round 10,Markus Schmidt,None,Estanita Martina,None