In [11]:
import pandas as pd

In [13]:
df = pd.read_parquet("pipeline/checkpoints/stage1_playlists_@OfficialYuGiOhTCG.parquet")
df

,Playlist Title,Video Count,Playlist ID
0,Chaos Origins,5,PLc1vyOIGc2qXR_Ym2ulQU-JQAwsL6mUs1
1,Battles of Legend: Glorious Gallery,3,PLc1vyOIGc2qU8wh9cPNF82OcKnw5IFccF
2,Blazing Dominion,4,PLc1vyOIGc2qXHIlcNpiK5UnxcUp02mkE-
3,Rarity Collection V,6,PLc1vyOIGc2qW7vPoPEzFNxnV54Q2qIOV6
4,Legendary Modern Decks 2026,5,PLc1vyOIGc2qX01LHO_FEuNuoA_XuYaoxU
...,...,...,...
118,Yu-Gi-Oh! 2015 North American WCQ,24,PLc1vyOIGc2qXKkGwYHOU-m5dBqMU8FDpt
119,How To Play Tutorials,5,PLc1vyOIGc2qVb3yvIXCuRD9wEH4YgGGhf
120,Yu-Gi-Oh! 150th YCS Columbus,15,PLc1vyOIGc2qVerc4qlE4na0TZRH0oRUix
121,YGO 2015 Products,12,PLc1vyOIGc2qUW0RKRuakuSJE2OXhtq8oN
122,2013 North American WCQ,3,PLc1vyOIGc2qX9_zN-CyG1_GTPOvinQZ3Q

In [14]:
df = pd.read_parquet("pipeline/checkpoints/stage1_playlists_@YuGiOhCardEU.parquet")
df

,Playlist Title,Video Count,Playlist ID
0,Yu-Gi-Oh! TCG | Chaos Origins Unboxing Series,21,PLIm0Rt8gzRbusJI2gZfgTOYXDp8DyhL-U
1,Yu-Gi-Oh! TCG | Battles of Legend: Glorious Ga...,22,PLIm0Rt8gzRbskxI-lI7pC0klGQw5FLGBI
2,Yu-Gi-Oh! TCG | Blazing Dominion Unboxing Series,22,PLIm0Rt8gzRbtYPRjkHV_z8WgY1I42EJdc
3,Yu-Gi-Oh! Rarity Collection,4,PLIm0Rt8gzRbv2hsmR9PrFpmOlwSKVDArh
4,Yu-Gi-Oh! TCG Rarity Collection 5 Reveals!,21,PLIm0Rt8gzRbuQw2N4O0oOvc5gOnPUO8dz
...,...,...,...
128,YCS Madrid | Yu-Gi-Oh! Championship Series Madrid,16,PLIm0Rt8gzRbtE1wXv0kUYBP4GeNUnpFdg
129,YCS Milan | Yu-Gi-Oh! Championship Series Milan,18,PLIm0Rt8gzRbu5uULuK4WArO6Ii3VRo12L
130,YCS Prague | Yu-Gi-Oh! Championship Series Prague,32,PLIm0Rt8gzRbu5rDW3wVN5G_Zcg_G53RB9
131,WCQ: EC2015 | 2015 Yu-Gi-Oh! TCG WCQ: European...,60,PLIm0Rt8gzRbss2nX1mixsDYj4CpmZ8ugW
132,YCS Bochum | Yu-Gi-Oh! Championship Series Bochum,38,PLIm0Rt8gzRbudSiIYYy2neWhQqecruQNU

In [17]:
df = pd.read_parquet("pipeline/checkpoints/OfficialYuGiOhTCG_parsed.parquet")
df

,Clean Title,Year,Category,Video Count,Playlist ID,Playlist Title
0,World Championship,2019,Advanced,26,PLc1vyOIGc2qUclsFSVx6fWVI0pI9TQDUp,Yu-Gi-Oh! World Championship 2019
1,WCQ,2015,Advanced,24,PLc1vyOIGc2qXKkGwYHOU-m5dBqMU8FDpt,Yu-Gi-Oh! 2015 North American WCQ
2,WCQ,2023,Advanced,23,PLc1vyOIGc2qWFXx4GRFFbiv3AR1wxD3yV,Dueling Archives: North American WCQ 2023
3,Other,Unknown,Advanced,18,PLc1vyOIGc2qX-zEOY_FPbKQtkJVyd-5jM,Dueling Archives: NAWCQ Indianapolis
4,WCQ,2024,Advanced,18,PLc1vyOIGc2qUPQ3Al4_8S6QJ__QFSVAaO,Dueling Archives: 2024 WCQ Austin
5,Other,2025,Advanced,18,PLc1vyOIGc2qUy8UruoP-7uEa-cgG6KRjO,Dueling Archives: YCS Houston 2025
6,Other,2025,Advanced,18,PLc1vyOIGc2qVR3zjIHAQmLCdrtFEDZT99,Dueling Archives - YCS Orlando 2025
7,Other,2025,Advanced,17,PLc1vyOIGc2qUdrzkwxpyWPF7hEA-4nxYM,Dueling Archives: YCS Providence 2025
8,Other,2024,Advanced,17,PLc1vyOIGc2qXZj0ml7PjZVotk9u4BKL8Z,Dueling Archives: 2024 YCS Raleigh
9,Other,Unknown,Advanced,16,PLc1vyOIGc2qW5Sc7c0ZFOtfPYr4Z5t8Bi,"Dueling Archives: 250th YCS: Los Angeles, CA"
10,Other,2024,Advanced,16,PLc1vyOIGc2qVH_lI0WeiyavM_XOAQoCnH,Dueling Archives: YCS Sacramento 2024
11,Other,2024,Advanced,15,PLc1vyOIGc2qVGiERh0olzUkkdjXVBzNi3,Dueling Archives - YCS Anaheim 2024
12,Other,2024,Advanced,15,PLc1vyOIGc2qVxjActmFOJHlVit2Y06w0C,Dueling Archives: 2024 YCS Indianapolis
13,Other,Unknown,Advanced,15,PLc1vyOIGc2qVerc4qlE4na0TZRH0oRUix,Yu-Gi-Oh! 150th YCS Columbus
14,World Championship,2017,Advanced,13,PLc1vyOIGc2qVsXghcP-IRPwbIg9yiDTrc,Yu-Gi-Oh! 2017 World Championship
15,Other,2020,Advanced,7,PLc1vyOIGc2qUwKZvwkAIZrfMup6QHDs-1,Remote Duel Invitational - TCG (8/22 - 8/23/2020)
16,WCQ,2024,Advanced,4,PLc1vyOIGc2qVX6ZJxab88NnmgUIZLDiLe,Dueling Archives: 2024 WQP Austin
17,World Championship,2024,Advanced,4,PLc1vyOIGc2qUluBlrVlUuTANCWpSAHjGa,Yu-Gi-Oh! World Championship 2024
18,WCQ,2013,Advanced,3,PLc1vyOIGc2qX9_zN-CyG1_GTPOvinQZ3Q,2013 North American WCQ
19,WCQ,2019,Advanced,3,PLc1vyOIGc2qXas2XPsp4wKpJDjshieo0N,Yu-Gi-Oh! 2019 North America WCQ
20,Other,2017,Advanced,3,PLc1vyOIGc2qVA85mAij71b89eAbdruY1u,"YCS San Diego (Nov 18-19, 2017)"
21,Other,2020,Advanced,2,PLc1vyOIGc2qXdSd5bAVaFUp3BTGDZPwgd,Team YCS Las Vegas 2020
22,Other,Unknown,Advanced,2,PLc1vyOIGc2qUpHELcFLe4ZE-JVw2enn54,Yu-Gi-Oh! Championship Series
23,Dragon Duel,2024,Advanced,1,PLc1vyOIGc2qUM7r-X3Abizu4s8qnfQwzG,Dueling Archives: 2024 WCQ Austin Dragon Duel ...

In [18]:
df = pd.read_parquet("pipeline/checkpoints/YuGiOhCardEU_parsed.parquet")
df

,Clean Title,Year,Category,Video Count,Playlist ID,Playlist Title
0,Other,2018,Advanced,78,PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl,YCS Bochum 2018 | Yu-Gi-Oh! Championship Serie...
1,WCQ,2015,Advanced,60,PLIm0Rt8gzRbss2nX1mixsDYj4CpmZ8ugW,WCQ: EC2015 | 2015 Yu-Gi-Oh! TCG WCQ: European...
2,WCQ,2016,Advanced,57,PLIm0Rt8gzRbvYYuWPcfcb1ZNQLCoPT5vm,WCQ: EC2016 | 2016 WCQ: European Championship
3,WCQ,2017,Advanced,54,PLIm0Rt8gzRbsHq8NXVNrIejQoUN3nMFfo,2017 WCQ: EC | 2017 WCQ: European Championship
4,Other,2018,Advanced,50,PLIm0Rt8gzRbvNmWVsRbgwdxXWcX1EXxh0,YCS Milan 2018 | Yu-Gi-Oh! Championship Series...
...,...,...,...,...,...,...
64,World Championship,2019,Advanced,7,PLIm0Rt8gzRbsxRacuVerQ4REzU6zRQFXt,Yu-Gi-Oh! World Championship 2019 - Berlin
65,Other,2021,Advanced,7,PLIm0Rt8gzRbtMPDnLGYFII_tUVnRM5ScA,Remote Duel Yu-Gi-Oh! Championship Series 2021...
66,Dragon Duel,2018,Advanced,7,PLIm0Rt8gzRbuauJOWCGiWGDMbOrK_4lZz,2018 Yu-Gi-Oh! TCG Dragon Duel World Championship
67,World Championship,2024,Advanced,6,PLIm0Rt8gzRbvlG2IvMeWgyI8VNEMLnuQ_,Yu-Gi-Oh! World Championship Series 2024
68,WCQ,2014,Advanced,1,PLIm0Rt8gzRbtTio1RMkWdRH9bkRNmX-Gh,WCQ: EC2014 | Yu-Gi-Oh! TCG WCQ: European Cham...

In [102]:
df = pd.read_parquet("pipeline/checkpoints/stage4_videos.parquet")
display(df)

,Playlist ID,Video ID,Title,Video Description,Clean Title,Year,Category,Playlist Title
0,PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl,s224f2XCeMo,YCS Bochum 2018: Welcome,"Footage recorded from Yu-Gi-Oh! YCS Bochum, he...",YCS Bochum,2018,YCS,YCS Bochum 2018 | Yu-Gi-Oh! Championship Serie...
1,PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl,UCaUi0WUV0A,YCS Bochum 2018: Event Spotlight,"Footage recorded from Yu-Gi-Oh! YCS Bochum, he...",YCS Bochum,2018,YCS,YCS Bochum 2018 | Yu-Gi-Oh! Championship Serie...
2,PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl,y8aTolgLcww,YCS Bochum 2018: Quick Questions,"Footage recorded from Yu-Gi-Oh! YCS Bochum, he...",YCS Bochum,2018,YCS,YCS Bochum 2018 | Yu-Gi-Oh! Championship Serie...
3,PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl,gr2n8RxtnBQ,YCS Bochum 2018: Meta Discussion,"Footage recorded from Yu-Gi-Oh! YCS Bochum, he...",YCS Bochum,2018,YCS,YCS Bochum 2018 | Yu-Gi-Oh! Championship Serie...
4,PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl,s68iNKx-chM,YCS Bochum 2018: Giant Card Spotlight,"Footage recorded from Yu-Gi-Oh! YCS Bochum, he...",YCS Bochum,2018,YCS,YCS Bochum 2018 | Yu-Gi-Oh! Championship Serie...
...,...,...,...,...,...,...,...,...
2019,PLc1vyOIGc2qXdSd5bAVaFUp3BTGDZPwgd,JjLkFrsrVy0,[Day 2] Team Yu-Gi-Oh! Championship Series - L...,Welcome to the Team Yu-Gi-Oh! Championship Ser...,YCS Las Vegas,2020,YCS,Team YCS Las Vegas 2020
2020,PLc1vyOIGc2qXdSd5bAVaFUp3BTGDZPwgd,jzDasFfd9BU,[Day 1] Team Yu-Gi-Oh! Championship Series - L...,Welcome to the Team Yu-Gi-Oh! Championship Ser...,YCS Las Vegas,2020,YCS,Team YCS Las Vegas 2020
2021,PLc1vyOIGc2qUpHELcFLe4ZE-JVw2enn54,CC4DnsceYTc,[Day 2] Yu-Gi-Oh! Championship Series - Pasade...,Welcome to the Yu-Gi-Oh! Championship Series i...,YCS,Unknown,YCS,Yu-Gi-Oh! Championship Series
2022,PLc1vyOIGc2qUpHELcFLe4ZE-JVw2enn54,3PS-97G3lBM,[Day 1] Yu-Gi-Oh! Championship Series - Pasade...,Welcome to the Yu-Gi-Oh! Championship Series i...,YCS,Unknown,YCS,Yu-Gi-Oh! Championship Series
2023,PLc1vyOIGc2qUM7r-X3Abizu4s8qnfQwzG,YrWkAofAm_E,"2024 North America Dragon Duel: Austin, TX// F...",Dragon Duel Final Match replay from 2024 WCQ A...,NA World Championship Austin Dragon Duel Finals,2024,Dragon Duel,Dueling Archives: 2024 WCQ Austin Dragon Duel ...

In [136]:
import pandas as pd
import re

RE_MATCH_INDICATOR = re.compile(  r'\bround\s*\d+|\btop\s*\d+|\bfinals?\b|\bsemi[-\s]?finals?\b|\bvs\.?\b|\b\d+(?:st|nd|rd|th)\s+place\b', re.IGNORECASE) 
RE_EXCLUDE = re.compile(r'\bannouncement\b|\binterview\b|\bdiscussion\b|\bvlog\b|\bdeck\s*profile\b', re.IGNORECASE)
RE_VS_PATTERN = re.compile(r'\bvs\.?\b', re.IGNORECASE)
RE_PLACEMENT = re.compile(r'\b\d+(?:st|nd|rd|th)\s+place\b', re.IGNORECASE)

df = pd.read_parquet("pipeline/checkpoints/stage4_videos.parquet")

match_mask   = df["Title"].str.contains(RE_MATCH_INDICATOR, na=False)
exclude_mask = df["Title"].str.contains(RE_EXCLUDE, na=False)

matches = df[match_mask & ~exclude_mask]
dropped = df[~match_mask | exclude_mask]

print(f"Kept: {len(matches)}")
print(f"Dropped: {len(dropped)}")

Kept: 1379
Dropped: 645

In [141]:
RE_LIVESTREAM_DAY = re.compile(r'\bday\s*[123]\b', re.IGNORECASE)

livestreams = dropped[dropped["Title"].str.contains(RE_LIVESTREAM_DAY, na=False)]
dropped_remaining = dropped[~dropped["Title"].str.contains(RE_LIVESTREAM_DAY, na=False)]

print(f"Livestreams: {len(livestreams)}")
print(f"Dropped (remaining): {len(dropped_remaining)}")

Livestreams: 63
Dropped (remaining): 582

In [140]:
dropped[dropped['Title'].str.contains('World')]['Title'].unique()

array(['The Road to Worlds',
       'Yu-Gi-Oh! World Championship Qualifier Utrecht 2017',
       'Yu-Gi-Oh! World Championship 2025 - President Emmanuel Macron\xa0Introduction',
       'Livestream | Yu-Gi-Oh! World Championship Master Duel 2025 | Day 1',
       'Livestream | Yu-Gi-Oh! World Championship Master Duel and Duel Links 2025 | Day 2',
       'Livestream | Yu-Gi-Oh! World Championship OCG/TCG 2025 | Day 2',
       'Yu-Gi-Oh! WCS 2025 | TCG World Championship Day 1 Impressions',
       'Yu-Gi-Oh! WCS 2025 | How to qualify for the World Championship? | Sebastian Lemke & Billy Brake',
       'Livestream | Yu-Gi-Oh! European World Championship Qualifier Berlin 2025 – Day 2',
       'Livestream | Yu-Gi-Oh! European World Championship Qualifier Berlin 2025 – Day 1',
       'Livestream | World Qualifying Points Play Off |\xa0Yu-Gi-Oh! European  WCQ Berlin 2025',
       'Livestream | Yu-Gi-Oh! European World Championship Qualifier Berlin 2024 – Day 2',
       'Livestream | Yu-Gi-Oh! European World Championship Qualifier Berlin 2024 – Day 1',
       '2018 Yu-Gi-Oh! TCG World Championship - Augmented-Reality Duel',
       '2018 Yu-Gi-Oh! TCG World Championship - Finalists Introduction',
       'Yu-Gi-Oh! World Championship 2018 [Qualifiers: Live Broadcast]',
       'Livestream | 2023 European World Championship Qualifier  – Day 2',
       'Livestream | 2023 European World Championship Qualifier – Day 1',
       '2014 World Championship: Behind The Scenes',
       '2014 Yu-Gi-Oh! TCG World Championship: Rimini City Tour',
       '[JP] 2017 World Championship | Exhibition Match | Augmented Reality Duel',
       '🔴 Livestream [DAY 1] – Yu-Gi-Oh! World Championship 2019 – Berlin',
       '🔴 Livestream [DAY 2]– Yu-Gi-Oh! World Championship 2019 – Berlin',
       'Yu-Gi-Oh! World Championship 2019 Recap',
       'How I got Invited to Worlds? All That You Want to Know FAQ - WCS 2019',
       'WCS 2019 Pre-Event Interview Raphael Neven, Galileo, Gabriel Vargas Breaks Down Worlds List',
       'Yu-Gi-Oh! World Championship Qualifier - Awards Ceremony',
       '[JP] 2017 World Championship Exhibition Match: Augmented Reality Duel',
       'Yu-Gi-Oh! TRADING CARD GAME World Championship 2024 – Day 1',
       'Yu-Gi-Oh! MASTER DUEL World Championship 2024 – Day 1',
       'Yu-Gi-Oh! DUEL LINKS World Championship 2024 – Day 1',
       'Yu-Gi-Oh! DUEL LINKS | MASTER DUEL | TCG World Championship 2024 – Day 2',
       'Yu-Gi-Oh! TRADING CARD GAME 2013 World Championship Message',
       'Yu-Gi-Oh! TCG 2019 North America World Championship Qualifier - Day 1',
       'Yu-Gi-Oh! TCG 2019 North America World Championship Qualifier - Day 3',
       'Yu-Gi-Oh! TCG 2019 North America World Championship Qualifier - Day 2'],
      dtype=object)

In [32]:
df = pd.read_parquet("pipeline/checkpoints/stage5_matches.parquet")
df

,Playlist ID,Video ID,Title,Video Description,Clean Title,Year,Category,Playlist Title
0,PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl,gtY3Gm81ckc,YCS Bochum 2018: Round 1 Feature Match,"Footage recorded from Yu-Gi-Oh! YCS Bochum, held on February 24/25, 2018.\nRound 1: Jörg Müller vs. Eugen Heidt\n \n Yu-Gi-Oh! TRADING CARD GAME\n © 1996 Kazuki Takahashi\n © 2014 NAS • TV TOKYO\n \n Web: www.yugioh-card.com\n \n Facebook: http://facebook.com/YuGiOhTCGEU\n Twitch: http://twitch.tv/OfficialYuGiOhChannel\n \n Live Event Coverage: www.yugioh-card.com/uk/live/\n Event Blog: http://coverage.yugioh-card.com -- Watch live at https://www.twitch.tv/officialyugiohc... -- Watch live at https://www.twitch.tv/officialyugiohc... -- Watch live at https://www.twitch.tv/officialyugiohchannel",YCS Bochum,2018,YCS,YCS Bochum 2018 | Yu-Gi-Oh! Championship Series Bochum 2018
1,PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl,Lpam8Aii1vM,YCS Bochum 2018: Round 2 Feature Match,"Footage recorded from Yu-Gi-Oh! YCS Bochum, held on February 24/25, 2018.\nRound 2: Phillip Weldinger vs. Meicel Neugebauer\n \n Yu-Gi-Oh! TRADING CARD GAME\n © 1996 Kazuki Takahashi\n © 2014 NAS • TV TOKYO\n \n Web: www.yugioh-card.com\n \n Facebook: http://facebook.com/YuGiOhTCGEU\n Twitch: http://twitch.tv/OfficialYuGiOhChannel\n \n Live Event Coverage: www.yugioh-card.com/uk/live/\n Event Blog: http://coverage.yugioh-card.com -- Watch live at https://www.twitch.tv/officialyugiohc... -- Watch live at https://www.twitch.tv/officialyugiohc... -- Watch live at https://www.twitch.tv/officialyugiohchannel",YCS Bochum,2018,YCS,YCS Bochum 2018 | Yu-Gi-Oh! Championship Series Bochum 2018
2,PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl,wRwnUvpcyKA,YCS Bochum 2018: Round 3 Feature Match,"Footage recorded from Yu-Gi-Oh! YCS Bochum, held on February 24/25, 2018.\nRound 3: Carmelo Buttiglieri vs. Adam Chamberlain\n \n Yu-Gi-Oh! TRADING CARD GAME\n © 1996 Kazuki Takahashi\n © 2014 NAS • TV TOKYO\n \n Web: www.yugioh-card.com\n \n Facebook: http://facebook.com/YuGiOhTCGEU\n Twitch: http://twitch.tv/OfficialYuGiOhChannel\n \n Live Event Coverage: www.yugioh-card.com/uk/live/\n Event Blog: http://coverage.yugioh-card.com -- Watch live at https://www.twitch.tv/officialyugiohc... -- Watch live at https://www.twitch.tv/officialyugiohc...\n -- Watch live at https://www.twitch.tv/officialyugiohchannel",YCS Bochum,2018,YCS,YCS Bochum 2018 | Yu-Gi-Oh! Championship Series Bochum 2018
3,PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl,tpR87uZpnfU,YCS Bochum 2018: Round 4 Feature Match,"Footage recorded from Yu-Gi-Oh! YCS Bochum, held on February 24/25, 2018.\r\nRound 4: Jordan Gallacher vs. Steffen Friedow\r\n \r\n Yu-Gi-Oh! TRADING CARD GAME\r\n © 1996 Kazuki Takahashi\r\n © 2014 NAS • TV TOKYO\r\n \r\n Web: www.yugioh-card.com\r\n \r\n Facebook: http://facebook.com/YuGiOhTCGEU\r\n Twitch: http://twitch.tv/OfficialYuGiOhChannel\r\n \r\n Live Event Coverage: www.yugioh-card.com/uk/live/\r\n Event Blog: http://coverage.yugioh-card.com -- Watch live at https://www.twitch.tv/officialyugiohc... -- Watch live at https://www.twitch.tv/officialyugiohc... -- Watch live at https://www.twitch.tv/officialyugiohchannel",YCS Bochum,2018,YCS,YCS Bochum 2018 | Yu-Gi-Oh! Championship Series Bochum 2018
4,PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl,Dwp_1bljFLo,YCS Bochum 2018: Round 5 Feature Match,"Footage recorded from Yu-Gi-Oh! YCS Bochum, held on February 24/25, 2018.\r\nRound 5: Loan Cite-Mielle vs. David Schmidt\r\n \r\n Yu-Gi-Oh! TRADING CARD GAME\r\n © 1996 Kazuki Takahashi\r\n © 2014 NAS • TV TOKYO\r\n \r\n Web: www.yugioh-card.com\r\n \r\n Facebook: http://facebook.com/YuGiOhTCGEU\r\n Twitch: http://twitch.tv/OfficialYuGiOhChannel\r\n \r\n Live Event Coverage: www.yugioh-card.com/uk/live/\r\n Event Blog: http://coverage.yugioh-card.com -- Watch live at https://www.twitch.tv/officialyugiohc... -- Watch live at https://www.twitch.tv/officialyugiohc... -- Watch live at https://www.twitch.tv/officialyugiohchannel",YCS Bochum,2018,YCS,YCS Bochum 2018 | Yu-Gi-Oh! Championship Series Bochum 2018
...,...,...,...,...,...,...,...,...
1374,PLc1vyOIGc2qVX6ZJxab88NnmgUIZLDiLe,ZrD5_lg5ioc,"2024 North America WQP: Austin, TX // Top 16 - George S. vs. Pakawat P.",WQP Austin Top 16 Match Replay between George S. and Pakawat P.,WQP Austin,2024,WQP,Dueling Archives: 2024 WQP Austin
1375,PLc1vyOIGc2qVX6ZJxab88NnmgUIZLDiLe,ZkyHjeRmmPs,"2024 North America WQP: Austin, TX // Top 8 - Logan J. vs. Steven S.",WQP Austin Top 8 Match Replay between Logan J. and Steven S.,WQP Austin,2024,WQP,Dueling Archives: 2024 WQP Austin
1376,PLc1vyOIGc2qVX6ZJxab88NnmgUIZLDiLe,FIhfBEclMv0,"2024 North America WQP: Austin, TX // Semi Final 1 - George S. vs. Ruben P.",WQP Austin Semi Final Match Replay between George S. and Ruben P.,WQP Austin,2024,WQP,Dueling Archives: 2024 WQP Austin
1377,PLc1vyOIGc2qVX6ZJxab88NnmgUIZLDiLe,-y24Ncvio-o,"2024 North America WQP: Austin, TX // Semi Final 2 - Logan J. vs. Jose S.",WQP Austin Semi Final Match Replay between Logan J. and Jose S.,WQP Austin,2024,WQP,Dueling Archives: 2024 WQP Austin
1378,PLc1vyOIGc2qUM7r-X3Abizu4s8qnfQwzG,YrWkAofAm_E,"2024 North America Dragon Duel: Austin, TX// Final - Diego M. vs. Nabila A.",Dragon Duel Final Match replay from 2024 WCQ Austin between Diego M. and Nabila A.,NA World Championship Austin Dragon Duel Finals,2024,Dragon Duel,Dueling Archives: 2024 WCQ Austin Dragon Duel Finals

In [158]:
df = pd.read_parquet("pipeline/checkpoints/livestreams.parquet")
df

,Playlist ID,Video ID,Title,Video Description,Clean Title,Year,Category,Playlist Title
0,PLIm0Rt8gzRbvYYuWPcfcb1ZNQLCoPT5vm,MqK7qRQbbj4,WCQ Berlin: Impressions Day 2,Yu-Gi-Oh! TRADING CARD GAME\r\n © 1996 Kazuki ...,EU World Championship Qualifer,2016,World Championship,WCQ: EC2016 | 2016 WCQ: European Championship
1,PLIm0Rt8gzRbvYYuWPcfcb1ZNQLCoPT5vm,bUStmUogIY8,WCQ Berlin: Impressions Day 1,Yu-Gi-Oh! TRADING CARD GAME\r\n © 1996 Kazuki ...,EU World Championship Qualifer,2016,World Championship,WCQ: EC2016 | 2016 WCQ: European Championship
2,PLIm0Rt8gzRbuI3ij0C4yrfAQb8tMbtCt8,HmtSUuOGztM,Livestream | Yu-Gi-Oh! Championship Series Bol...,Watch the day 2 livestream of Yu-Gi-Oh! Champi...,YCS Bologna,2025,YCS,YCS Bologna 2025
3,PLIm0Rt8gzRbuI3ij0C4yrfAQb8tMbtCt8,pIvUeWm9lWU,Livestream | Yu-Gi-Oh! Championship Series Bol...,Watch the day 1 livestream of Yu-Gi-Oh! Champi...,YCS Bologna,2025,YCS,YCS Bologna 2025
4,PLIm0Rt8gzRbvUqBmSmnIEr9nTIFuqAW_F,CtMLNdRJ3u4,Livestream | Yu-Gi-Oh! World Championship Mast...,"©2020 Studio Dice／SHUEISHA, TV TOKYO, KONAMI\n...",World Championship Paris France,2025,World Championship,"Yu-Gi-Oh! World Championship 2025 - Paris, France"
...,...,...,...,...,...,...,...,...
58,PLc1vyOIGc2qVA85mAij71b89eAbdruY1u,IA6scolIkt0,Yu-Gi-Oh! TCG - YCS San Diego 2017 Day 2,,YCS San Diego,2017,YCS,"YCS San Diego (Nov 18-19, 2017)"
59,PLc1vyOIGc2qXdSd5bAVaFUp3BTGDZPwgd,JjLkFrsrVy0,[Day 2] Team Yu-Gi-Oh! Championship Series - L...,Welcome to the Team Yu-Gi-Oh! Championship Ser...,YCS Las Vegas,2020,YCS,Team YCS Las Vegas 2020
60,PLc1vyOIGc2qXdSd5bAVaFUp3BTGDZPwgd,jzDasFfd9BU,[Day 1] Team Yu-Gi-Oh! Championship Series - L...,Welcome to the Team Yu-Gi-Oh! Championship Ser...,YCS Las Vegas,2020,YCS,Team YCS Las Vegas 2020
61,PLc1vyOIGc2qUpHELcFLe4ZE-JVw2enn54,CC4DnsceYTc,[Day 2] Yu-Gi-Oh! Championship Series - Pasade...,Welcome to the Yu-Gi-Oh! Championship Series i...,YCS,Unknown,YCS,Yu-Gi-Oh! Championship Series
62,PLc1vyOIGc2qUpHELcFLe4ZE-JVw2enn54,3PS-97G3lBM,[Day 1] Yu-Gi-Oh! Championship Series - Pasade...,Welcome to the Yu-Gi-Oh! Championship Series i...,YCS,Unknown,YCS,Yu-Gi-Oh! Championship Series

In [177]:
df = pd.read_parquet("pipeline/checkpoints/stage5_matches.parquet")  # adjust to your actual stage5 output filename
llm_input = df[["Video ID", "Title", "Video Description"]].copy()
llm_input["Video Description"] = llm_input["Video Description"].str[:200]  # trim long descriptions

In [183]:
from groq import Groq
import os
import json
import pandas as pd
from dotenv import load_dotenv
load_dotenv()

client = Groq(api_key=os.getenv("GROQ_API_KEY"))

sample = llm_input.sample(n=20, random_state=56)
sample_records = sample[["Video ID", "Title", "Video Description"]].to_dict("records")

prompt = """
You are a Yu-Gi-Oh! feature match classification system.

You will receive a JSON array of videos. For EVERY video in the input, return EXACTLY ONE object in the output array.

A feature match is a real recorded duel between two identifiable players.
Livestreams, vlogs, deck profiles, promos, interviews, and commentary-only videos are NOT feature matches.

IMPORTANT: Titles containing round/bracket stage indicators (e.g. "Round X", "Top X", "Quarterfinal", 
"Semi-Final", "Final") almost always indicate a feature match, even if player names are not present 
in the title or description. Player names being unavailable does NOT mean it's not a match — 
set player_1/player_2/deck_1/deck_2 to null in that case, but still mark is_match as true.

Return ONLY a valid JSON array, one object per input video, in the same order, using this schema:

{
  "video_id": string,
  "is_match": true or false,
  "tournament": string or null,
  "round": string or null,
  "player_1": string or null,
  "deck_1": string or null,
  "player_2": string or null,
  "deck_2": string or null
}

RULES:
- ALWAYS include "video_id" exactly as given in the input.
- If is_match is false, set all other fields to null.
- Round must be formatted exactly like: "Round 1", "Top 32", "Finals", "Semi-Final", "Quarterfinal"
- Tournament should be the event name (e.g. "YCS London 2024")
- Do NOT guess missing players or decks — use null if unknown

INPUT:
""" + json.dumps(sample_records)

response = client.chat.completions.create(
    model="llama-3.1-8b-instant",
    messages=[{"role": "user", "content": prompt}],
    temperature=0,
    max_tokens=8192
)

content = response.choices[0].message.content.strip()

# strip markdown code fences if present
if content.startswith("```"):
    content = content.split("```")[1]
    if content.startswith("json"):
        content = content[4:]
    content = content.strip()

parsed = json.loads(content)
results_df = pd.DataFrame(parsed)
results_df

,video_id,is_match,tournament,round,player_1,deck_1,player_2,deck_2
0,QZ6RLokEP2c,True,WCQ 2017 Utrecht,None,Noah Riffel,Zoodiac,Reuben Baron,Zoodiac
1,ISsuUwHMeK4,True,YCS Utrecht 2022,Round 4,Niklas A.,Runick Spright,Sebastian F.,P.U.N.K
2,843BaEKEcwk,True,EU WQP Playoff Berlin 2025,Round 1,Ben K.,Vanquish Soul,Danilo S.,Mementotlan
3,KywLxddxPEk,True,YCS Dortmund 2022,TOP 8,Mario A.,Floowandereeze,Eteeyen I.,Ishizu Tearlaments
4,Sr5-PQxpT5c,True,YCS Bologna 2024,Round 11,Dinh-Kha B.,Fiendsmith Kashtira,Vincenzo C.,Bystial Centur-Ion
5,QFmOS8P6XEo,False,None,None,None,None,None,None
6,-ZvcNaV70pM,True,YCS 2017 Prague,Round 1,Christian Habicht,Zoodiac,Danny Goldmann,Paleozoic
7,fHfd7DRvEdc,True,YCS 2017 Prague,Top 4,Joshua Schmidt,60 Cards Paleozoic,Jawed Sayeed Chowdhury,60 Cards Infernoid Zoodiac
8,VolgsU2bLZ4,True,Italian OPEN May 2024,Round 3,Zuccatelli J.,Branded Despia,Cefola A.,Floowandereeze
9,p2CWlEL-k1E,True,YCS London 2017,Round 7,Mirko Zanelli,None,John Lascelles,None
10,iJSPfEkubQc,True,Ultimate Time Wizard 2010 YCS Birmingham 2025,Round 8,Frogs,None,Blackwing,None
11,5UxWdxmr95U,True,2018 WCQ: European Championship - Berlin,Top 16,Simon Franke,Gouki,Jake Quinse,Gouki
12,6pxaxWCxyqg,True,"2025 North America YCS Houston, TX",Top 16,Aditya D.,None,Bryce S.,None
13,8DQggTHhukI,True,2024 World Championship Series - Duel Links Ru...,Final,Voltalon,None,QunatumCubes,None
14,lFyEaeG2FcY,True,YCS Bochum 2018,Round 7,Stefan Frankowski,None,Dinh Khang Pham,None
15,Ldklbb5NgBw,True,2017 World Championship,Semi Final,Marcello Barberi,None,Shen-Fei Milton Chua,None
16,AHbxLTJiF_o,True,Italian OPEN May 2024,Round 8,Pastore M.,Melodious,Kelly C.,Snake-Eye
17,MH_esuOgueI,True,"2025 North America YCS Houston, TX",Semi Final 2,Pascal M.,None,Kevin Z.,None
18,-cGqaoYXRfU,True,Yu-Gi-Oh! TCG Italian OPEN January 2025,Round 2,Nusca A.,Melodious,Barsacchi D.,Eldlich
19,9DMxJgAPFIY,False,None,None,None,None,None,None

In [229]:
prompt_template = """
You are a Yu-Gi-Oh! feature match classification system.

You will receive a JSON array of videos. For EVERY video in the input, return EXACTLY ONE object in the output array.

A feature match is a real recorded duel between two identifiable players.
Livestreams, vlogs, deck profiles, promos, interviews, and commentary-only videos are NOT feature matches.

IMPORTANT: Titles containing round/bracket stage indicators (e.g. "Round X", "Top X", "Quarterfinal", 
"Semi-Final", "Final") almost always indicate a feature match, even if player names are not present 
in the title or description. Player names being unavailable does NOT mean it's not a match — 
set player_1/player_2/deck_1/deck_2 to null in that case, but still mark is_match as true.

Return ONLY a valid JSON array, one object per input video, in the same order, using this schema:

{
  "video_id": string,
  "is_match": true or false,
  "tournament": string or null,
  "round": string or null,
  "player_1": string or null,
  "deck_1": string or null,
  "player_2": string or null,
  "deck_2": string or null
}


RULES:
- ALWAYS include "video_id" exactly as given in the input.
- If is_match is false, set all other fields to null.
- Round must be formatted exactly like: "Round 1", "Top 32", "Finals", "Semi-Final", "Quarterfinal"
- Tournament should be the event name (e.g. "YCS London 2024")
- Do NOT guess missing players or decks — use null if unknown
- DO NOT write Python or JavaScript.
- DO NOT explain.
- DO NOT wrap in ```json.
- DO NOT write any text before or after the JSON.
- The first character of your response MUST be [
- The last character of your response MUST be ]

INPUT:
"""

def safe_parse_json(content: str):
    if content.startswith("```"):
        content = content.split("```")[1]
        if content.startswith("json"):
            content = content[4:]
        content = content.strip()

    try:
        return json.loads(content)
    except json.JSONDecodeError as e:
        print(f"JSON parse failed: {e}")
        print(f"Raw content (last 300 chars): {content[-300:]}")
        return None

In [233]:
import time

all_results = []
chunk_size = 10
rows = llm_input.to_dict("records")
total_chunks = -(-len(rows) // chunk_size)

for i in range(0, len(rows), chunk_size):
    chunk_id = i // chunk_size + 1
    chunk = rows[i:i + chunk_size]

    print(f"Processing chunk {chunk_id}/{total_chunks}")

    chunk_prompt = prompt_template + json.dumps(chunk, ensure_ascii=False)

    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[{"role": "user", "content": chunk_prompt}],
        temperature=0,
        max_tokens=1000,
        response_format={"type": "json_object"}
    )

    content = response.choices[0].message.content.strip()
    parsed = safe_parse_json(content)

    if parsed is not None:
        all_results.extend(parsed)
        print(f"  ✓ {len(parsed)} rows returned")
    else:
        print(f"  ✗ chunk {chunk_id} failed — skipping")

    if i + chunk_size < len(rows):  # don't sleep after the last chunk
        time.sleep(30)
        # break

results_df = pd.DataFrame(all_results)
print(f"\nTotal rows processed: {len(results_df)} / {len(rows)}")

Processing chunk 1/138
  ✓ 10 rows returned
Processing chunk 2/138
  ✓ 10 rows returned
Processing chunk 3/138
  ✓ 10 rows returned
Processing chunk 4/138
  ✓ 10 rows returned
Processing chunk 5/138
  ✓ 10 rows returned
Processing chunk 6/138
  ✓ 10 rows returned
Processing chunk 7/138
  ✓ 10 rows returned
Processing chunk 8/138
  ✓ 10 rows returned
Processing chunk 9/138
  ✓ 10 rows returned
Processing chunk 10/138
  ✓ 10 rows returned
Processing chunk 11/138
  ✓ 10 rows returned
Processing chunk 12/138
  ✓ 10 rows returned
Processing chunk 13/138
  ✓ 10 rows returned
Processing chunk 14/138
  ✓ 10 rows returned
Processing chunk 15/138
  ✓ 10 rows returned
Processing chunk 16/138
  ✓ 10 rows returned
Processing chunk 17/138
  ✓ 10 rows returned
Processing chunk 18/138
  ✓ 10 rows returned
Processing chunk 19/138
  ✓ 10 rows returned
Processing chunk 20/138
  ✓ 10 rows returned
Processing chunk 21/138
  ✓ 10 rows returned
Processing chunk 22/138
  ✓ 10 rows returned
Processing chunk 23/138
  ✓ 10 rows returned
Processing chunk 24/138
  ✓ 10 rows returned
Processing chunk 25/138
  ✓ 10 rows returned
Processing chunk 26/138
  ✓ 10 rows returned
Processing chunk 27/138
  ✓ 10 rows returned
Processing chunk 28/138
  ✓ 10 rows returned
Processing chunk 29/138
  ✓ 10 rows returned
Processing chunk 30/138
  ✓ 10 rows returned
Processing chunk 31/138
  ✓ 10 rows returned
Processing chunk 32/138

RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kw2wctxxekn9jf2z6prmcb89` service tier `on_demand` on tokens per day (TPD): Limit 100000, Used 98180, Requested 2388. Please try again in 8m10.752s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

In [31]:
import pandas as pd
df = pd.read_parquet("pipeline/checkpoints/stage6_matches.parquet")  # adjust to your actual stage5 output filename
df

,video_id,is_match,tournament,round,player_1,deck_1,player_2,deck_2,Playlist ID,Playlist Title,Clean Title,Category,Year
0,gtY3Gm81ckc,True,YCS Bochum 2018,Round 1,Jörg Müller,None,Eugen Heidt,None,PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl,YCS Bochum 2018 | Yu-Gi-Oh! Championship Series Bochum 2018,YCS Bochum,YCS,2018
1,Lpam8Aii1vM,True,YCS Bochum 2018,Round 2,Phillip Weldinger,None,Meicel Neugebauer,None,PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl,YCS Bochum 2018 | Yu-Gi-Oh! Championship Series Bochum 2018,YCS Bochum,YCS,2018
2,wRwnUvpcyKA,True,YCS Bochum 2018,Round 3,Carmelo Buttiglieri,None,Adam Chamberlain,None,PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl,YCS Bochum 2018 | Yu-Gi-Oh! Championship Series Bochum 2018,YCS Bochum,YCS,2018
3,tpR87uZpnfU,True,YCS Bochum 2018,Round 4,Jordan Gallacher,None,Steffen Friedow,None,PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl,YCS Bochum 2018 | Yu-Gi-Oh! Championship Series Bochum 2018,YCS Bochum,YCS,2018
4,Dwp_1bljFLo,True,YCS Bochum 2018,Round 5,Loan Cite-Mielle,None,David Schmidt,None,PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl,YCS Bochum 2018 | Yu-Gi-Oh! Championship Series Bochum 2018,YCS Bochum,YCS,2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1382,-vsulzcQkF4,True,2017 World Championship TCG (All-Ages),3rd Place Match,Marcello Barberi,None,Michael Forner,None,PLc1vyOIGc2qVsXghcP-IRPwbIg9yiDTrc,Yu-Gi-Oh! 2017 World Championship,World Championship,World Championship,2017
1383,MXa5NlC_634,True,2017 World Championship TCG (All-Ages),Final,Ryosuke Tsujimura,None,Shen-Fei Milton Shua,None,PLc1vyOIGc2qVsXghcP-IRPwbIg9yiDTrc,Yu-Gi-Oh! 2017 World Championship,World Championship,World Championship,2017
1384,MjBeOAdEWdM,False,None,None,None,None,None,None,PLc1vyOIGc2qUwKZvwkAIZrfMup6QHDs-1,Remote Duel Invitational - TCG (8/22 - 8/23/2020),Remote Duel Invitational,Remote Duel Invitational,2020
1385,RJDej8ylczo,False,None,None,None,None,None,None,PLc1vyOIGc2qUwKZvwkAIZrfMup6QHDs-1,Remote Duel Invitational - TCG (8/22 - 8/23/2020),Remote Duel Invitational,Remote Duel Invitational,2020
1386,htTBIelTUB8,True,None,Round 3,Cameron Neal,None,Sam Arunnaveesiri,None,PLc1vyOIGc2qUwKZvwkAIZrfMup6QHDs-1,Remote Duel Invitational - TCG (8/22 - 8/23/2020),Remote Duel Invitational,Remote Duel Invitational,2020

In [198]:
import pandas as pd
df = pd.read_parquet("pipeline/checkpoints/llm_progress.parquet")  # adjust to your actual stage5 output filename
df

,video_id,is_match,tournament,round,player_1,deck_1,player_2,deck_2
0,gtY3Gm81ckc,True,YCS Bochum 2018,Round 1,Jörg Müller,None,Eugen Heidt,None
1,Lpam8Aii1vM,True,YCS Bochum 2018,Round 2,Phillip Weldinger,None,Meicel Neugebauer,None
2,wRwnUvpcyKA,True,YCS Bochum 2018,Round 3,Carmelo Buttiglieri,None,Adam Chamberlain,None
3,tpR87uZpnfU,True,YCS Bochum 2018,Round 4,Jordan Gallacher,None,Steffen Friedow,None
4,Dwp_1bljFLo,True,YCS Bochum 2018,Round 5,Loan Cite-Mielle,None,David Schmidt,None
...,...,...,...,...,...,...,...,...
1332,vZytF7DUIMM,True,2018 WCQ: UK Open II London,Round 9,Alex Moffatt,Pendulum Magician,Abdul Ismael,SPYRAL
1333,nk1c0Wjyvn0,True,2018 WCQ: UK Open II London,Round 8,Kristoffer Nielsen,SPYRAL,Vj Sadiua,60 Card Lightsworn
1334,nk1c0Wjyvn0,True,2018 WCQ: UK Open II London,Round 9,Alex Moffatt,Pendulum Magician,Abdul Ismael,SPYRAL
1335,UqK_XD-73iY,True,2018 WCQ: UK Open II London,Round 9,Alex Moffatt,Pendulum Magician,Abdul Ismael,SPYRAL
1336,PLcKlnBOAs0,True,TCG Final – Yu-Gi-Oh! World Championship 2019 ...,Final,Chia Ching Wang,None,Kouki Kosaka,None

In [30]:
df[df["is_match"] == False]

         video_id  is_match tournament round player_1 deck_1 player_2 deck_2
17    tj25H8Sy5ok     False       None  None     None   None     None   None
18    g6hQxO8q6V0     False       None  None     None   None     None   None
19    pNFSiXYdXzQ     False       None  None     None   None     None   None
36    UW-WXN2Ly6w     False       None  None     None   None     None   None
45    c74KX8N5s1Y     False       None  None     None   None     None   None
...           ...       ...        ...   ...      ...    ...      ...    ...
1032  Hvs3AmcZ8-4     False       None  None     None   None     None   None
1112  k78lSiU7GSY     False       None  None     None   None     None   None
1232  iAXWdhX6520     False       None  None     None   None     None   None
1360  MjBeOAdEWdM     False       None  None     None   None     None   None
1361  RJDej8ylczo     False       None  None     None   None     None   None

[77 rows x 8 columns]

In [218]:
results_df = pd.read_parquet("pipeline/checkpoints/stage6_matches.parquet")
df = pd.read_parquet("pipeline/checkpoints/stage5_matches.parquet")

df
false_matches = results_df[results_df['is_match'] == False]

merged_false = false_matches.merge(
    df, 
    left_on='Video ID', 
    right_on='Video ID', 
    how='left'
)

# df.columns
merged_false['Title'].unique()

array(['YCS Bochum 2018: Pendulum Magician vs Trickstar - Jesse Kotton',
       'YCS Bochum 2018: Pendulum Magician vs Trickstar - Lorenzo Roma',
       'YCS Bochum 2018: Pendulum Magician vs Trickstar - Joshua Schmidt',
       'YCS Bochum 2018: Trickstar vs Lightsworn Zombie - Jesse Kotton',
       'YCS Bochum 2018: Trickstar vs Lightsworn Zombie - Lorenzo Roma',
       'YCS Bochum 2018: Trickstar vs Lightsworn Zombie - Joshua Schmidt',
       'YCS Bochum 2018: Trickstar vs True Draco - Jesse Kotton',
       'YCS Bochum 2018: Trickstar vs True Draco - Lorenzo Roma',
       'YCS Bochum 2018: Trickstar vs True Draco - Joshua Schmidt',
       'WCQ: EC2015: Dragon Duel - Final Highlights',
       'WCQ: EC2015: Round 9 Feature Match Highlights',
       'WCQ: EC2015: Round 8 Feature Match Highlights',
       'WCQ: EC2015: Round 7 Feature Match Highlights',
       'WCQ: EC2015: Round 4 Feature Match Highlights',
       'WCQ: EC2015: Round 3 Feature Match Highlights',
       'WCQ: EC2015: Round 2 Feature Match Highlights',
       'WCQ: EC2015: Round 1 Feature Match Highlights',
       'WCQ 2016 Berlin: Top 4 Feature Match Highlights',
       'WCQ 2016 Berlin: Top 8 Feature Match Highlights',
       'WCQ 2016 Berlin: Top 16 Feature Match Highlights',
       'WCQ 2016 Berlin: Round 7 Feature Match Highlights',
       'WCQ 2016 Berlin: Round 6 Feature Match Highlights',
       'YCS Milan 2018: Round 10 - Hot Takes - Part 1',
       'YCS Milan 2018: Round 10 - Hot Takes - Part 2',
       'YCS Milan 2018: Round 10 - Hot Takes - Part 4',
       'YCS Milan 2018: Round 10 - Hot Takes - Part 3',
       'YCS Milan 2018: Round 7 - Hot Takes - Part 1',
       'Master vs. Caster |\xa0YCS Bologna 2025',
       'Yu-Gi-Oh! World Championship 2025 - TCG Finals Opening Ceremony - Salif Gueye (Crookboyz) & His Crew',
       'Yu-Gi-Oh! WCS 2025 | Billy Brake & Marcello Barberi discuss player vs commentator WCS experience',
       'Genesys Showcase - Barcode (Eldlich) vs Alberto Marazzi (Spright) | YCS Lille 2025',
       'Genesys Showcase - Sebastian Lemke (Apophis) vs Joshua Schmidt (Dragon Ruler) | YCS Lille 2025',
       'Genesys Showcase - Marcello B. (Vanquish Soul K9) vs Mike P. (Lunalight Zoodiac) | YCS Lille 2025',
       'YCS 2017 Prague: Round 1', 'YCS 2017 Prague: Round 2',
       'EU WCQ Berlin 2025 - Round 6 - Giuseppe P.',
       'YCS London: Round 3 Feature Match',
       'YCS London: Round 4 Feature Match',
       'YCS London: Top 8 Feature Match',
       '2018 Yu-Gi-Oh! TCG World Championship - Walter Jule vs Seung-Chul Jung',
       '2018 Yu-Gi-Oh! TCG Dragon Duel World Championship - Koizumi Yuto vs James English',
       '2018 Yu-Gi-Oh! TCG Dragon Duel World Championship - Charley Futch III vs Wu Hung-Wei',
       '2018 Yu-Gi-Oh! TCG World Championship - Akira Hasegawa vs Gabriel Vargas',
       '2018 Yu-Gi-Oh! TCG World Championship - Ryosuke Tsujimura vs Poe Jiang',
       '2016 WCQ: UK National | Final', '2016 WCQ: UK National | Top 4',
       '2016 WCQ: UK National | Top 64',
       'YCS London 2019 - Top 16 - David Erpen vs. Christoph Kofoet',
       'YCS London 2019 - Top 32 - Christian Thomas vs. Enzo Duval',
       'YCS London 2019 - Round 10 - Doganay Cekic vs. Tom Kleingräber',
       'YCS London 2019 - Round 8 - Vladis Baranovskis vs. Themis Gzykis',
       'YCS Dortmund 2022 - Round 8 - Federico M. vs. Kristoffer N.',
       'YCS Dortmund 2022 - Round 7 - Matthew C. vs. Batuhan S.',
       'YCS Sydney 2017: Round 6', 'YCS Madrid: Round 4 Feature Match',
       '2016 WCQ: German National Championship - Top 64',
       '2014 World Championship: 3rd / 4th Place',
       '2014 World Championship Dragon Duel: 3rd / 4th Place Match',
       'Round 1 - Plants vs Frog HERO - Ultimate Time Wizard 2010 YCS Bologna 2024',
       'Round 2 - Lightsworn vs Chaos Fairy - Ultimate Time Wizard 2010 YCS Bologna 2024',
       'Round 3 - Machina Gadget vs Blackwing - Ultimate Time Wizard 2010 YCS Bologna 2024',
       'Round 4 - Machina Synchro vs Flamvell Frog - Ultimate Time Wizard 2010 YCS Bologna 2024',
       'Yu-Gi-Oh! Card EU | Greek OPEN Round 2 - Xanidis A. vs Rafailidis D.',
       'Yu-Gi-Oh! Card EU | Greek OPEN Round 3 - Gkamaris G. vs Pete A.',
       'Yu-Gi-Oh! Card EU | Greek OPEN Round 4 - Paraskevas D. vs Konstantinidis Y.',
       'Yu-Gi-Oh! Card EU | Greek OPEN Round 5 - Koutentakis I. vs Mourikis X.',
       'Yu-Gi-Oh! Card EU | Greek OPEN Round 6 - Kouzoupis N. vs Stergiopoulou Z.',
       'Yu-Gi-Oh! Card EU | Greek OPEN Round 1 - Gkyzis T. vs Tsimploulis B.',
       'YuGiOh REAL LIFE DUEL | YUGI vs KAIBA!!',
       'WCS 2019 - 1st Place YugiTuber Influencer Tournament Official Champion',
       '2025 North America YCS Houston, TX// Round 1 - Mitchell M. vs. Tyler I.',
       '2025 North America YCS Houston, TX// Round 3 - Hector L. vs. Ethan V.',
       '2025 North America YCS Orlando, FL// Round 1 - Kamal C. vs. Emilio F.',
       '2025 North America YCS Providence, RI // Round 1 - Nicholas K. vs. Steven C.',
       '2025 North America YCS Providence, RI // Round 2 - Kody F. vs Yacine S.',
       '2025 North America YCS Providence, RI // Round 3 - Adam K. vs. Jason Y.',
       '2024 North America YCS: Raleigh, NC // Top 16 - Jeffrey J. vs Evan P.',
       '2024 North America YCS: Raleigh, NC // Top 32 - Aaron F. vs Clifton L.',
       '2024 North America YCS: Indianapolis, IN// Round 1 - Raymond D. vs. Samuel B.',
       '2024 North America YCS: Indianapolis  // Round 3 - Johnny N. vs. Michael D.',
       '2024 North America YCS: Indianapolis, IN// Round 4 - Brian B. vs. Garret M.',
       '2024 North America YCS: Indianapolis, IN// Round 11 - Casey H. vs. Kailyn C.',
       '2017 World Championship TCG (Dragon Duel) Round 3: Charley Futch III vs Felix Rau',
       '2017 World Championship TCG (Dragon Duel) Quarter Final: Ryan Yu vs Connor Dwyer',
       '2017 World Championship TCG (Dragon Duel) Final: Rafael Mariano Reich vs Ryan Yu'],
      dtype=object)

In [175]:
matches[matches['Title'].str.contains('Games')]

,Playlist ID,Video ID,Title,Video Description,Clean Title,Year,Category,Playlist Title
129,PLIm0Rt8gzRbvNmWVsRbgwdxXWcX1EXxh0,_Cc9oKSloFA,YCS Milan 2018: Round 10 - Yu-Gi-Oh! Games - P...,Yu-Gi-Oh! TRADING CARD GAME\n© 1996 Kazuki Tak...,YCS Milan,2018,YCS,YCS Milan 2018 | Yu-Gi-Oh! Championship Series...
130,PLIm0Rt8gzRbvNmWVsRbgwdxXWcX1EXxh0,XU3GAVHWSis,YCS Milan 2018: Round 10 - Yu-Gi-Oh! Games - P...,Yu-Gi-Oh! TRADING CARD GAME\n© 1996 Kazuki Tak...,YCS Milan,2018,YCS,YCS Milan 2018 | Yu-Gi-Oh! Championship Series...
131,PLIm0Rt8gzRbvNmWVsRbgwdxXWcX1EXxh0,SC63tjnlUFk,YCS Milan 2018: Round 10 - Yu-Gi-Oh! Games - P...,Yu-Gi-Oh! TRADING CARD GAME\n© 1996 Kazuki Tak...,YCS Milan,2018,YCS,YCS Milan 2018 | Yu-Gi-Oh! Championship Series...
132,PLIm0Rt8gzRbvNmWVsRbgwdxXWcX1EXxh0,Gd5rp3D8awA,YCS Milan 2018: Round 10 - Yu-Gi-Oh! Games - P...,Yu-Gi-Oh! TRADING CARD GAME\n© 1996 Kazuki Tak...,YCS Milan,2018,YCS,YCS Milan 2018 | Yu-Gi-Oh! Championship Series...
133,PLIm0Rt8gzRbvNmWVsRbgwdxXWcX1EXxh0,bJYm8HJ5fEg,YCS Milan 2018: Round 10 - Yu-Gi-Oh! Games - P...,Yu-Gi-Oh! TRADING CARD GAME\n© 1996 Kazuki Tak...,YCS Milan,2018,YCS,YCS Milan 2018 | Yu-Gi-Oh! Championship Series...
134,PLIm0Rt8gzRbvNmWVsRbgwdxXWcX1EXxh0,h2PWOMZgmnc,YCS Milan 2018: Round 10 - Yu-Gi-Oh! Games - P...,Yu-Gi-Oh! TRADING CARD GAME\n© 1996 Kazuki Tak...,YCS Milan,2018,YCS,YCS Milan 2018 | Yu-Gi-Oh! Championship Series...
135,PLIm0Rt8gzRbvNmWVsRbgwdxXWcX1EXxh0,Yfvy1X6QWrY,YCS Milan 2018: Round 10 - Yu-Gi-Oh! Games - P...,Yu-Gi-Oh! TRADING CARD GAME\n© 1996 Kazuki Tak...,YCS Milan,2018,YCS,YCS Milan 2018 | Yu-Gi-Oh! Championship Series...
136,PLIm0Rt8gzRbvNmWVsRbgwdxXWcX1EXxh0,0MG3kgcFO-8,YCS Milan 2018: Round 10 - Yu-Gi-Oh! Games - P...,Yu-Gi-Oh! TRADING CARD GAME\n© 1996 Kazuki Tak...,YCS Milan,2018,YCS,YCS Milan 2018 | Yu-Gi-Oh! Championship Series...
137,PLIm0Rt8gzRbvNmWVsRbgwdxXWcX1EXxh0,Pp-rWVY6xnw,YCS Milan 2018: Round 10 - Yu-Gi-Oh! Games - P...,Yu-Gi-Oh! TRADING CARD GAME\n© 1996 Kazuki Tak...,YCS Milan,2018,YCS,YCS Milan 2018 | Yu-Gi-Oh! Championship Series...

In [80]:
stage6 = pd.read_parquet("pipeline/checkpoints/stage6_matches.parquet")
stage5 = pd.read_parquet("pipeline/checkpoints/stage5_matches.parquet")

stage5_clean = stage5.drop_duplicates(subset=["Video ID"])
stage6_clean = stage6.drop_duplicates(subset=["video_id"])
print(len(stage6_clean))
df = stage6_clean.merge(
    stage5_clean,
    left_on="video_id",
    right_on="Video ID",
    how="left")

df

1358

,video_id,is_match,tournament,round,player_1,deck_1,player_2,deck_2,Playlist ID_x,Playlist Title_x,...,Category_x,Year_x,Playlist ID_y,Video ID,Title,Video Description,Clean Title_y,Year_y,Category_y,Playlist Title_y
0,gtY3Gm81ckc,True,YCS Bochum 2018,Round 1,Jörg Müller,None,Eugen Heidt,None,PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl,YCS Bochum 2018 | Yu-Gi-Oh! Championship Series Bochum 2018,...,YCS,2018,PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl,gtY3Gm81ckc,YCS Bochum 2018: Round 1 Feature Match,"Footage recorded from Yu-Gi-Oh! YCS Bochum, held on February 24/25, 2018.\nRound 1: Jörg Müller vs. Eugen Heidt\n \n Yu-Gi-Oh! TRADING CARD GAME\n © 1996 Kazuki Takahashi\n © 2014 NAS • TV TOKYO\n \n Web: www.yugioh-card.com\n \n Facebook: http://facebook.com/YuGiOhTCGEU\n Twitch: http://twitch.tv/OfficialYuGiOhChannel\n \n Live Event Coverage: www.yugioh-card.com/uk/live/\n Event Blog: http://coverage.yugioh-card.com -- Watch live at https://www.twitch.tv/officialyugiohc... -- Watch live at https://www.twitch.tv/officialyugiohc... -- Watch live at https://www.twitch.tv/officialyugiohchannel",YCS Bochum,2018,YCS,YCS Bochum 2018 | Yu-Gi-Oh! Championship Series Bochum 2018
1,Lpam8Aii1vM,True,YCS Bochum 2018,Round 2,Phillip Weldinger,None,Meicel Neugebauer,None,PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl,YCS Bochum 2018 | Yu-Gi-Oh! Championship Series Bochum 2018,...,YCS,2018,PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl,Lpam8Aii1vM,YCS Bochum 2018: Round 2 Feature Match,"Footage recorded from Yu-Gi-Oh! YCS Bochum, held on February 24/25, 2018.\nRound 2: Phillip Weldinger vs. Meicel Neugebauer\n \n Yu-Gi-Oh! TRADING CARD GAME\n © 1996 Kazuki Takahashi\n © 2014 NAS • TV TOKYO\n \n Web: www.yugioh-card.com\n \n Facebook: http://facebook.com/YuGiOhTCGEU\n Twitch: http://twitch.tv/OfficialYuGiOhChannel\n \n Live Event Coverage: www.yugioh-card.com/uk/live/\n Event Blog: http://coverage.yugioh-card.com -- Watch live at https://www.twitch.tv/officialyugiohc... -- Watch live at https://www.twitch.tv/officialyugiohc... -- Watch live at https://www.twitch.tv/officialyugiohchannel",YCS Bochum,2018,YCS,YCS Bochum 2018 | Yu-Gi-Oh! Championship Series Bochum 2018
2,wRwnUvpcyKA,True,YCS Bochum 2018,Round 3,Carmelo Buttiglieri,None,Adam Chamberlain,None,PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl,YCS Bochum 2018 | Yu-Gi-Oh! Championship Series Bochum 2018,...,YCS,2018,PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl,wRwnUvpcyKA,YCS Bochum 2018: Round 3 Feature Match,"Footage recorded from Yu-Gi-Oh! YCS Bochum, held on February 24/25, 2018.\nRound 3: Carmelo Buttiglieri vs. Adam Chamberlain\n \n Yu-Gi-Oh! TRADING CARD GAME\n © 1996 Kazuki Takahashi\n © 2014 NAS • TV TOKYO\n \n Web: www.yugioh-card.com\n \n Facebook: http://facebook.com/YuGiOhTCGEU\n Twitch: http://twitch.tv/OfficialYuGiOhChannel\n \n Live Event Coverage: www.yugioh-card.com/uk/live/\n Event Blog: http://coverage.yugioh-card.com -- Watch live at https://www.twitch.tv/officialyugiohc... -- Watch live at https://www.twitch.tv/officialyugiohc...\n -- Watch live at https://www.twitch.tv/officialyugiohchannel",YCS Bochum,2018,YCS,YCS Bochum 2018 | Yu-Gi-Oh! Championship Series Bochum 2018
3,tpR87uZpnfU,True,YCS Bochum 2018,Round 4,Jordan Gallacher,None,Steffen Friedow,None,PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl,YCS Bochum 2018 | Yu-Gi-Oh! Championship Series Bochum 2018,...,YCS,2018,PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl,tpR87uZpnfU,YCS Bochum 2018: Round 4 Feature Match,"Footage recorded from Yu-Gi-Oh! YCS Bochum, held on February 24/25, 2018.\r\nRound 4: Jordan Gallacher vs. Steffen Friedow\r\n \r\n Yu-Gi-Oh! TRADING CARD GAME\r\n © 1996 Kazuki Takahashi\r\n © 2014 NAS • TV TOKYO\r\n \r\n Web: www.yugioh-card.com\r\n \r\n Facebook: http://facebook.com/YuGiOhTCGEU\r\n Twitch: http://twitch.tv/OfficialYuGiOhChannel\r\n \r\n Live Event Coverage: www.yugioh-card.com/uk/live/\r\n Event Blog: http://coverage.yugioh-card.com -- Watch live at https://www.twitch.tv/officialyugiohc... -- Watch live at https://www.twitch.tv/officialyugiohc... -- Watch live at https://www.twitch.tv/officialyugiohchannel",YCS Bochum,2018,YCS,YCS Bochum 2018 | Yu-Gi-Oh! Championship Series Bochum 2018
4,Dwp_1bljFLo,True,YCS Bochum 2018,Round 5,Loan Cite-Mielle,None,David Schmidt,None,PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl,YCS Bochum 2018 | Yu-Gi-Oh! Championship Series Bochum 2018,...,YCS,2018,PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl,Dwp_1bljFLo,YCS Bochum 2018: Round 5 Feature Match,"Footage recorded from Yu-Gi-Oh! YCS Bochum, held on February 24/25, 2018.\r\nRound 5: Loan Cite-Mielle vs. David Schmidt\r\n \r\n Yu-Gi-Oh! TRADING CARD GAME\r\n © 1996 Kazuki Takahashi\r\n © 2014 NAS • TV TOKYO\r\n \r\n Web: www.yugioh-card.com\r\n \r\n Facebook: http://facebook.com/YuGiOhTCGEU\r\n Twitch: http://twitch.tv/OfficialYuGiOhChannel\r\n \r\n Live Event Coverage: www.yugioh-card.com/uk/live/\r\n Event Blog: http://coverage.yugioh-card.com -- Watch live at https://www.twitch.tv/officialyugiohc... -- Watch live at https://www.twitch.tv/officialyugiohc... -- Watch live at https://www.twitch.tv/officialyugiohchannel",YCS Bochum,2018,YCS,YCS Bochum 2018 | Yu-Gi-Oh! Championship Series Bochum 2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1353,-vsulzcQkF4,True,2017 World Championship TCG (All-Ages),3rd Place Match,Marcello Barberi,None,Michael Forner,None,PLc1vyOIGc2qVsXghcP-IRPwbIg9yiDTrc,Yu-Gi-Oh! 2017 World Championship,...,World Championship,2017,PLc1vyOIGc2qVsXghcP-IRPwbIg9yiDTrc,-vsulzcQkF4,2017 World Championship TCG (All-Ages) 3rd Place Match: Marcello Barberi vs Michael Forner,,World Championship,2017,World Championship,Yu-Gi-Oh! 2017 World Championship
1354,MXa5NlC_634,True,2017 World Championship TCG (All-Ages),Final,Ryosuke Tsujimura,None,Shen-Fei Milton Shua,None,PLc1vyOIGc2qVsXghcP-IRPwbIg9yiDTrc,Yu-Gi-Oh! 2017 World Championship,...,World Championship,2017,PLc1vyOIGc2qVsXghcP-IRPwbIg9yiDTrc,MXa5NlC_634,2017 World Championship TCG (All-Ages) Final: Ryosuke Tsujimura vs Shen-Fei Milton Shua,,World Championship,2017,World Championship,Yu-Gi-Oh! 2017 World Championship
1355,MjBeOAdEWdM,False,None,None,None,None,None,None,PLc1vyOIGc2qUwKZvwkAIZrfMup6QHDs-1,Remote Duel Invitational - TCG (8/22 - 8/23/2020),...,Remote Duel Invitational,2020,PLc1vyOIGc2qUwKZvwkAIZrfMup6QHDs-1,MjBeOAdEWdM,Yu Gi Oh! Remote Duel Invitational - TCG: Day 1 Round 1,Gage Poljak (USA) vs Ryan Yu (Canada),Remote Duel Invitational,2020,Remote Duel Invitational,Remote Duel Invitational - TCG (8/22 - 8/23/2020)
1356,RJDej8ylczo,False,None,None,None,None,None,None,PLc1vyOIGc2qUwKZvwkAIZrfMup6QHDs-1,Remote Duel Invitational - TCG (8/22 - 8/23/2020),...,Remote Duel Invitational,2020,PLc1vyOIGc2qUwKZvwkAIZrfMup6QHDs-1,RJDej8ylczo,"Yu Gi Oh! Remote Duel Invitational - TCG: Day 1, Round 2",Blair Hunter (USA) vs. Ryan Levine (USA),Remote Duel Invitational,2020,Remote Duel Invitational,Remote Duel Invitational - TCG (8/22 - 8/23/2020)
1357,htTBIelTUB8,True,None,Round 3,Cameron Neal,None,Sam Arunnaveesiri,None,PLc1vyOIGc2qUwKZvwkAIZrfMup6QHDs-1,Remote Duel Invitational - TCG (8/22 - 8/23/2020),...,Remote Duel Invitational,2020,PLc1vyOIGc2qUwKZvwkAIZrfMup6QHDs-1,htTBIelTUB8,Yu Gi Oh! Remote Duel Invitational - TCG: Day 1 Round 3,Cameron Neal (USA) vs. Sam (TeamsamuraiX1) Arunnaveesiri (Canada),Remote Duel Invitational,2020,Remote Duel Invitational,Remote Duel Invitational - TCG (8/22 - 8/23/2020)

In [173]:
stage5[stage5['Video ID'] == 'Hvs3AmcZ8-4']

,Playlist ID,Video ID,Title,Video Description,Clean Title,Year,Category,Playlist Title
1029,PLIm0Rt8gzRbvoTO6w4CBrg0uOJmsPZYMQ,Hvs3AmcZ8-4,Round 6 - Gladiator Beast vs Gladiator Beast -...,For more information on the Time Wizard format...,YCS Bologna,2010,YCS,Ultimate Time Wizard 2010 - YCS Bologna 2024

In [83]:
merged = pd.read_parquet("pipeline/checkpoints/stage7_clean.parquet")
merged

,video_id,is_match,tournament,round,player_1,deck_1,player_2,deck_2,Playlist ID_x,Playlist Title_x,...,Category_x,Year_x,Playlist ID_y,Video ID,Title,Video Description,Clean Title_y,Year_y,Category_y,Playlist Title_y
0,gtY3Gm81ckc,True,YCS Bochum 2018,Round 1,Jörg Müller,None,Eugen Heidt,None,PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl,YCS Bochum 2018 | Yu-Gi-Oh! Championship Series Bochum 2018,...,YCS,2018,PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl,gtY3Gm81ckc,YCS Bochum 2018: Round 1 Feature Match,"Footage recorded from Yu-Gi-Oh! YCS Bochum, held on February 24/25, 2018.\nRound 1: Jörg Müller vs. Eugen Heidt\n \n Yu-Gi-Oh! TRADING CARD GAME\n © 1996 Kazuki Takahashi\n © 2014 NAS • TV TOKYO\n \n Web: www.yugioh-card.com\n \n Facebook: http://facebook.com/YuGiOhTCGEU\n Twitch: http://twitch.tv/OfficialYuGiOhChannel\n \n Live Event Coverage: www.yugioh-card.com/uk/live/\n Event Blog: http://coverage.yugioh-card.com -- Watch live at https://www.twitch.tv/officialyugiohc... -- Watch live at https://www.twitch.tv/officialyugiohc... -- Watch live at https://www.twitch.tv/officialyugiohchannel",YCS Bochum,2018,YCS,YCS Bochum 2018 | Yu-Gi-Oh! Championship Series Bochum 2018
1,Lpam8Aii1vM,True,YCS Bochum 2018,Round 2,Phillip Weldinger,None,Meicel Neugebauer,None,PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl,YCS Bochum 2018 | Yu-Gi-Oh! Championship Series Bochum 2018,...,YCS,2018,PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl,Lpam8Aii1vM,YCS Bochum 2018: Round 2 Feature Match,"Footage recorded from Yu-Gi-Oh! YCS Bochum, held on February 24/25, 2018.\nRound 2: Phillip Weldinger vs. Meicel Neugebauer\n \n Yu-Gi-Oh! TRADING CARD GAME\n © 1996 Kazuki Takahashi\n © 2014 NAS • TV TOKYO\n \n Web: www.yugioh-card.com\n \n Facebook: http://facebook.com/YuGiOhTCGEU\n Twitch: http://twitch.tv/OfficialYuGiOhChannel\n \n Live Event Coverage: www.yugioh-card.com/uk/live/\n Event Blog: http://coverage.yugioh-card.com -- Watch live at https://www.twitch.tv/officialyugiohc... -- Watch live at https://www.twitch.tv/officialyugiohc... -- Watch live at https://www.twitch.tv/officialyugiohchannel",YCS Bochum,2018,YCS,YCS Bochum 2018 | Yu-Gi-Oh! Championship Series Bochum 2018
2,wRwnUvpcyKA,True,YCS Bochum 2018,Round 3,Carmelo Buttiglieri,None,Adam Chamberlain,None,PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl,YCS Bochum 2018 | Yu-Gi-Oh! Championship Series Bochum 2018,...,YCS,2018,PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl,wRwnUvpcyKA,YCS Bochum 2018: Round 3 Feature Match,"Footage recorded from Yu-Gi-Oh! YCS Bochum, held on February 24/25, 2018.\nRound 3: Carmelo Buttiglieri vs. Adam Chamberlain\n \n Yu-Gi-Oh! TRADING CARD GAME\n © 1996 Kazuki Takahashi\n © 2014 NAS • TV TOKYO\n \n Web: www.yugioh-card.com\n \n Facebook: http://facebook.com/YuGiOhTCGEU\n Twitch: http://twitch.tv/OfficialYuGiOhChannel\n \n Live Event Coverage: www.yugioh-card.com/uk/live/\n Event Blog: http://coverage.yugioh-card.com -- Watch live at https://www.twitch.tv/officialyugiohc... -- Watch live at https://www.twitch.tv/officialyugiohc...\n -- Watch live at https://www.twitch.tv/officialyugiohchannel",YCS Bochum,2018,YCS,YCS Bochum 2018 | Yu-Gi-Oh! Championship Series Bochum 2018
3,tpR87uZpnfU,True,YCS Bochum 2018,Round 4,Jordan Gallacher,None,Steffen Friedow,None,PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl,YCS Bochum 2018 | Yu-Gi-Oh! Championship Series Bochum 2018,...,YCS,2018,PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl,tpR87uZpnfU,YCS Bochum 2018: Round 4 Feature Match,"Footage recorded from Yu-Gi-Oh! YCS Bochum, held on February 24/25, 2018.\r\nRound 4: Jordan Gallacher vs. Steffen Friedow\r\n \r\n Yu-Gi-Oh! TRADING CARD GAME\r\n © 1996 Kazuki Takahashi\r\n © 2014 NAS • TV TOKYO\r\n \r\n Web: www.yugioh-card.com\r\n \r\n Facebook: http://facebook.com/YuGiOhTCGEU\r\n Twitch: http://twitch.tv/OfficialYuGiOhChannel\r\n \r\n Live Event Coverage: www.yugioh-card.com/uk/live/\r\n Event Blog: http://coverage.yugioh-card.com -- Watch live at https://www.twitch.tv/officialyugiohc... -- Watch live at https://www.twitch.tv/officialyugiohc... -- Watch live at https://www.twitch.tv/officialyugiohchannel",YCS Bochum,2018,YCS,YCS Bochum 2018 | Yu-Gi-Oh! Championship Series Bochum 2018
4,Dwp_1bljFLo,True,YCS Bochum 2018,Round 5,Loan Cite-Mielle,None,David Schmidt,None,PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl,YCS Bochum 2018 | Yu-Gi-Oh! Championship Series Bochum 2018,...,YCS,2018,PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl,Dwp_1bljFLo,YCS Bochum 2018: Round 5 Feature Match,"Footage recorded from Yu-Gi-Oh! YCS Bochum, held on February 24/25, 2018.\r\nRound 5: Loan Cite-Mielle vs. David Schmidt\r\n \r\n Yu-Gi-Oh! TRADING CARD GAME\r\n © 1996 Kazuki Takahashi\r\n © 2014 NAS • TV TOKYO\r\n \r\n Web: www.yugioh-card.com\r\n \r\n Facebook: http://facebook.com/YuGiOhTCGEU\r\n Twitch: http://twitch.tv/OfficialYuGiOhChannel\r\n \r\n Live Event Coverage: www.yugioh-card.com/uk/live/\r\n Event Blog: http://coverage.yugioh-card.com -- Watch live at https://www.twitch.tv/officialyugiohc... -- Watch live at https://www.twitch.tv/officialyugiohc... -- Watch live at https://www.twitch.tv/officialyugiohchannel",YCS Bochum,2018,YCS,YCS Bochum 2018 | Yu-Gi-Oh! Championship Series Bochum 2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1353,-vsulzcQkF4,True,2017 World Championship TCG (All-Ages),3rd Place Match,Marcello Barberi,None,Michael Forner,None,PLc1vyOIGc2qVsXghcP-IRPwbIg9yiDTrc,Yu-Gi-Oh! 2017 World Championship,...,World Championship,2017,PLc1vyOIGc2qVsXghcP-IRPwbIg9yiDTrc,-vsulzcQkF4,2017 World Championship TCG (All-Ages) 3rd Place Match: Marcello Barberi vs Michael Forner,,World Championship,2017,World Championship,Yu-Gi-Oh! 2017 World Championship
1354,MXa5NlC_634,True,2017 World Championship TCG (All-Ages),Final,Ryosuke Tsujimura,None,Shen-Fei Milton Shua,None,PLc1vyOIGc2qVsXghcP-IRPwbIg9yiDTrc,Yu-Gi-Oh! 2017 World Championship,...,World Championship,2017,PLc1vyOIGc2qVsXghcP-IRPwbIg9yiDTrc,MXa5NlC_634,2017 World Championship TCG (All-Ages) Final: Ryosuke Tsujimura vs Shen-Fei Milton Shua,,World Championship,2017,World Championship,Yu-Gi-Oh! 2017 World Championship
1355,MjBeOAdEWdM,False,None,None,None,None,None,None,PLc1vyOIGc2qUwKZvwkAIZrfMup6QHDs-1,Remote Duel Invitational - TCG (8/22 - 8/23/2020),...,Remote Duel Invitational,2020,PLc1vyOIGc2qUwKZvwkAIZrfMup6QHDs-1,MjBeOAdEWdM,Yu Gi Oh! Remote Duel Invitational - TCG: Day 1 Round 1,Gage Poljak (USA) vs Ryan Yu (Canada),Remote Duel Invitational,2020,Remote Duel Invitational,Remote Duel Invitational - TCG (8/22 - 8/23/2020)
1356,RJDej8ylczo,False,None,None,None,None,None,None,PLc1vyOIGc2qUwKZvwkAIZrfMup6QHDs-1,Remote Duel Invitational - TCG (8/22 - 8/23/2020),...,Remote Duel Invitational,2020,PLc1vyOIGc2qUwKZvwkAIZrfMup6QHDs-1,RJDej8ylczo,"Yu Gi Oh! Remote Duel Invitational - TCG: Day 1, Round 2",Blair Hunter (USA) vs. Ryan Levine (USA),Remote Duel Invitational,2020,Remote Duel Invitational,Remote Duel Invitational - TCG (8/22 - 8/23/2020)
1357,htTBIelTUB8,True,None,Round 3,Cameron Neal,None,Sam Arunnaveesiri,None,PLc1vyOIGc2qUwKZvwkAIZrfMup6QHDs-1,Remote Duel Invitational - TCG (8/22 - 8/23/2020),...,Remote Duel Invitational,2020,PLc1vyOIGc2qUwKZvwkAIZrfMup6QHDs-1,htTBIelTUB8,Yu Gi Oh! Remote Duel Invitational - TCG: Day 1 Round 3,Cameron Neal (USA) vs. Sam (TeamsamuraiX1) Arunnaveesiri (Canada),Remote Duel Invitational,2020,Remote Duel Invitational,Remote Duel Invitational - TCG (8/22 - 8/23/2020)

In [91]:
filtered = merged[
    (merged["is_match"] == False)
]
filtered

,video_id,is_match,tournament,round,player_1,deck_1,player_2,deck_2,Playlist ID_x,Playlist Title_x,...,Category_x,Year_x,Playlist ID_y,Video ID,Title,Video Description,Clean Title_y,Year_y,Category_y,Playlist Title_y
17,tj25H8Sy5ok,False,None,None,None,None,None,None,PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl,YCS Bochum 2018 | Yu-Gi-Oh! Championship Series Bochum 2018,...,YCS,2018,PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl,tj25H8Sy5ok,YCS Bochum 2018: Pendulum Magician vs Trickstar - Jesse Kotton,"Footage recorded from Yu-Gi-Oh! YCS Bochum, held on February 24/25, 2018.\nPendulum Magician vs Trickstar - Jesse Kotton\n\nYu-Gi-Oh! TRADING CARD GAME\n© 1996 Kazuki Takahashi\n© 2014 NAS • TV TOKYO\n\n\nWeb: http://www.yugioh-card.com\n\nFacebook: http://facebook.com/YuGiOhTCGEU\nTwitch: http://twitch.tv/OfficialYuGiOhChannel\n\nLive Event Coverage: www.yugioh-card.com/uk/live/\nCoverage Blog: http://konami-europe.com/coverage",YCS Bochum,2018,YCS,YCS Bochum 2018 | Yu-Gi-Oh! Championship Series Bochum 2018
18,g6hQxO8q6V0,False,None,None,None,None,None,None,PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl,YCS Bochum 2018 | Yu-Gi-Oh! Championship Series Bochum 2018,...,YCS,2018,PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl,g6hQxO8q6V0,YCS Bochum 2018: Pendulum Magician vs Trickstar - Lorenzo Roma,"Footage recorded from Yu-Gi-Oh! YCS Bochum, held on February 24/25, 2018.\nPendulum Magician vs Trickstar - Lorenzo Roma\n\nYu-Gi-Oh! TRADING CARD GAME\n© 1996 Kazuki Takahashi\n© 2014 NAS • TV TOKYO\n\n\nWeb: http://www.yugioh-card.com\n\nFacebook: http://facebook.com/YuGiOhTCGEU\nTwitch: http://twitch.tv/OfficialYuGiOhChannel\n\nLive Event Coverage: www.yugioh-card.com/uk/live/\nCoverage Blog: http://konami-europe.com/coverage",YCS Bochum,2018,YCS,YCS Bochum 2018 | Yu-Gi-Oh! Championship Series Bochum 2018
19,pNFSiXYdXzQ,False,None,None,None,None,None,None,PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl,YCS Bochum 2018 | Yu-Gi-Oh! Championship Series Bochum 2018,...,YCS,2018,PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl,pNFSiXYdXzQ,YCS Bochum 2018: Pendulum Magician vs Trickstar - Joshua Schmidt,"Footage recorded from Yu-Gi-Oh! YCS Bochum, held on February 24/25, 2018.\nPendulum Magician vs Trickstar - Joshua Schmidt\n\nYu-Gi-Oh! TRADING CARD GAME\n© 1996 Kazuki Takahashi\n© 2014 NAS • TV TOKYO\n\n\nWeb: http://www.yugioh-card.com\n\nFacebook: http://facebook.com/YuGiOhTCGEU\nTwitch: http://twitch.tv/OfficialYuGiOhChannel\n\nLive Event Coverage: www.yugioh-card.com/uk/live/\nCoverage Blog: http://konami-europe.com/coverage",YCS Bochum,2018,YCS,YCS Bochum 2018 | Yu-Gi-Oh! Championship Series Bochum 2018
36,UW-WXN2Ly6w,False,None,None,None,None,None,None,PLIm0Rt8gzRbss2nX1mixsDYj4CpmZ8ugW,WCQ: EC2015 | 2015 Yu-Gi-Oh! TCG WCQ: European Championship,...,World Championship,2015,PLIm0Rt8gzRbss2nX1mixsDYj4CpmZ8ugW,UW-WXN2Ly6w,WCQ: EC2015: Dragon Duel - Final Highlights,"Footage recorded from 2015 WCQ: European Championship, held on July 04/05.\nWCQ Dublin: Dragon Duel - Final Highlights: Andrea Pittorino (Satellar) vs. Zoltan Kolonics (Nekroz)\n\nYu-Gi-Oh! TRADING CARD GAME\n© 1996 Kazuki Takahashi\n© 2014 NAS • TV TOKYO\n\nWeb: www.yugioh-card.com\n\nFacebook: http://facebook.com/YuGiOhTCGEU\nTwitch: http://twitch.tv/OfficialYuGiOhChannel\n\nLive Event Coverage: www.yugioh-card.com/uk/live/\nEvent Blog: http://konami-europe.com/coverage -- Watch live at http://www.twitch.tv/officialyugiohchannel",EU World Championship Qualifer,2015,World Championship,WCQ: EC2015 | 2015 Yu-Gi-Oh! TCG WCQ: European Championship
45,c74KX8N5s1Y,False,None,None,None,None,None,None,PLIm0Rt8gzRbss2nX1mixsDYj4CpmZ8ugW,WCQ: EC2015 | 2015 Yu-Gi-Oh! TCG WCQ: European Championship,...,World Championship,2015,PLIm0Rt8gzRbss2nX1mixsDYj4CpmZ8ugW,c74KX8N5s1Y,WCQ: EC2015: Round 9 Feature Match Highlights,"Footage recorded from Yu-Gi-Oh! World Championship Qualifier Dublin, held on July 04/05, 2015.\r\nRound 9 Feature Match Highlights: Sebastian Moser (Yosenju) vs. Giovanni Paolini (Nekroz)\r\n\r\nYu-Gi-Oh! TRADING CARD GAME\r\n© 1996 Kazuki Takahashi\r\n© 2014 NAS • TV TOKYO\r\n\r\nWeb: www.yugioh-card.com\r\n\r\nFacebook: http://facebook.com/YuGiOhTCGEU\r\nTwitch: http://twitch.tv/OfficialYuGiOhChannel\r\n\r\nLive Event Coverage: www.yugioh-card.com/uk/live/\r\nEvent Blog: http://konami-europe.com/coverage -- Watch live at http://www.twitch.tv/officialyugiohchannel",EU World Championship Qualifer,2015,World Championship,WCQ: EC2015 | 2015 Yu-Gi-Oh! TCG WCQ: European Championship
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1027,Hvs3AmcZ8-4,False,None,None,None,None,None,None,PLIm0Rt8gzRbvoTO6w4CBrg0uOJmsPZYMQ,Ultimate Time Wizard 2010 - YCS Bologna 2024,...,YCS,2010,PLIm0Rt8gzRbvoTO6w4CBrg0uOJmsPZYMQ,Hvs3AmcZ8-4,Round 6 - Gladiator Beast vs Gladiator Beast - Ultimate Time Wizard 2010 YCS Bologna 2024,"For more information on the Time Wizard format and how to find your local tournaments, visit https://www.yugioh-card.com/eu/event/time-wizard/ \n\nBe sure to Subscribe to our Channel and hit the alert bell to know when a new video is available! \n \nStay up to date on Yu-Gi-Oh! TCG and Yu-Gi-Oh! Digital titles at http://www.yugioh-card.com\n \nFacebook: https://facebook.com/YuGiOhCardEU\nTwitch: https://twitch.tv/YuGiOhCardEU\nTwitter: https://twitter.com/YuGiOhCardEU\nInstagram: https://www.instagram.com/YuGiOhCardEU\n \n©2020 Studio Dice／SHUEISHA, TV TOKYO, KONAMI\n©Konami Digital Entertainment",YCS Bologna,2010,YCS,Ultimate Time Wizard 2010 - YCS Bologna 2024
1107,k78lSiU7GSY,False,None,None,None,None,None,None,PLc1vyOIGc2qUclsFSVx6fWVI0pI9TQDUp,Yu-Gi-Oh! World Championship 2019,...,World Championship,2019,PLc1vyOIGc2qUclsFSVx6fWVI0pI9TQDUp,k78lSiU7GSY,YuGiOh REAL LIFE DUEL | YUGI vs KAIBA!!,Buy LEGEND of BLUE EYES White Dragon 25th Anniversary HERE ► https://bit.ly/25thAnniversaryYGO\nSubscribe to our Secondary Channel Here ► https://www.youtube.com/@simplyunluckytv\nBuy Cards at Our Game Shop Here ► https://linktr.ee/simplyunlucky\nFollow SimplyUnlucky on Whatnot for DAILY Giveaways & Live Streams ► https://www.whatnot.com/invite/simplyunlucky\n\nSimplyUnlucky OFFICIAL TOURNAMENT STORE Address ►\n2307 Oakdale Rd Suite 601 Modesto CA 95355 \nOpen 10-6 PST\n\nThank you for supporting SU in creating the Best Card Shop! KAIBA!!\n\n#SimplyUnlucky #YuGiOh #遊戯王,World Championship,2019,World Championship,Yu-Gi-Oh! World Championship 2019
1227,iAXWdhX6520,False,None,None,None,None,None,None,PLc1vyOIGc2qUdrzkwxpyWPF7hEA-4nxYM,Dueling Archives: YCS Providence 2025,...,YCS,2025,PLc1vyOIGc2qUdrzkwxpyWPF7hEA-4nxYM,iAXWdhX6520,"2025 North America YCS Providence, RI // Round 5 - Jonathan M. vs. Rehan S.",Swiss Round 5 Match replay from 2025 YCS Providence between Jonathan M. and Rehan S.,YCS Providence,2025,YCS,Dueling Archives: YCS Providence 2025
1355,MjBeOAdEWdM,False,None,None,None,None,None,None,PLc1vyOIGc2qUwKZvwkAIZrfMup6QHDs-1,Remote Duel Invitational - TCG (8/22 - 8/23/2020),...,Remote Duel Invitational,2020,PLc1vyOIGc2qUwKZvwkAIZrfMup6QHDs-1,MjBeOAdEWdM,Yu Gi Oh! Remote Duel Invitational - TCG: Day 1 Round 1,Gage Poljak (USA) vs Ryan Yu (Canada),Remote Duel Invitational,2020,Remote Duel Invitational,Remote Duel Invitational - TCG (8/22 - 8/23/2020)
1356,RJDej8ylczo,False,None,None,None,None,None,None,PLc1vyOIGc2qUwKZvwkAIZrfMup6QHDs-1,Remote Duel Invitational - TCG (8/22 - 8/23/2020),...,Remote Duel Invitational,2020,PLc1vyOIGc2qUwKZvwkAIZrfMup6QHDs-1,RJDej8ylczo,"Yu Gi Oh! Remote Duel Invitational - TCG: Day 1, Round 2",Blair Hunter (USA) vs. Ryan Levine (USA),Remote Duel Invitational,2020,Remote Duel Invitational,Remote Duel Invitational - TCG (8/22 - 8/23/2020)

In [96]:
false_negatives = merged[
    (merged["is_match"] == False) &
    (merged["Title"].str.contains("Round|Top|Final|vs|Feature Match", case=False, na=False))
]

# print(len(false_negatives))
# for t in false_negatives["Title"]:
#     print(t)

titles = false_negatives["Title"].dropna().tolist()
titles

['YCS Bochum 2018: Pendulum Magician vs Trickstar - Jesse Kotton',
 'YCS Bochum 2018: Pendulum Magician vs Trickstar - Lorenzo Roma',
 'YCS Bochum 2018: Pendulum Magician vs Trickstar - Joshua Schmidt',
 'WCQ: EC2015: Dragon Duel - Final Highlights',
 'WCQ: EC2015: Round 9 Feature Match Highlights',
 'WCQ: EC2015: Round 8 Feature Match Highlights',
 'WCQ: EC2015: Round 7 Feature Match Highlights',
 'WCQ: EC2015: Round 3 Feature Match Highlights',
 'WCQ: EC2015: Round 2 Feature Match Highlights',
 'WCQ 2016 Berlin: Round 7 Feature Match Highlights',
 'WCQ 2016 Berlin: Round 6 Feature Match Highlights',
 'YCS Milan 2018: Round 10 - Hot Takes - Part 1',
 'YCS Milan 2018: Round 10 - Hot Takes - Part 2',
 'YCS Milan 2018: Round 10 - Hot Takes - Part 4',
 'YCS Milan 2018: Round 10 - Hot Takes - Part 3',
 'YCS Milan 2018: Round 10 - Yu-Gi-Oh! Games - Part 1',
 'YCS Milan 2018: Round 7 - Hot Takes - Part 1',
 'YCS Milan 2018: Round 7 - Hot Takes - Part 2',
 'Master vs. Caster |\xa0YCS Bologna 2025',
 'Yu-Gi-Oh! World Championship 2025 - TCG Finals Opening Ceremony - Salif Gueye (Crookboyz) & His Crew',
 'Yu-Gi-Oh! WCS 2025 | Master Duel & Duel Links Finals Opening Ceremony',
 'Yu-Gi-Oh! WCS 2025 | Day 2 - Master Duel/Duel Links finals & TCG Qualifiers spotlight',
 'Yu-Gi-Oh! WCS 2025 | Day 2 Master Duel & Duel Links Finals highlights',
 'Yu-Gi-Oh! WCS 2025 | Billy Brake & Marcello Barberi discuss player vs commentator WCS experience',
 'Yu-Gi-Oh! WCS 2025 | Day 2 Master Duel & Duel Links Finals spotlight',
 '300th YCS Dortmund 2026 - YCS Memories Infernoid Zodiac vs. Paleozoic',
 '300th YCS Dortmund 2026 - YCS Memories Shaddoll vs. Shaddoll',
 '300 YCS Dortmund 2026 - YCS Memories Spright vs. Kashtira',
 'YCS Bologna 2024 - Caster vs. Master 2',
 'YCS Bologna 2024 - Caster vs. Master 1',
 'YCS Bologna 2024 - Round 5 - Christoph T. vs. Felix F.',
 'YCS Birmingham 2025 - Dueling Chronicles - Mermail vs. Infernity',
 'YCS Birmingham 2025 - Dueling Chronicles - Plant Synchro vs. Gadget',
 'YCS Birmingham 2025 - Caster vs Master',
 'YCS Birmingham 2025 - Round 9 - Manuel S. vs. Pasha G.',
 'YCS Birmingham 2025 - Round 8 - Conor B. vs. Ed S.',
 'YCS Birmingham 2025 - Round 7 - Lochlann S. vs. Finley T.',
 'YCS Birmingham 2025 - Round 6 - Jack Rory S. vs. Oliver G.',
 '275th YCS Lille 2024 - Dueling Chronicles: YCS Lille 2013 Finals',
 '275th YCS Lille 2024 - Caster vs Master: Sebastian Lemke vs Christos Mourikis',
 'YCS London 2017: Round 11',
 '2018 YCS London: Yu-Gi-Oh Championship Series - Top 4 - Ping Xiao vs Tayfun Bayraktar',
 'YCS Prague 2017: Top 16 Feature Match',
 'YCS London: Round 3 Feature Match',
 'YCS London: Round 4 Feature Match',
 'YCS Prague: Round 3 Feature Match',
 '2018 Yu-Gi-Oh! Duel Links World Championship - Yeom-Jun Lee vs Josh Cooper',
 '2018 Yu-Gi-Oh! Duel Links World Championship - Charlie Whyborne vs Alex Cheung',
 '2018 Yu-Gi-Oh! Duel Links World Championship - Roy Svinik vs Ryoichi Kitahata',
 '2018 Yu-Gi-Oh! Duel Links World Championship - Jason Chu vs Marjo Jahaj',
 '2018 Yu-Gi-Oh! Duel Links World Championship - Patricio vs Wzarimi Thayib',
 '2018 Yu-Gi-Oh! TCG World Championship - Finals Opening Ceremony',
 '2018 Yu-Gi-Oh! Duel Links World Championship - Final',
 '2018 Yu-Gi-Oh! TCG World Championship - Final & Award Ceremony',
 '2016 WCQ: UK National | Top 64',
 'YCS Rimini 2017: Round 7',
 'YCS Utrecht 2020 - Round 7 - Eike Ruting vs. David Erpen',
 'YCS Bologna 2023 - Top 64 - Joo-Ho A. vs. Emilio S.',
 'YCS Dortmund 2023 - Round 7 - Jordan G. vs. David E.',
 'Round 9 – Arthur Tarrieu vs. Alvaro Bonilla – European Yu-Gi-Oh! Championship 2022 – Day 1',
 'YCS Ghent 2019 - Round 9 - Alexandre Pousset vs. Marvin Schmidt (part2)',
 'YCS Dortmund 2022 - Round 12 - Lars J. vs. Piyal P.',
 'YCS Sydney 2017: Round 6',
 'YCS Melbourne 2018: Top 16 Feature Match',
 '2017 World Championship | Duel Links | Round 5: dgzo vs Tutpup',
 '2018 WCQ: National Championship - UK - Round 7 - Finn Bakewell vs Joe White',
 'Round 1 - Plants vs Frog HERO - Ultimate Time Wizard 2010 YCS Bologna 2024',
 'Round 2 - Lightsworn vs Chaos Fairy - Ultimate Time Wizard 2010 YCS Bologna 2024',
 'Round 3 - Machina Gadget vs Blackwing - Ultimate Time Wizard 2010 YCS Bologna 2024',
 'Round 4 - Machina Synchro vs Flamvell Frog - Ultimate Time Wizard 2010 YCS Bologna 2024',
 'Round 5 - Blackwing vs Frog Monarch - Ultimate Time Wizard 2010 YCS Bologna 2024',
 'Round 6 - Gladiator Beast vs Gladiator Beast - Ultimate Time Wizard 2010 YCS Bologna 2024',
 'YuGiOh REAL LIFE DUEL | YUGI vs KAIBA!!',
 '2025 North America YCS Providence, RI // Round 5 - Jonathan M. vs. Rehan S.',
 'Yu Gi Oh! Remote Duel Invitational - TCG: Day 1 Round 1',
 'Yu Gi Oh! Remote Duel Invitational - TCG: Day 1, Round 2']

In [163]:
stage6 = pd.read_parquet("pipeline/checkpoints/stage6_matches.parquet")
stage5 = pd.read_parquet("pipeline/checkpoints/stage5_matches.parquet")

stage5_clean = stage5.drop_duplicates(subset=["Video ID"])
stage6_clean = stage6.drop_duplicates(subset=["video_id"])
df = stage6_clean.merge(
    stage5_clean,
    left_on="video_id",
    right_on="Video ID",
    how="left")

candidates = df[df["is_match"] == False].copy()
# suspects = candidates[
#     candidates["Title"].str.contains(
#         r"Round|vs|Feature Match|Final",
#         case=False,
#         na=False
#     )
# ]

to_drop = []
fine = []

for i, row in suspects.iterrows():
    # print("\n--------------------")
    # print(row["video_id"])
    # print(row["Title"])
    title = row["Title"].lower()
    
    if ("memories" in title
          or "caster vs" in title
          or "chronicles" in title
          or "duel links" in title):
        to_drop.append(i)
        
    elif ("round" in title
           or "top" in title
           or "3rd" in title):
        if ("hot takes" in title
            or "highlights" in title
            or "yu-gi-oh! games" in title):
            to_drop.append(i)
        else:
            fine.append(i)

df = df.drop(index=to_drop)
# dropped 35 non related videos

# keep_candidates = candidates.loc[fine]
keep_candidates

,video_id,is_match,tournament,round,player_1,deck_1,player_2,deck_2,Playlist ID_x,Playlist Title_x,...,Category_x,Year_x,Playlist ID_y,Video ID,Title,Video Description,Clean Title_y,Year_y,Category_y,Playlist Title_y
309,6rhZfFY5ezc,False,None,None,None,None,None,None,PLIm0Rt8gzRbtnbZYH99PGTqCWtR6WZS77,YCS Bologna 2024,...,YCS,2024,PLIm0Rt8gzRbtnbZYH99PGTqCWtR6WZS77,6rhZfFY5ezc,YCS Bologna 2024 - Round 5 - Christoph T. vs. Felix F.,Watch Round 5 of YCS Bologna 2024: Christoph T. (Goblin Bikers) vs. Felix F. (Fiendsmith Yubel) -- Watch live at https://www.twitch.tv/yugiohcardeu,YCS Bologna,2024,YCS,YCS Bologna 2024
326,zEFYAFKMJRw,False,None,None,None,None,None,None,PLIm0Rt8gzRbuSa9zamQ9XAqfN9f5wa0IM,YCS Birmingham 2025,...,YCS,2025,PLIm0Rt8gzRbuSa9zamQ9XAqfN9f5wa0IM,zEFYAFKMJRw,YCS Birmingham 2025 - Round 9 - Manuel S. vs. Pasha G.,Watch Round 9 of YCS Birmingham 2025: Manuel S. (Mermail) vs. Pasha G. (Fiendsmith Memento - Watch live at https://www.twitch.tv/yugiohcardeu,YCS Birmingham,2025,YCS,YCS Birmingham 2025
327,AwWVkKpnBIQ,False,None,None,None,None,None,None,PLIm0Rt8gzRbuSa9zamQ9XAqfN9f5wa0IM,YCS Birmingham 2025,...,YCS,2025,PLIm0Rt8gzRbuSa9zamQ9XAqfN9f5wa0IM,AwWVkKpnBIQ,YCS Birmingham 2025 - Round 8 - Conor B. vs. Ed S.,Watch Round 8 of YCS Birmingham 2025: Conor B. (Runick Bystial) vs. Ed S. (Tenpai Sky Striker) - Watch live at https://www.twitch.tv/yugiohcardeu,YCS Birmingham,2025,YCS,YCS Birmingham 2025
328,4zubx1TJgeo,False,None,None,None,None,None,None,PLIm0Rt8gzRbuSa9zamQ9XAqfN9f5wa0IM,YCS Birmingham 2025,...,YCS,2025,PLIm0Rt8gzRbuSa9zamQ9XAqfN9f5wa0IM,4zubx1TJgeo,YCS Birmingham 2025 - Round 7 - Lochlann S. vs. Finley T.,Watch Round 7 of YCS Birmingham 2025: Lochlann S. (Shark) vs. Finley T. (Bystial Maliss) - Watch live at https://www.twitch.tv/yugiohcardeu,YCS Birmingham,2025,YCS,YCS Birmingham 2025
329,Bx7Ugk4_LWM,False,None,None,None,None,None,None,PLIm0Rt8gzRbuSa9zamQ9XAqfN9f5wa0IM,YCS Birmingham 2025,...,YCS,2025,PLIm0Rt8gzRbuSa9zamQ9XAqfN9f5wa0IM,Bx7Ugk4_LWM,YCS Birmingham 2025 - Round 6 - Jack Rory S. vs. Oliver G.,Watch Round 6 of YCS Birmingham 2025: Jack Rory S. (Ryzeal) vs. Oliver G. (Tearlaments Paleo) - Watch live at https://www.twitch.tv/yugiohcardeu,YCS Birmingham,2025,YCS,YCS Birmingham 2025
475,FsT09iPtrYQ,False,None,None,None,None,None,None,PLIm0Rt8gzRbvARnj3qZUwXVaN3WLiZu-G,YCS London 2017 | Yu-Gi-Oh! Championship Series London 2017,...,YCS,2017,PLIm0Rt8gzRbvARnj3qZUwXVaN3WLiZu-G,FsT09iPtrYQ,YCS London 2017: Round 11,"Footage recorded from Yu-Gi-Oh! YCS London, held on October 28/29, 2017.\r\nRound 11: Leon Dowe-Ranger vs. Leon Dowe-Ranger \r\n \r\n Yu-Gi-Oh! TRADING CARD GAME\r\n © 1996 Kazuki Takahashi\r\n © 2014 NAS • TV TOKYO\r\n \r\n Web: www.yugioh-card.com\r\n \r\n Facebook: http://facebook.com/YuGiOhTCGEU\r\n Twitch: http://twitch.tv/OfficialYuGiOhChannel\r\n \r\n Live Event Coverage: www.yugioh-card.com/uk/live/\r\n Event Blog: http://coverage.yugioh-card.com -- Watch live at https://www.twitch.tv/officialyugiohchannel -- Watch live at https://www.twitch.tv/officialyugiohchannel",YCS London,2017,YCS,YCS London 2017 | Yu-Gi-Oh! Championship Series London 2017
508,uLzecajpVXE,False,None,None,None,None,None,None,PLIm0Rt8gzRbvdbAcXuDGBPDQ24dW5wjKc,YCS London 2018 | Yu-Gi-Oh! Championship Series London 2018,...,YCS,2018,PLIm0Rt8gzRbvdbAcXuDGBPDQ24dW5wjKc,uLzecajpVXE,2018 YCS London: Yu-Gi-Oh Championship Series - Top 4 - Ping Xiao vs Tayfun Bayraktar,"Footage recorded from Yu-Gi-Oh! YCS London, held on October 27/28, 2018.\nTop 4: Ping Xiao vs Tayfun Bayraktar\n \nYu-Gi-Oh! TRADING CARD GAME\n© 1996 Kazuki Takahashi\n© 2017 NAS • TV TOKYO\n \nWeb: www.yugioh-card.com\n \nFacebook: http://facebook.com/YuGiOhTCGEU\nTwitch: http://twitch.tv/OfficialYuGiOhChannel\n \nLive Event Coverage: www.yugioh-card.com/uk/live/\nEvent Blog: http://coverage.yugioh-card.com -- Watch live at https://www.twitch.tv/officialyugiohchannel",YCS London,2018,YCS,YCS London 2018 | Yu-Gi-Oh! Championship Series London 2018
587,slTQ8z-g9iY,False,None,None,None,None,None,None,PLIm0Rt8gzRbvOLxLL69WsUn1Q6jwbpDRo,YCS Prague 2017 | Yu-Gi-Oh! Championship Series Prague 2017 (November),...,YCS,2017,PLIm0Rt8gzRbvOLxLL69WsUn1Q6jwbpDRo,slTQ8z-g9iY,YCS Prague 2017: Top 16 Feature Match,"Footage recorded from YCS Prague 2017, held on November 25/26, 2017.\nTop 16 Feature Match: Raymond Torres (Trickstar) vs. Callum Hinchcliffe (SPYRAL)\n \n Yu-Gi-Oh! TRADING CARD GAME\n © 1996 Kazuki Takahashi\n © 2014 NAS • TV TOKYO\n \n Web: www.yugioh-card.com\n \n Facebook: http://facebook.com/YuGiOhTCGEU\n Twitch: http://twitch.tv/OfficialYuGiOhChannel\n \n Live Event Coverage: www.yugioh-card.com/uk/live/\n Event Blog: http://coverage.yugioh-card.com",YCS Prague,2017,YCS,YCS Prague 2017 | Yu-Gi-Oh! Championship Series Prague 2017 (November)
593,EO15MEh2F7g,False,None,None,None,None,None,None,PLIm0Rt8gzRbsM_eU_TVTTh8GJPA1ZCF0Z,YCS London | Yu-Gi-Oh! Championship Series London,...,YCS,Unknown,PLIm0Rt8gzRbsM_eU_TVTTh8GJPA1ZCF0Z,EO15MEh2F7g,YCS London: Round 3 Feature Match,"Footage recorded from Yu-Gi-Oh! Championship Series London, held on October 25/26, 2014.\r\nRound 2 Feature Match: Tomasz Allen (Shaddoll) vs. Nathen Sergent (Gravekeeper)\r\n\r\nYu-Gi-Oh! TRADING CARD GAME\r\n© 1996 Kazuki Takahashi\r\n© 2014 NAS • TV TOKYO\r\n\r\nWeb: www.yugioh-card.com\r\n\r\nFacebook: http://facebook.com/YuGiOhTCGEU\r\nTwitch: http://twitch.tv/OfficialYuGiOhChannel\r\n\r\nLive Event Coverage: www.yugioh-card.com/uk/live/\r\nEvent Blog: http://konami-europe.com/coverage -- Watch live at http://www.twitch.tv/officialyugiohchannel",YCS London,Unknown,YCS,YCS London | Yu-Gi-Oh! Championship Series London
594,-ZHQxKRwH4g,False,None,None,None,None,None,None,PLIm0Rt8gzRbsM_eU_TVTTh8GJPA1ZCF0Z,YCS London | Yu-Gi-Oh! Championship Series London,...,YCS,Unknown,PLIm0Rt8gzRbsM_eU_TVTTh8GJPA1ZCF0Z,-ZHQxKRwH4g,YCS London: Round 4 Feature Match,"Footage recorded from Yu-Gi-Oh! Championship Series London, held on October 25/26, 2014.\r\nRound 1 Feature Match: Michael Cipalz (/) vs. Marcello Barberi (/)\r\n\r\nYu-Gi-Oh! TRADING CARD GAME\r\n© 1996 Kazuki Takahashi\r\n© 2014 NAS • TV TOKYO\r\n\r\nWeb: www.yugioh-card.com\r\n\r\nFacebook: http://facebook.com/YuGiOhTCGEU\r\nTwitch: http://twitch.tv/OfficialYuGiOhChannel\r\n\r\nLive Event Coverage: www.yugioh-card.com/uk/live/\r\nEvent Blog: http://konami-europe.com/coverage -- Watch live at http://www.twitch.tv/officialyugiohchannel",YCS London,Unknown,YCS,YCS London | Yu-Gi-Oh! Championship Series London
607,u8oYhIA313k,False,None,None,None,None,None,None,PLIm0Rt8gzRbtuya5V5H6zeKwIlmbwyunI,YCS Prague 2016 | Yu-Gi-Oh! Championship Series Prague 2016,...,YCS,2016,PLIm0Rt8gzRbtuya5V5H6zeKwIlmbwyunI,u8oYhIA313k,YCS Prague: Round 3 Feature Match,Yu-Gi-Oh! TRADING CARD GAME\r\n© 1996 Kazuki Takahashi\r\n© 2014 NAS • TV TOKYO\r\n\r\nWeb: www.yugioh-card.com\r\n\r\nFacebook: http://facebook.com/YuGiOhTCGEU\r\nTwitch: http://twitch.tv/OfficialYuGiOhChannel\r\n\r\nLive Event Coverage: www.yugioh-card.com/uk/live/\r\nEvent Blog: http://konami-europe.com/coverage -- Watch live at http://www.twitch.tv/officialyugiohchannel,YCS Prague,2016,YCS,YCS Prague 2016 | Yu-Gi-Oh! Championship Series Prague 2016
633,1ABWYJfRpAY,False,None,None,None,None,None,None,PLIm0Rt8gzRbsNALbcx6KJ8V5a2-mYLUCn,2018 Yu-Gi-Oh! World Championship,...,World Championship,2018,PLIm0Rt8gzRbsNALbcx6KJ8V5a2-mYLUCn,1ABWYJfRpAY,2018 Yu-Gi-Oh! TCG World Championship - 3rd Place Playoff,Broadcasted live on Twitch -- Watch live at https://www.twitch.tv/officialyugiohchannel,World Championship,2018,World Championship,2018 Yu-Gi-Oh! World Championship
645,HbxQcpYZiV0,False,None,None,None,None,None,None,PLIm0Rt8gzRbsidpr96G4FFXf9GvdMh-lB,2016 WCQ: UK National Championship,...,National Championship,2016,PLIm0Rt8gzRbsidpr96G4FFXf9GvdMh-lB,HbxQcpYZiV0,2016 WCQ: UK National | Top 64,-- Watch live at https://www.twitch.tv/officialyugiohchannel,World Qualifying PointsUK National Championship,2016,National Championship,2016 WCQ: UK National Championship
667,wunWpXa-0iM,False,None,None,None,None,None,None,PLIm0Rt8gzRbviW3duevd3e3C1QjalKtlj,YCS Rimini 2017 | Yu-Gi-Oh! Championship Series Rimini 2017,...,YCS,2017,PLIm0Rt8gzRbviW3duevd3e3C1QjalKtlj,wunWpXa-0iM,YCS Rimini 2017: Round 7,"Footage recorded from Yu-Gi-Oh! YCS Rimini 2017, held on August 26/27, 2017.\r\nRound 7: Stefano Campanale (Pendulum Magician) vs. Alexis Grand (Dino Yang Zing)\r\n \r\n Yu-Gi-Oh! TRADING CARD GAME\r\n © 1996 Kazuki Takahashi\r\n © 2014 NAS • TV TOKYO\r\n \r\n Web: www.yugioh-card.com\r\n \r\n Facebook: http://facebook.com/YuGiOhTCGEU\r\n Twitch: http://twitch.tv/OfficialYuGiOhChannel\r\n \r\n Live Event Coverage: www.yugioh-card.com/uk/live/\r\n Event Blog: http://coverage.yugioh-card.com\r\n -- Watch live at https://www.twitch.tv/officialyugiohchannel",YCS Rimini,2017,YCS,YCS Rimini 2017 | Yu-Gi-Oh! Championship Series Rimini 2017
726,JhwkFMPxClY,False,None,None,None,None,None,None,PLIm0Rt8gzRbuO5Y9S6sLDEcy9ceIQpkHB,YCS Utrecht 2020 | Yu-Gi-Oh! Championship Series Utrecht 2020,...,YCS,2020,PLIm0Rt8gzRbuO5Y9S6sLDEcy9ceIQpkHB,JhwkFMPxClY,YCS Utrecht 2020 - Round 7 - Eike Ruting vs. David Erpen,🇳🇱Livestream #YCSUtrecht 🇳🇱\nHere we are again with Round ️7⃣️! Eike Ruting 🇩🇪 is dueling David Erpen 🇨🇭! -- Watch live at https://www.twitch.tv/officialyugiohchannel,YCS Utrecht,2020,YCS,YCS Utrecht 2020 | Yu-Gi-Oh! Championship Series Utrecht 2020
767,NSZhaNU7KHc,False,None,None,None,None,None,None,PLIm0Rt8gzRbs_jPCYppMNC7TOCuibkYgy,Yu-Gi-Oh! Championship Series Bologna 2023,...,YCS,2023,PLIm0Rt8gzRbs_jPCYppMNC7TOCuibkYgy,NSZhaNU7KHc,YCS Bologna 2023 - Top 64 - Joo-Ho A. vs. Emilio S.,"Watch the Top 64 match of YCS Bologna 2023: Joo-Ho A. (Labrynth) vs. Emilio S. (Horus Vanquish Soul).\n\nFacebook: https://facebook.com/YuGiOhCardEU\nTwitch: https://twitch.tv/YuGiOhCardEU\nTwitter: https://twitter.com/YuGiOhCardEU\nInstagram: https://www.instagram.com/YuGiOhCardEU\n\n2020 Studio Dice／SHUEISHA, TV TOKYO, KONAMI\nKonami Digital Entertainment -- Watch live at https://www.twitch.tv/yugiohcardeu",YCS Bologna,2023,YCS,Yu-Gi-Oh! Championship Series Bologna 2023
794,1atPgoNSf7E,False,None,None,None,None,None,None,PLIm0Rt8gzRbsWWG_zEMA3iybOAd7TF1gc,Yu-Gi-Oh! Championship Series Dortmund 2023,...,YCS,2023,PLIm0Rt8gzRbsWWG_zEMA3iybOAd7TF1gc,1atPgoNSf7E,YCS Dortmund 2023 - Round 7 - Jordan G. vs. David E.,"Watch Round 7 of YCS Dortmund 2023: Jordan G. (Unchained) vs. David E. (Purrely)\n\nFacebook: https://facebook.com/YuGiOhCardEU\nTwitch: https://twitch.tv/YuGiOhCardEU\nTwitter: https://twitter.com/YuGiOhCardEU\nInstagram: https://www.instagram.com/YuGiOhCardEU\n \n2020 Studio Dice／SHUEISHA, TV TOKYO, KONAMI\nKonami Digital Entertainment\n\n\nBe sure to Subscribe to our Channel and hit the alert bell to know when a new video is available! \n \nStay up to date on Yu-Gi-Oh! TCG and Yu-Gi-Oh! Digital titles at http://www.yugioh-card.com\n \nFacebook: https://facebook.com/YuGiOhCardEU\nTwitch: https://twitch.tv/YuGiOhCardEU\nTwitter: https://twitter.com/YuGiOhCardEU\nInstagram: https://www.instagram.com/YuGiOhCardEU\n \n©2020 Studio Dice／SHUEISHA, TV TOKYO, KONAMI\n©Konami Digital Entertainment",YCS Dortmund,2023,YCS,Yu-Gi-Oh! Championship Series Dortmund 2023
807,fLEi4TJaEh4,False,None,None,None,None,None,None,PLIm0Rt8gzRbtsvJLX5Jz3_XP401RpPNw_,European Yu-Gi-Oh! Championship 2022,...,World Championship,2022,PLIm0Rt8gzRbtsvJLX5Jz3_XP401RpPNw_,fLEi4TJaEh4,Round 9 – Arthur Tarrieu vs. Alvaro Bonilla – European Yu-Gi-Oh! Championship 2022 – Day 1,"Round 9 – Arthur Tarrieu vs. Alvaro Bonilla – European Yu-Gi-Oh! Championship 2022 – Day 1 \n\nWatch the Livestream of European Yu-Gi-Oh! Championship 2022 (Day 1) here! \n \nFacebook: https://facebook.com/YuGiOhCardEU\nTwitch: https://twitch.tv/YuGiOhCardEU\nTwitter: https://twitter.com/YuGiOhCardEU\nInstagram: https://www.instagram.com/YuGiOhCardEU\n \n2020 Studio Dice／SHUEISHA, TV TOKYO, KONAMI\nKonami Digital Entertainment -- Watch live at https://www.twitch.tv/yugiohcardeu",EU World Championship Qualifer,2022,World Championship,European Yu-Gi-Oh! Championship 2022
824,hN-Z1KW_vZ4,False,None,None,None,None,None,None,PLIm0Rt8gzRbvQIL8kLAlzf2b1frm5P6jR,Yu-Gi-Oh! Championship Series in Ghent 2019,...,YCS,2019,PLIm0Rt8gzRbvQIL8kLAlzf2b1frm5P6jR,hN-Z1KW_vZ4,YCS Ghent 2019 - Round 9 - Alexandre Pousset vs. Marvin Schmidt (part2),Broadcasted live on Twitch -- Watch live at https://www.twitch.tv/officialyugiohchannel,YCS Ghent,2019,YCS,Yu-Gi-Oh! Championship Series in Ghent 2019
917,iBkzFXNTU4A,False,None,None,None,None,None,None,PLIm0Rt8gzRbuAOWpBz67KbSptL4l-ZEXl,YCS Dortmund 2022,...,YCS,2022,PLIm0Rt8gzRbuAOWpBz67KbSptL4l-ZEXl,iBkzFXNTU4A,YCS Dortmund 2022 - Round 12 - Lars J. vs. Piyal P.,"Watch the Round 12 match of YCS Dortmund 2022: Lars J. (Runick) vs. Piyal P. (Mystic Mine Burn) \n\nFacebook: [https://facebook.com/YuGiOhCardEU](https://facebook.com/YuGiOhCardEU) \n\nTwitch: [https://twitch.tv/YuGiOhCardEU](https://twitch.tv/YuGiOhCardEU) \n\nTwitter: [https://twitter.com/YuGiOhCardEU](https://twitter.com/YuGiOhCardEU) \n\nInstagram: [https://www.instagram.com/YuGiOhCardEU](https://www.instagram.com/YuGiOhCardEU) \n\n2020 Studio Dice／SHUEISHA, TV TOKYO, KONAMI \n\nKonami Digital Entertainment \n\n`` \n``",YCS Dortmund,2022,YCS,YCS Dortmund 2022
927,Kuv7dI12wCk,False,None,None,None,None,None,None,PLIm0Rt8gzRbuwoMC-m7OWUgD_Uuqt_5Km,YCS Sydney 2017 | Yu-Gi-Oh! Championship Series Sydney 2017 (175th YCS),...,YCS,2017,PLIm0Rt8gzRbuwoMC-m7OWUgD_Uuqt_5Km,Kuv7dI12wCk,YCS Sydney 2017: Round 6,"Footage recorded from Yu-Gi-Oh! Championship Series Sydney, held on January 14/15, 2017.\r\nRound 1 Feature Match: Liam Fardell vs. Jordan Westbroke\r\n\r\nYu-Gi-Oh! TRADING CARD GAME\r\n© 1996 Kazuki Takahashi\r\n© 2014 NAS • TV TOKYO\r\n\r\nWeb: www.yugioh-card.com\r\n\r\nFacebook: http://facebook.com/YuGiOhTCGEU\r\nTwitch: http://twitch.tv/OfficialYuGiOhChannel\r\n\r\nLive Event Coverage: www.yugioh-card.com/uk/live/\r\nEvent Blog: http://coverage.yugioh-card.com -- Watch live at https://www.twitch.tv/officialyugiohchannel -- Watch live at https://www.twitch.tv/officialyugiohchannel",YCS Sydney,2017,YCS,YCS Sydney 2017 | Yu-Gi-Oh! Championship Series Sydney 2017 (175th YCS)
984,fmYRTeBPil0,False,None,None,None,None,None,None,PLIm0Rt8gzRbu8eb7UBCPY8jMkWSIfY5lZ,YCS Melbourne 2018 | Yu-Gi-Oh! Championship Series Melbourne 2018 (January),...,YCS,2018,PLIm0Rt8gzRbu8eb7UBCPY8jMkWSIfY5lZ,fmYRTeBPil0,YCS Melbourne 2018: Top 16 Feature Match,"Footage recorded from YCS Melbourne 2017, held on January 13/14, 2018.\n\nRound 16 Feature Match: Ian Carroll (True King Dinosaur) vs. Matthew Casiero (Trickstars)\n \n Yu-Gi-Oh! TRADING CARD GAME\n © 1996 Kazuki Takahashi\n © 2014 NAS • TV TOKYO\n \n Web: www.yugioh-card.com\n \n Facebook: http://facebook.com/YuGiOhTCGEU\n Twitch: http://twitch.tv/OfficialYuGiOhChannel\n \n Live Event Coverage: www.yugioh-card.com/uk/live/\n Event Blog: http://coverage.yugioh-card.com",YCS Melbourne,2018,YCS,YCS Melbourne 2018 | Yu-Gi-Oh! Championship Series Melbourne 2018 (January)
1017,BZsAspc9j4E,False,None,None,None,None,None,None,PLIm0Rt8gzRbtlF-ldXXFmhRTym7L5yk23,2018 WCQ: UK National Championship,...,National Championship,2018,PLIm0Rt8gzRbtlF-ldXXFmhRTym7L5yk23,BZsAspc9j4E,2018 WCQ: National Championship - UK - Round 7 - Finn Bakewell vs Joe White,"Footage recorded from 2018 WCQ: UK National Championship in Birmingham, held on June 23/24, 2018.\nRound 6 Feature Match: Finn Bakewell (Pendulum Magician) vs. Joe White (Sky Striker)\n \n Yu-Gi-Oh! TRADING CARD GAME\n © 1996 Kazuki Takahashi\n © 2017 NAS • TV TOKYO\n \n Web: www.yugioh-card.com\n \n Facebook: http://facebook.com/YuGiOhTCGEU\n Twitch: http://twitch.tv/OfficialYuGiOhChannel\n \n Live Event Coverage: www.yugioh-card.com/uk/live/\n Event Blog: http://coverage.yugioh-card.com\n -- Watch live at https://www.twitch.tv/officialyugiohchannel",World Qualifying PointsUK National Championship,2018,National Championship,2018 WCQ: UK National Championship
1022,8BLTwWtCFrY,False,None,None,None,None,None,None,PLIm0Rt8gzRbvoTO6w4CBrg0uOJmsPZYMQ,Ultimate Time Wizard 2010 - YCS Bologna 2024,...,YCS,2010,PLIm0Rt8gzRbvoTO6w4CBrg0uOJmsPZYMQ,8BLTwWtCFrY,Round 1 - Plants vs Frog HERO - Ultimate Time Wizard 2010 YCS Bologna 2024,"For more information on the Time Wizard format and how to find your local tournaments, visit https://www.yugioh-card.com/eu/event/time-wizard/ \n\n\nBe sure to Subscribe to our Channel and hit the alert bell to know when a new video is available! \n \nStay up to date on Yu-Gi-Oh! TCG and Yu-Gi-Oh! Digital titles at http://www.yugioh-card.com\n \nFacebook: https://facebook.com/YuGiOhCardEU\nTwitch: https://twitch.tv/YuGiOhCardEU\nTwitter: https://twitter.com/YuGiOhCardEU\nInstagram: https://www.instagram.com/YuGiOhCardEU\n \n©2020 Studio Dice／SHUEISHA, TV TOKYO, KONAMI\n©Konami Digital Entertainment",YCS Bologna,2010,YCS,Ultimate Time Wizard 2010 - YCS Bologna 2024
1023,MYLGfhQpKtQ,False,None,None,None,None,None,None,PLIm0Rt8gzRbvoTO6w4CBrg0uOJmsPZYMQ,Ultimate Time Wizard 2010 - YCS Bologna 2024,...,YCS,2010,PLIm0Rt8gzRbvoTO6w4CBrg0uOJmsPZYMQ,MYLGfhQpKtQ,Round 2 - Lightsworn vs Chaos Fairy - Ultimate Time Wizard 2010 YCS Bologna 2024,"For more information on the Time Wizard format and how to find your local tournaments, visit https://www.yugioh-card.com/eu/event/time-wizard/ \n\nBe sure to Subscribe to our Channel and hit the alert bell to know when a new video is available! \n \nStay up to date on Yu-Gi-Oh! TCG and Yu-Gi-Oh! Digital titles at http://www.yugioh-card.com\n \nFacebook: https://facebook.com/YuGiOhCardEU\nTwitch: https://twitch.tv/YuGiOhCardEU\nTwitter: https://twitter.com/YuGiOhCardEU\nInstagram: https://www.instagram.com/YuGiOhCardEU\n \n©2020 Studio Dice／SHUEISHA, TV TOKYO, KONAMI\n©Konami Digital Entertainment",YCS Bologna,2010,YCS,Ultimate Time Wizard 2010 - YCS Bologna 2024
1024,zMHzZYiGc-A,False,None,None,None,None,None,None,PLIm0Rt8gzRbvoTO6w4CBrg0uOJmsPZYMQ,Ultimate Time Wizard 2010 - YCS Bologna 2024,...,YCS,2010,PLIm0Rt8gzRbvoTO6w4CBrg0uOJmsPZYMQ,zMHzZYiGc-A,Round 3 - Machina Gadget vs Blackwing - Ultimate Time Wizard 2010 YCS Bologna 2024,"For more information on the Time Wizard format and how to find your local tournaments, visit https://www.yugioh-card.com/eu/event/time-wizard/ \n\nBe sure to Subscribe to our Channel and hit the alert bell to know when a new video is available! \n \nStay up to date on Yu-Gi-Oh! TCG and Yu-Gi-Oh! Digital titles at http://www.yugioh-card.com\n \nFacebook: https://facebook.com/YuGiOhCardEU\nTwitch: https://twitch.tv/YuGiOhCardEU\nTwitter: https://twitter.com/YuGiOhCardEU\nInstagram: https://www.instagram.com/YuGiOhCardEU\n \n©2020 Studio Dice／SHUEISHA, TV TOKYO, KONAMI\n©Konami Digital Entertainment",YCS Bologna,2010,YCS,Ultimate Time Wizard 2010 - YCS Bologna 2024
1025,hiTuah0MugU,False,None,None,None,None,None,None,PLIm0Rt8gzRbvoTO6w4CBrg0uOJmsPZYMQ,Ultimate Time Wizard 2010 - YCS Bologna 2024,...,YCS,2010,PLIm0Rt8gzRbvoTO6w4CBrg0uOJmsPZYMQ,hiTuah0MugU,Round 4 - Machina Synchro vs Flamvell Frog - Ultimate Time Wizard 2010 YCS Bologna 2024,"For more information on the Time Wizard format and how to find your local tournaments, visit https://www.yugioh-card.com/eu/event/time-wizard/ \n\nBe sure to Subscribe to our Channel and hit the alert bell to know when a new video is available! \n \nStay up to date on Yu-Gi-Oh! TCG and Yu-Gi-Oh! Digital titles at http://www.yugioh-card.com\n \nFacebook: https://facebook.com/YuGiOhCardEU\nTwitch: https://twitch.tv/YuGiOhCardEU\nTwitter: https://twitter.com/YuGiOhCardEU\nInstagram: https://www.instagram.com/YuGiOhCardEU\n \n©2020 Studio Dice／SHUEISHA, TV TOKYO, KONAMI\n©Konami Digital Entertainment",YCS Bologna,2010,YCS,Ultimate Time Wizard 2010 - YCS Bologna 2024

In [171]:
pd.set_option("display.max_colwidth", 50)
keep_candidates[['Title', 'Video Description', 'Video ID']]

,Title,Video Description,Video ID
309,YCS Bologna 2024 - Round 5 - Christoph T. vs. ...,Watch Round 5 of YCS Bologna 2024: Christoph T...,6rhZfFY5ezc
326,YCS Birmingham 2025 - Round 9 - Manuel S. vs. ...,Watch Round 9 of YCS Birmingham 2025: Manuel S...,zEFYAFKMJRw
327,YCS Birmingham 2025 - Round 8 - Conor B. vs. E...,Watch Round 8 of YCS Birmingham 2025: Conor B....,AwWVkKpnBIQ
328,YCS Birmingham 2025 - Round 7 - Lochlann S. vs...,Watch Round 7 of YCS Birmingham 2025: Lochlann...,4zubx1TJgeo
329,YCS Birmingham 2025 - Round 6 - Jack Rory S. v...,Watch Round 6 of YCS Birmingham 2025: Jack Ror...,Bx7Ugk4_LWM
475,YCS London 2017: Round 11,"Footage recorded from Yu-Gi-Oh! YCS London, he...",FsT09iPtrYQ
508,2018 YCS London: Yu-Gi-Oh Championship Series ...,"Footage recorded from Yu-Gi-Oh! YCS London, he...",uLzecajpVXE
587,YCS Prague 2017: Top 16 Feature Match,"Footage recorded from YCS Prague 2017, held on...",slTQ8z-g9iY
593,YCS London: Round 3 Feature Match,Footage recorded from Yu-Gi-Oh! Championship S...,EO15MEh2F7g
594,YCS London: Round 4 Feature Match,Footage recorded from Yu-Gi-Oh! Championship S...,-ZHQxKRwH4g
607,YCS Prague: Round 3 Feature Match,Yu-Gi-Oh! TRADING CARD GAME\r\n© 1996 Kazuki T...,u8oYhIA313k
633,2018 Yu-Gi-Oh! TCG World Championship - 3rd Pl...,Broadcasted live on Twitch -- Watch live at ht...,1ABWYJfRpAY
645,2016 WCQ: UK National | Top 64,-- Watch live at https://www.twitch.tv/officia...,HbxQcpYZiV0
667,YCS Rimini 2017: Round 7,Footage recorded from Yu-Gi-Oh! YCS Rimini 201...,wunWpXa-0iM
726,YCS Utrecht 2020 - Round 7 - Eike Ruting vs. D...,🇳🇱Livestream #YCSUtrecht 🇳🇱\nHere we are again...,JhwkFMPxClY
767,YCS Bologna 2023 - Top 64 - Joo-Ho A. vs. Emil...,Watch the Top 64 match of YCS Bologna 2023: Jo...,NSZhaNU7KHc
794,YCS Dortmund 2023 - Round 7 - Jordan G. vs. Da...,Watch Round 7 of YCS Dortmund 2023: Jordan G. ...,1atPgoNSf7E
807,Round 9 – Arthur Tarrieu vs. Alvaro Bonilla – ...,Round 9 – Arthur Tarrieu vs. Alvaro Bonilla – ...,fLEi4TJaEh4
824,YCS Ghent 2019 - Round 9 - Alexandre Pousset v...,Broadcasted live on Twitch -- Watch live at ht...,hN-Z1KW_vZ4
917,YCS Dortmund 2022 - Round 12 - Lars J. vs. Piy...,Watch the Round 12 match of YCS Dortmund 2022:...,iBkzFXNTU4A
927,YCS Sydney 2017: Round 6,Footage recorded from Yu-Gi-Oh! Championship S...,Kuv7dI12wCk
984,YCS Melbourne 2018: Top 16 Feature Match,"Footage recorded from YCS Melbourne 2017, held...",fmYRTeBPil0
1017,2018 WCQ: National Championship - UK - Round 7...,Footage recorded from 2018 WCQ: UK National Ch...,BZsAspc9j4E
1022,Round 1 - Plants vs Frog HERO - Ultimate Time ...,For more information on the Time Wizard format...,8BLTwWtCFrY
1023,Round 2 - Lightsworn vs Chaos Fairy - Ultimate...,For more information on the Time Wizard format...,MYLGfhQpKtQ
1024,Round 3 - Machina Gadget vs Blackwing - Ultima...,For more information on the Time Wizard format...,zMHzZYiGc-A
1025,Round 4 - Machina Synchro vs Flamvell Frog - U...,For more information on the Time Wizard format...,hiTuah0MugU
1026,Round 5 - Blackwing vs Frog Monarch - Ultimate...,For more information on the Time Wizard format...,Wu3OtvgfyMg
1027,Round 6 - Gladiator Beast vs Gladiator Beast -...,For more information on the Time Wizard format...,Hvs3AmcZ8-4
1227,"2025 North America YCS Providence, RI // Round...",Swiss Round 5 Match replay from 2025 YCS Provi...,iAXWdhX6520
1355,Yu Gi Oh! Remote Duel Invitational - TCG: Day ...,Gage Poljak (USA) vs Ryan Yu (Canada),MjBeOAdEWdM
1356,Yu Gi Oh! Remote Duel Invitational - TCG: Day ...,Blair Hunter (USA) vs. Ryan Levine (USA),RJDej8ylczo

In [67]:
import pandas as pd

stage6 = pd.read_parquet("pipeline/checkpoints/stage6_matches.parquet")
# stage6['Title'].unique()
# This safely ignores any rows where Title is missing/None
casters_df = stage6[stage6['Title'].str.contains('Caster', case=False, na=False)]
print(casters_df[['Title', 'is_match']])

Empty DataFrame
Columns: [Title, is_match]
Index: []

In [65]:
stage6[stage6['is_match'] == False]['Title'].unique()

array([], dtype=object)