# Basic setup to get all playlists of the YGO Card EU channel

In [283]:
import pandas as pd
from googleapiclient.discovery import build
from googleapiclient.errors import HttpError

# 1. SETUP CONFIGURATION
# Make sure to replace this with your actual key from the Google Cloud Console
API_KEY = os.getenv("YOUTUBE_API_KEY")
HANDLE = "@YuGiOhCardEU"

# 2. DEFINE LOGIC FUNCTIONS
def get_channel_id_via_api(youtube, handle):
    """Uses the official YouTube API search method to securely resolve a handle 
    into an absolute Channel ID (UC...).
    """
    try:
        response = youtube.search().list(
            q=handle,
            type="channel",
            part="id,snippet",
            maxResults=1
        ).execute()
        
        items = response.get("items", [])
        if not items:
            print(f"Error: Could not find channel with handle: {handle}")
            return None
            
        channel_id = items[0]["id"]["channelId"]
        channel_title = items[0]["snippet"]["title"]
        print(f"Successfully connected to: '{channel_title}'")
        return channel_id
        
    except HttpError as e:
        print(f"An API error occurred while looking up the handle: {e}")
        return None

def fetch_all_playlists(youtube, channel_id):
    """Iterates through all pages of playlists using the YouTube Data API."""
    playlists = []
    next_page_token = None
    
    while True:
        try:
            response = youtube.playlists().list(
                channelId=channel_id,
                part="snippet,contentDetails",
                maxResults=50,
                pageToken=next_page_token
            ).execute()
            
            for item in response.get("items", []):
                playlists.append({
                    "Playlist Title": item["snippet"]["title"],
                    "Video Count": item["contentDetails"]["itemCount"],
                    "Playlist ID": item["id"]
                })
            next_page_token = response.get("nextPageToken")
            if not next_page_token:
                break
        except HttpError as e:
            print(f"An API error occurred while downloading lists: {e}")
            break
    return playlists

# Fetch all playlists into a dataframe

In [284]:
youtube = build("youtube", "v3", developerKey=os.getenv("YOUTUBE_API_KEY"))

channel_id = get_channel_id_via_api(youtube, HANDLE)

if channel_id:
    print(f"Channel ID confirmed as {channel_id}. Fetching playlist data...")
    data = fetch_all_playlists(youtube, channel_id)
    df = pd.DataFrame(data)
    print(f"Done! Extracted {len(df)} total playlists.\n")
    
    pd.set_option('display.max_rows', None)
    pd.set_option('display.max_colwidth', None)
    
    # Renders the table visually beneath the cell
    display(df) 
else:
    print("Execution halted: Unable to determine Channel ID.")

Successfully connected to: 'YuGiOhCardEU'
Channel ID confirmed as UCvjX8v8KMcLToVxKLjDNSVg. Fetching playlist data...
Done! Extracted 132 total playlists.

,Playlist Title,Video Count,Playlist ID
0,Yu-Gi-Oh! TCG | Battles of Legend: Glorious Gallery Unboxing Series,22,PLIm0Rt8gzRbskxI-lI7pC0klGQw5FLGBI
1,Yu-Gi-Oh! TCG | Blazing Dominion Unboxing Series,22,PLIm0Rt8gzRbtYPRjkHV_z8WgY1I42EJdc
2,Yu-Gi-Oh! Rarity Collection,4,PLIm0Rt8gzRbv2hsmR9PrFpmOlwSKVDArh
3,Yu-Gi-Oh! TCG Rarity Collection 5 Reveals!,21,PLIm0Rt8gzRbuQw2N4O0oOvc5gOnPUO8dz
4,Yu-Gi-Oh! MASTER DUEL EU Challenger Cup Final Paris 2026,2,PLIm0Rt8gzRbuomctdTErxkiYT6zPT07GZ
5,YCS Dortmund 2026,41,PLIm0Rt8gzRbs70xRsspnrAuR1qgUDXl4e
6,Yu-Gi-Oh! TCG Burst Protocol Reveals!,19,PLIm0Rt8gzRbu8mVV-2QrsgpJr-uX0Zgg6
7,Yu-Gi-Oh! DUEL LINKS,16,PLIm0Rt8gzRbt6U_yEBFCIXcPTWOfopKkK
8,THE CHRONICLES DECK: Spirit Charmers (All-Foil Edition),16,PLIm0Rt8gzRbu84BuZvx-VrDEZEJV6ODcU
9,Yu-Gi-Oh! CARD GAME THE CHRONICLES,12,PLIm0Rt8gzRbunisv8ir7jZl-KCmf6MHQE
10,Yu-Gi-Yoh! Phantom Revenge!,3,PLIm0Rt8gzRbu-ZcWapkK4eyk-491gveKK
11,Yu-Gi-Oh! TCG Phantom Revenge Reveals!,20,PLIm0Rt8gzRbsFyPAdZvrpHiVMp-62F57f
12,Yu-Gi-Yoh! 5Ds,7,PLIm0Rt8gzRbtwxDEtP1UPaN8ayoawiHd9
13,YCS Bologna 2025,46,PLIm0Rt8gzRbuI3ij0C4yrfAQb8tMbtCt8
14,Yu-Gi-Oh! TCG Retro Pack 2 Reveals!,17,PLIm0Rt8gzRbv27-JwibmDyA4UNCfQ7kVa
15,The Chronicles Deck: The Fallen & The Virtuous (All-Foil Edition)!,5,PLIm0Rt8gzRbtVa7bmoCOgnNeaR5aq1TBW
16,Doom of Dimensions,4,PLIm0Rt8gzRbuG7SGLGhg4Gd99RlYJUKlq
17,Yu-Gi-Oh! TCG Legendary 5D's Decks Reveals!,16,PLIm0Rt8gzRbs-HKZFDT-QIF6LAl2OEZpw
18,YCS Lille 2025,38,PLIm0Rt8gzRbvpM61P9xfJEZoU558nP7Hw
19,Yu-Gi-Oh! TCG Doom of Dimensions Reveals!,19,PLIm0Rt8gzRbvrE7BWf7lHzUZEn0GDCykU
20,"Yu-Gi-Oh! World Championship 2025 - Paris, France",44,PLIm0Rt8gzRbvUqBmSmnIEr9nTIFuqAW_F
21,Yu-Gi-Oh! World Championship Qualifier Berlin 2025,29,PLIm0Rt8gzRbtzFNzn1ayewRiNuwNekWsq
22,Yu-Gi-Oh! TCG Justice Hunters - Box Openings,16,PLIm0Rt8gzRbsT11fGdKMuiV9PQDu8kloW
23,Duelist's Advance,7,PLIm0Rt8gzRbuENspsf7xSYy-Zv5Aa_Lgg
24,Yu-Gi-Oh! TCG Alliance Insight Reveals!,31,PLIm0Rt8gzRbuGxYZyVn9l_ZBwquNBkT4U
25,Quarter Century Memories | Quarter Century Stampede,17,PLIm0Rt8gzRbv9KkM_BkVYQYzx_PRpIOF1
26,Ultimate Time Wizard 2010 Format - YCS Birmingham 2025,9,PLIm0Rt8gzRbvP8EGZykEEQIzaZ2gK8FSF
27,Yu-Gi-Oh! Quarter Century Stampede - Box Openings!,22,PLIm0Rt8gzRbuYrWDSTGXHnc5XNconVoOX
28,Maze of the Master,6,PLIm0Rt8gzRbv1ItNHEErzel8lY__U2iod
29,Structure Deck: Blue-Eyes White Destiny,11,PLIm0Rt8gzRbu0EFqo1l30VdzKc9F4sG_N
30,Yu-Gi-Oh! DUEL LINKS | Create The Links,8,PLIm0Rt8gzRbvt4tmUgHeehM0ihmYZGTs-
31,YCS Birmingham 2025,37,PLIm0Rt8gzRbuSa9zamQ9XAqfN9f5wa0IM
32,Ultimate Time Wizard 2010 - YCS Bologna 2024,11,PLIm0Rt8gzRbvoTO6w4CBrg0uOJmsPZYMQ
33,Yu-Gi-Oh! TCG Italian OPEN January 2025,9,PLIm0Rt8gzRbs0QeJ5UPKUXEMJ126KNK-b
34,Crossover Breakers,4,PLIm0Rt8gzRbsIbYRMqgJgLCN-VZKOA-IA
35,YCS Bologna 2024,38,PLIm0Rt8gzRbtnbZYH99PGTqCWtR6WZS77
36,Quarter Century Memories | Quarter Century Bonanza,8,PLIm0Rt8gzRbtk5lobTvITTrnO1kV-3doF
37,Yu-Gi-Oh! World Championship Series 2024,6,PLIm0Rt8gzRbvlG2IvMeWgyI8VNEMLnuQ_
38,275th Yu-Gi-Oh! Championship Series Lille 2024,36,PLIm0Rt8gzRbsro5ChBPW-Jv8q2Potz2ll
39,Yu-Gi-Oh! World Championship Qualifier Berlin 2024,29,PLIm0Rt8gzRbsuyvjSAe5Zf9_CxIvEqsH2
40,Yu-Gi-Oh! TCG Italian OPEN May 2024,9,PLIm0Rt8gzRbs9Msm9739PwTwCyMExCrdD
41,Yu-Gi-Oh! TCG Greek OPEN April 2024,9,PLIm0Rt8gzRbu0W_Ov0RLECOx8ZW6mIEKp
42,Yu-Gi-Oh! Card EU Master Duel 2nd Anniversary Invitational,11,PLIm0Rt8gzRbvSiy-roaJDq1kpG_HQd3Zm
43,Yu-Gi-Oh! Card Game The Chronicles,8,PLIm0Rt8gzRbuMU4AwY2A0OtG8i6uenVcs
44,Yu-Gi-Oh! DUEL LINKS | Rival School Academy,10,PLIm0Rt8gzRbvG8XIZew6F6stnXplgJ-48
45,Deck Combo Tutorials,4,PLIm0Rt8gzRbtvMXnXkRn-9gDEjSld8yLu
46,Dueling Chronicles,2,PLIm0Rt8gzRbsLHylHEZzMqOMhukkXxDGK
47,Yu-Gi-Oh! Championship Series Bologna 2023,20,PLIm0Rt8gzRbs_jPCYppMNC7TOCuibkYgy
48,Yu-Gi-Oh! TCG - Yu-Gi-Oh! para Principiantes (PT),13,PLIm0Rt8gzRbsu9f95DSg3dZrCsGvdm_qv
49,Yu-Gi-Oh! TCG - Yu-Gi-Oh! per Principianti (IT),13,PLIm0Rt8gzRbtIp_cjWWx7zgV1Kz6pf43y
50,Yu-Gi-Oh! TCG - Yu-Gi-Oh! para Principiantes (ES),13,PLIm0Rt8gzRbuaP67KOxmgGDsEOT73Z5Zc
51,Yu-Gi-Oh! TCG - Yu-Gi-Oh! für Einsteiger (DE),13,PLIm0Rt8gzRbtETpCJAxx6EMXI47fUDcsN
52,Yu-Gi-Oh! TCG - Yu-Gi-Oh! pour les Débutants (FR),13,PLIm0Rt8gzRbuGv7z4SZtsKgjFnU1FC1BQ
53,Yu-Gi-Oh! TCG - Yu-Gi-Oh! For Beginners (EN),13,PLIm0Rt8gzRbuNTdzYNQbdlOOLJFLjcJYM
54,Master vs. Caster,8,PLIm0Rt8gzRbvcx1d-4KR3m9d9yqh-dDyx
55,Yu-Gi-Oh! Championship Series Dortmund 2023,20,PLIm0Rt8gzRbsWWG_zEMA3iybOAd7TF1gc
56,2023 World Qualifying Points Play Off,8,PLIm0Rt8gzRbuNH6poINGjyPLRdN1J7DRz
57,2023 European World Championship Qualifier,21,PLIm0Rt8gzRbsGUTXNC05ktSQ_DbPLG0dL
58,2023 Yu-Gi-Oh! TRADING CARD GAME Product Highlights,11,PLIm0Rt8gzRbsFFNWto80HjFYUJdUx0tS7
59,YCS London 2023,20,PLIm0Rt8gzRbvYDhxLPDUyBVNNPme534Pv
60,YCS Lyon 2023,21,PLIm0Rt8gzRbsZ9pAhcQcggxgkcWsWZGni
61,Yu-Gi-Oh! MASTER DUEL Invitational Paris 2022,25,PLIm0Rt8gzRbuPuoI8LN9UCIYXcH1l2isD
62,YCS Dortmund 2022,18,PLIm0Rt8gzRbuAOWpBz67KbSptL4l-ZEXl
63,YCS Utrecht 2022,18,PLIm0Rt8gzRbv6leYtBwsne1gGpiwbP9Yh
64,Yu-Gi-Oh! CROSS DUEL,6,PLIm0Rt8gzRbuEvtsPaxFm6kM85CtRhGBs
65,European Yu-Gi-Oh! Championship 2022,20,PLIm0Rt8gzRbtsvJLX5Jz3_XP401RpPNw_
66,2022 Yu-Gi-Oh! TRADING CARD GAME Product Highlights,4,PLIm0Rt8gzRbuQvfvv8V-D-n0lZ6K9m1z_
67,Yu-Gi-Oh! MASTER DUEL,37,PLIm0Rt8gzRbuHVKmtnhFLdkE1ElkiXekn
68,Yu-Gi-Oh! DUEL LINKS,18,PLIm0Rt8gzRburd-DtJlSj9NE_AVcdBHlk
69,2021 Yu-Gi-Oh! TRADING CARD GAME Product Highlights,12,PLIm0Rt8gzRbsVvj4-sE-zyL4PRdf2YqYk
70,Remote Duel,88,PLIm0Rt8gzRbtaQCNw84Le39m75QYtpjJ9
71,Yu-Gi-Oh! Remote Duel Invitational 5 (Remote Duel Season 3),21,PLIm0Rt8gzRbsRKpusSYDHsLP3yIlehQM3
72,Remote Duel Yu-Gi-Oh! Championship Series 2021 – Top 8,7,PLIm0Rt8gzRbtMPDnLGYFII_tUVnRM5ScA
73,Yu-Gi-Oh! Remote Duel Invitational 4 (Remote Duel Season 2),15,PLIm0Rt8gzRbvbxSjb2KobHUdvi0aN3sNO
74,Yu-Gi-Oh! Remote Duel Invitational 4 (Remote Duel Season 1),15,PLIm0Rt8gzRbss2eTqtH1_AUk2oei6Gcfw
75,Yu-Gi-Oh! Remote Duel Invitational 2,18,PLIm0Rt8gzRbtvMHY4kexPXDZbuuhBQcFu
76,Yu-Gi-Oh! Remote Duel Invitational,14,PLIm0Rt8gzRbtTpkic6LD37Bnj4lTTZnqa
77,Livestream 5D's Marathon,1,PLIm0Rt8gzRbuUsS2uYvEbl2GU970TIArZ
78,"YCS Utrecht 2020 | Interviews, Mini Games and more",20,PLIm0Rt8gzRbufJIgY8WiTdsrG93HxD0bq
79,YCS Utrecht 2020 | Yu-Gi-Oh! Championship Series Utrecht 2020,20,PLIm0Rt8gzRbuO5Y9S6sLDEcy9ceIQpkHB
80,Yu-Gi-Oh! Championship Series in Milan 2019,18,PLIm0Rt8gzRbubZdC-3nwjMmf4XnBa3XcX
81,Yu-Gi-Oh! Championship Series in London 2019,19,PLIm0Rt8gzRbt26wj5dH1-p7JP9PjmWFin
82,Yu-Gi-Oh! Championship Series in Ghent 2019,19,PLIm0Rt8gzRbvQIL8kLAlzf2b1frm5P6jR
83,Yu-Gi-Oh! World Championship 2019 - Berlin,7,PLIm0Rt8gzRbsxRacuVerQ4REzU6zRQFXt
84,YCS Düsseldorf 2019 | Yu-Gi-Oh! Championship Series Düsseldorf 2019,40,PLIm0Rt8gzRbue3Nu1Xy67JzYHUGRFFCSR
85,YCS Sydney 2019 | Yu-Gi-Oh! Championship Series Sydney 2019,17,PLIm0Rt8gzRburNEkrpAZchPkgIHfvOhYf
86,YCS Milan 2018 | Yu-Gi-Oh! Championship Series Milan 2018,50,PLIm0Rt8gzRbvNmWVsRbgwdxXWcX1EXxh0
87,YCS London 2018 | Yu-Gi-Oh! Championship Series London 2018,29,PLIm0Rt8gzRbvdbAcXuDGBPDQ24dW5wjKc
88,YCS Utrecht 2018 | 200th YCS | Yu-Gi-Oh! Championship Series Utrecht 2018,20,PLIm0Rt8gzRburE-D3lYnL5QL6INZRSHn2
89,2018 Yu-Gi-Oh! Duel Links World Championship,8,PLIm0Rt8gzRbuqtZFz-Sv7x1li19vA-ynQ
90,2018 Yu-Gi-Oh! TCG Dragon Duel World Championship,7,PLIm0Rt8gzRbuauJOWCGiWGDMbOrK_4lZz
91,2018 Yu-Gi-Oh! TCG World Championship,10,PLIm0Rt8gzRbvqW-711158U4fL3Mk_aZCh
92,2018 Yu-Gi-Oh! World Championship,23,PLIm0Rt8gzRbsNALbcx6KJ8V5a2-mYLUCn
93,Yu-Gi-Oh! Duel Links Exhibition (Berlin 2018),6,PLIm0Rt8gzRbsrzBk8WJ6xP20ZMFdfftsg
94,2018 WCQ: European Championship,39,PLIm0Rt8gzRbuLKQ294o73x9SXXT4S-8IO
95,2018 WCQ: UK National Championship,11,PLIm0Rt8gzRbtlF-ldXXFmhRTym7L5yk23
96,YCS Bochum 2018 | Yu-Gi-Oh! Championship Series Bochum 2018,78,PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl
97,Structure Deck: Wave of Light,3,PLIm0Rt8gzRbsJcIE7xs9oIYb9snDdlUxt
98,2018 WCQ - UK Open - London II,10,PLIm0Rt8gzRbtV4YAMY-tqJL3Ov2LMki68
99,YCS Melbourne 2018 | Yu-Gi-Oh! Championship Series Melbourne 2018 (January),15,PLIm0Rt8gzRbu8eb7UBCPY8jMkWSIfY5lZ
100,YCS Prague 2017 | Yu-Gi-Oh! Championship Series Prague 2017 (November),28,PLIm0Rt8gzRbvOLxLL69WsUn1Q6jwbpDRo
101,LLDS 2017 | 2017 Local Legend Duelist Series Finals,6,PLIm0Rt8gzRbt3WiPDuWk38Tzmgqh1zz6I
102,YCS London 2017 | Yu-Gi-Oh! Championship Series London 2017,32,PLIm0Rt8gzRbvARnj3qZUwXVaN3WLiZu-G
103,YCS Rimini 2017 | Yu-Gi-Oh! Championship Series Rimini 2017,21,PLIm0Rt8gzRbviW3duevd3e3C1QjalKtlj
104,2017 Yu-Gi-Oh! TRADING CARD GAME World Championship,13,PLIm0Rt8gzRbtF0raJMkgb_AVj7Kyqnwn7
105,Yu-Gi-Oh! TCG Tutorials,27,PLIm0Rt8gzRbtyBoer1V0UpUv9_7XkWq-W
106,2017 WCQ: EC | 2017 WCQ: European Championship,54,PLIm0Rt8gzRbsHq8NXVNrIejQoUN3nMFfo
107,2017 WCQ: UK National Championship,32,PLIm0Rt8gzRbtzapH_8KLPAehZVrHsALMR
108,[DE] 2017 WCQ: German National Championship,37,PLIm0Rt8gzRbutxiGy8fJI0W3m4bcGg3-j
109,[ES] 2017 WCQ: Spanish National Championship,11,PLIm0Rt8gzRbsKkfRBUEAtYDGBlH8fVkud
110,YCS Prague 2017 | Yu-Gi-Oh! Championship Series Prague 2017,33,PLIm0Rt8gzRbvQIZ4LdDzsQcg05qD5-AfI
111,YCS Sydney 2017 | Yu-Gi-Oh! Championship Series Sydney 2017 (175th YCS),17,PLIm0Rt8gzRbuwoMC-m7OWUgD_Uuqt_5Km
112,YCS Bochum 2016 | Yu-Gi-Oh! Championship Series Bochum 2016,32,PLIm0Rt8gzRbsCXQnGZVhu2Acnfbi43uk6
113,[DE] LLDS Kassel | 2016 Yu-Gi-Oh! TCG Local Legend Duelist Series (Germany),21,PLIm0Rt8gzRbtQWmvz_D1i4J656FlLqPWi
114,YCS Liverpool 2016 | Yu-Gi-Oh! Championship Series Liverpool 2016,32,PLIm0Rt8gzRbtPVaqIwILHqX2YvVk54upH
115,YCS Rimini 2016 | Yu-Gi-Oh! Championship Series Rimini 2016,34,PLIm0Rt8gzRbus2XHbGg1A0qef58bLUg9W
116,WCQ: EC2016 | 2016 WCQ: European Championship,57,PLIm0Rt8gzRbvYYuWPcfcb1ZNQLCoPT5vm
117,Yu-Gi-Oh! TCG | TV Commercials,3,PLIm0Rt8gzRbvx9LU3AitXXy81KW-xNKZZ
118,2016 WCQ: UK National Championship,22,PLIm0Rt8gzRbsidpr96G4FFXf9GvdMh-lB
119,2016 WCQ: German National Championship,16,PLIm0Rt8gzRbtCvzE6j2-6uD5cfNqnIVw2
120,2015 WCQ: National Champion Interviews,14,PLIm0Rt8gzRbu6hF2h0RBMnuLQpzHDEQeY
121,YCS Prague 2016 | Yu-Gi-Oh! Championship Series Prague 2016,25,PLIm0Rt8gzRbtuya5V5H6zeKwIlmbwyunI
122,YCS Rimini | Yu-Gi-Oh! Championship Series Rimini 2015,28,PLIm0Rt8gzRbsmNqbYBR6ET0v82YLHs-Pk
123,Yu-Gi-Oh! Videogames,51,PLIm0Rt8gzRbuNHjK3hPn7QgjSxV4JkOrs
124,YCS London | Yu-Gi-Oh! Championship Series London,28,PLIm0Rt8gzRbsM_eU_TVTTh8GJPA1ZCF0Z
125,WCQ: EC2014 | Yu-Gi-Oh! TCG WCQ: European Championship 2014,1,PLIm0Rt8gzRbtTio1RMkWdRH9bkRNmX-Gh
126,WCS 2014 | 2014 Yu-Gi-Oh! TCG World Championship,13,PLIm0Rt8gzRbuBwwHoazOzCj6s3_67kj8e
127,YCS Madrid | Yu-Gi-Oh! Championship Series Madrid,16,PLIm0Rt8gzRbtE1wXv0kUYBP4GeNUnpFdg
128,YCS Milan | Yu-Gi-Oh! Championship Series Milan,18,PLIm0Rt8gzRbu5uULuK4WArO6Ii3VRo12L
129,YCS Prague | Yu-Gi-Oh! Championship Series Prague,32,PLIm0Rt8gzRbu5rDW3wVN5G_Zcg_G53RB9
130,WCQ: EC2015 | 2015 Yu-Gi-Oh! TCG WCQ: European Championship,60,PLIm0Rt8gzRbss2nX1mixsDYj4CpmZ8ugW
131,YCS Bochum | Yu-Gi-Oh! Championship Series Bochum,38,PLIm0Rt8gzRbudSiIYYy2neWhQqecruQNU

# Filter tournaments by phrases

In [83]:
TARGET_PHRASES = ["YCS", "Championship", "WCQ", "National", "Open"]
strict_regex = "|".join([rf"\b{word}\b" for word in TARGET_PHRASES])
filtered_df = df[df["Playlist Title"].str.contains(strict_regex, case=False, na=False)]

print(f"--- Found {len(filtered_df)} playlists matching your target tournament phrases ---")
filtered_df = filtered_df.sort_values(by="Video Count", ascending=False)
display(filtered_df)

--- Found 71 playlists matching your target tournament phrases ---

,Playlist Title,Video Count,Playlist ID
96,YCS Bochum 2018 | Yu-Gi-Oh! Championship Series Bochum 2018,78,PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl
130,WCQ: EC2015 | 2015 Yu-Gi-Oh! TCG WCQ: European Championship,60,PLIm0Rt8gzRbss2nX1mixsDYj4CpmZ8ugW
116,WCQ: EC2016 | 2016 WCQ: European Championship,57,PLIm0Rt8gzRbvYYuWPcfcb1ZNQLCoPT5vm
106,2017 WCQ: EC | 2017 WCQ: European Championship,54,PLIm0Rt8gzRbsHq8NXVNrIejQoUN3nMFfo
86,YCS Milan 2018 | Yu-Gi-Oh! Championship Series Milan 2018,50,PLIm0Rt8gzRbvNmWVsRbgwdxXWcX1EXxh0
13,YCS Bologna 2025,46,PLIm0Rt8gzRbuI3ij0C4yrfAQb8tMbtCt8
20,"Yu-Gi-Oh! World Championship 2025 - Paris, France",44,PLIm0Rt8gzRbvUqBmSmnIEr9nTIFuqAW_F
5,YCS Dortmund 2026,41,PLIm0Rt8gzRbs70xRsspnrAuR1qgUDXl4e
84,YCS Düsseldorf 2019 | Yu-Gi-Oh! Championship Series Düsseldorf 2019,40,PLIm0Rt8gzRbue3Nu1Xy67JzYHUGRFFCSR
94,2018 WCQ: European Championship,39,PLIm0Rt8gzRbuLKQ294o73x9SXXT4S-8IO
18,YCS Lille 2025,38,PLIm0Rt8gzRbvpM61P9xfJEZoU558nP7Hw
131,YCS Bochum | Yu-Gi-Oh! Championship Series Bochum,38,PLIm0Rt8gzRbudSiIYYy2neWhQqecruQNU
35,YCS Bologna 2024,38,PLIm0Rt8gzRbtnbZYH99PGTqCWtR6WZS77
31,YCS Birmingham 2025,37,PLIm0Rt8gzRbuSa9zamQ9XAqfN9f5wa0IM
108,[DE] 2017 WCQ: German National Championship,37,PLIm0Rt8gzRbutxiGy8fJI0W3m4bcGg3-j
38,275th Yu-Gi-Oh! Championship Series Lille 2024,36,PLIm0Rt8gzRbsro5ChBPW-Jv8q2Potz2ll
115,YCS Rimini 2016 | Yu-Gi-Oh! Championship Series Rimini 2016,34,PLIm0Rt8gzRbus2XHbGg1A0qef58bLUg9W
110,YCS Prague 2017 | Yu-Gi-Oh! Championship Series Prague 2017,33,PLIm0Rt8gzRbvQIZ4LdDzsQcg05qD5-AfI
102,YCS London 2017 | Yu-Gi-Oh! Championship Series London 2017,32,PLIm0Rt8gzRbvARnj3qZUwXVaN3WLiZu-G
112,YCS Bochum 2016 | Yu-Gi-Oh! Championship Series Bochum 2016,32,PLIm0Rt8gzRbsCXQnGZVhu2Acnfbi43uk6
114,YCS Liverpool 2016 | Yu-Gi-Oh! Championship Series Liverpool 2016,32,PLIm0Rt8gzRbtPVaqIwILHqX2YvVk54upH
107,2017 WCQ: UK National Championship,32,PLIm0Rt8gzRbtzapH_8KLPAehZVrHsALMR
129,YCS Prague | Yu-Gi-Oh! Championship Series Prague,32,PLIm0Rt8gzRbu5rDW3wVN5G_Zcg_G53RB9
39,Yu-Gi-Oh! World Championship Qualifier Berlin 2024,29,PLIm0Rt8gzRbsuyvjSAe5Zf9_CxIvEqsH2
21,Yu-Gi-Oh! World Championship Qualifier Berlin 2025,29,PLIm0Rt8gzRbtzFNzn1ayewRiNuwNekWsq
87,YCS London 2018 | Yu-Gi-Oh! Championship Series London 2018,29,PLIm0Rt8gzRbvdbAcXuDGBPDQ24dW5wjKc
124,YCS London | Yu-Gi-Oh! Championship Series London,28,PLIm0Rt8gzRbsM_eU_TVTTh8GJPA1ZCF0Z
122,YCS Rimini | Yu-Gi-Oh! Championship Series Rimini 2015,28,PLIm0Rt8gzRbsmNqbYBR6ET0v82YLHs-Pk
100,YCS Prague 2017 | Yu-Gi-Oh! Championship Series Prague 2017 (November),28,PLIm0Rt8gzRbvOLxLL69WsUn1Q6jwbpDRo
121,YCS Prague 2016 | Yu-Gi-Oh! Championship Series Prague 2016,25,PLIm0Rt8gzRbtuya5V5H6zeKwIlmbwyunI
92,2018 Yu-Gi-Oh! World Championship,23,PLIm0Rt8gzRbsNALbcx6KJ8V5a2-mYLUCn
118,2016 WCQ: UK National Championship,22,PLIm0Rt8gzRbsidpr96G4FFXf9GvdMh-lB
103,YCS Rimini 2017 | Yu-Gi-Oh! Championship Series Rimini 2017,21,PLIm0Rt8gzRbviW3duevd3e3C1QjalKtlj
60,YCS Lyon 2023,21,PLIm0Rt8gzRbsZ9pAhcQcggxgkcWsWZGni
57,2023 European World Championship Qualifier,21,PLIm0Rt8gzRbsGUTXNC05ktSQ_DbPLG0dL
59,YCS London 2023,20,PLIm0Rt8gzRbvYDhxLPDUyBVNNPme534Pv
79,YCS Utrecht 2020 | Yu-Gi-Oh! Championship Series Utrecht 2020,20,PLIm0Rt8gzRbuO5Y9S6sLDEcy9ceIQpkHB
78,"YCS Utrecht 2020 | Interviews, Mini Games and more",20,PLIm0Rt8gzRbufJIgY8WiTdsrG93HxD0bq
88,YCS Utrecht 2018 | 200th YCS | Yu-Gi-Oh! Championship Series Utrecht 2018,20,PLIm0Rt8gzRburE-D3lYnL5QL6INZRSHn2
55,Yu-Gi-Oh! Championship Series Dortmund 2023,20,PLIm0Rt8gzRbsWWG_zEMA3iybOAd7TF1gc
47,Yu-Gi-Oh! Championship Series Bologna 2023,20,PLIm0Rt8gzRbs_jPCYppMNC7TOCuibkYgy
65,European Yu-Gi-Oh! Championship 2022,20,PLIm0Rt8gzRbtsvJLX5Jz3_XP401RpPNw_
81,Yu-Gi-Oh! Championship Series in London 2019,19,PLIm0Rt8gzRbt26wj5dH1-p7JP9PjmWFin
82,Yu-Gi-Oh! Championship Series in Ghent 2019,19,PLIm0Rt8gzRbvQIL8kLAlzf2b1frm5P6jR
80,Yu-Gi-Oh! Championship Series in Milan 2019,18,PLIm0Rt8gzRbubZdC-3nwjMmf4XnBa3XcX
128,YCS Milan | Yu-Gi-Oh! Championship Series Milan,18,PLIm0Rt8gzRbu5uULuK4WArO6Ii3VRo12L
62,YCS Dortmund 2022,18,PLIm0Rt8gzRbuAOWpBz67KbSptL4l-ZEXl
63,YCS Utrecht 2022,18,PLIm0Rt8gzRbv6leYtBwsne1gGpiwbP9Yh
85,YCS Sydney 2019 | Yu-Gi-Oh! Championship Series Sydney 2019,17,PLIm0Rt8gzRburNEkrpAZchPkgIHfvOhYf
111,YCS Sydney 2017 | Yu-Gi-Oh! Championship Series Sydney 2017 (175th YCS),17,PLIm0Rt8gzRbuwoMC-m7OWUgD_Uuqt_5Km
127,YCS Madrid | Yu-Gi-Oh! Championship Series Madrid,16,PLIm0Rt8gzRbtE1wXv0kUYBP4GeNUnpFdg
119,2016 WCQ: German National Championship,16,PLIm0Rt8gzRbtCvzE6j2-6uD5cfNqnIVw2
99,YCS Melbourne 2018 | Yu-Gi-Oh! Championship Series Melbourne 2018 (January),15,PLIm0Rt8gzRbu8eb7UBCPY8jMkWSIfY5lZ
120,2015 WCQ: National Champion Interviews,14,PLIm0Rt8gzRbu6hF2h0RBMnuLQpzHDEQeY
126,WCS 2014 | 2014 Yu-Gi-Oh! TCG World Championship,13,PLIm0Rt8gzRbuBwwHoazOzCj6s3_67kj8e
104,2017 Yu-Gi-Oh! TRADING CARD GAME World Championship,13,PLIm0Rt8gzRbtF0raJMkgb_AVj7Kyqnwn7
109,[ES] 2017 WCQ: Spanish National Championship,11,PLIm0Rt8gzRbsKkfRBUEAtYDGBlH8fVkud
95,2018 WCQ: UK National Championship,11,PLIm0Rt8gzRbtlF-ldXXFmhRTym7L5yk23
32,Ultimate Time Wizard 2010 - YCS Bologna 2024,11,PLIm0Rt8gzRbvoTO6w4CBrg0uOJmsPZYMQ
98,2018 WCQ - UK Open - London II,10,PLIm0Rt8gzRbtV4YAMY-tqJL3Ov2LMki68
91,2018 Yu-Gi-Oh! TCG World Championship,10,PLIm0Rt8gzRbvqW-711158U4fL3Mk_aZCh
26,Ultimate Time Wizard 2010 Format - YCS Birmingham 2025,9,PLIm0Rt8gzRbvP8EGZykEEQIzaZ2gK8FSF
41,Yu-Gi-Oh! TCG Greek OPEN April 2024,9,PLIm0Rt8gzRbu0W_Ov0RLECOx8ZW6mIEKp
40,Yu-Gi-Oh! TCG Italian OPEN May 2024,9,PLIm0Rt8gzRbs9Msm9739PwTwCyMExCrdD
33,Yu-Gi-Oh! TCG Italian OPEN January 2025,9,PLIm0Rt8gzRbs0QeJ5UPKUXEMJ126KNK-b
89,2018 Yu-Gi-Oh! Duel Links World Championship,8,PLIm0Rt8gzRbuqtZFz-Sv7x1li19vA-ynQ
83,Yu-Gi-Oh! World Championship 2019 - Berlin,7,PLIm0Rt8gzRbsxRacuVerQ4REzU6zRQFXt
72,Remote Duel Yu-Gi-Oh! Championship Series 2021 – Top 8,7,PLIm0Rt8gzRbtMPDnLGYFII_tUVnRM5ScA
90,2018 Yu-Gi-Oh! TCG Dragon Duel World Championship,7,PLIm0Rt8gzRbuauJOWCGiWGDMbOrK_4lZz
37,Yu-Gi-Oh! World Championship Series 2024,6,PLIm0Rt8gzRbvlG2IvMeWgyI8VNEMLnuQ_
125,WCQ: EC2014 | Yu-Gi-Oh! TCG WCQ: European Championship 2014,1,PLIm0Rt8gzRbtTio1RMkWdRH9bkRNmX-Gh

# Feature Match Processing

In [197]:
import re
import pandas as pd

# Global Regex Compilation Matrix
RE_EURO = re.compile(r"(?:WCQ:\s*)?\bEuropean\b(?:\s+Yu-Gi-Oh!)?\s+\bChampionship\b", re.IGNORECASE)
RE_NATS = re.compile(r"WCQ:\s*([A-Za-z]+)\s+National Championship", re.IGNORECASE)
RE_OPEN = re.compile(r"\b([A-Za-z]+)\s+Open\b", re.IGNORECASE)
RE_YEARS = re.compile(r'\b(19\d{2}|20\d{2})\b')


def clean_base_text(full_title):
    """Handles pipe splitting, string type conversions, and leading/trailing whitespace."""
    base_text = str(full_title).strip()
    if "|" in base_text:
        base_text = base_text.split("|")[0].strip()
    return base_text


def extract_tournament_year(text):
    """Finds the main tournament year and strips it out of the title string."""
    year_match = RE_YEARS.search(text)
    if year_match:
        year = year_match.group(1)
        clean_title = text.replace(year, "").replace("  ", " ").strip(" -:")
        return year, clean_title
    return "Unknown", text


def process_ycs_event(clean_title, base_text):
    """Applies specialized transformations for YCS, Remote Duels, and Time Wizard formats."""
    category = 'Advanced'
    is_remote = 'Remote Duel' in clean_title
    
    if any(kw in clean_title for kw in ['Time Wizard', 'Ultimate Time Wizard']) or any(fmt in base_text for fmt in ['Edison', 'Goat', 'Toss', 'HAT']):
        category = 'Time Wizard'
        clean_title = clean_title.replace('Ultimate Time Wizard', '').replace('Time Wizard', '').replace('Format', '')
        clean_title = RE_YEARS.sub('', clean_title)  # Wipe retro format years (e.g., 2010)

    if 'Genesys' in clean_title:
        category = 'Genesys'
        
    clean_title = clean_title.replace('Yu-Gi-Oh! Championship Series', 'YCS')

    if 'YCS' in clean_title:
        clean_title = 'YCS' + clean_title.split('YCS')[1]
        clean_title = re.sub(r'\bYCS\s+in\s+', 'YCS ', clean_title, flags=re.IGNORECASE)
        
    if is_remote:
        clean_title = 'Remote ' + clean_title

    if any(dash in clean_title for dash in ['–', '-']) and 'Top' in clean_title:
        split_char = '–' if '–' in clean_title else '-'
        parts = clean_title.split(split_char)
        clean_title = f"{parts[0].strip()} ({parts[1].strip()})"
        
    clean_title = re.sub(r'\s+', ' ', clean_title).strip(" -")
    return clean_title, category


def identify_other_categories(clean_title):
    """Checks for World Championships, Nationals, Opens, and Continental WCQs."""
    category = 'Advanced'
    
    # 1. World Championships
    if 'World Championship' in clean_title or 'WCS' in clean_title:
        if 'Dragon Duel' in clean_title:
            category = 'Dragon Duel'
        return 'World Championship', category
    
    # 2. National Championships
    if match_nat := RE_NATS.search(clean_title):
        country = match_nat.group(1).strip()
        return f"{country} National Championship", category
        
    # 3. Open Tournaments
    if match_open := RE_OPEN.search(clean_title):
        country = match_open.group(1).strip()
        country = 'UK' if country.lower() == 'uk' else country.capitalize()
        return f"{country} Open", category
        
    # 4. Continental WCQs
    if 'WCQ: EC' in clean_title or 'World Championship Qualifier' in clean_title or RE_EURO.search(clean_title):
        return 'European WCQ', category
        
    return clean_title, category


def extract_title_and_year(full_title):
    if 'interview' in str(full_title).lower():
        return pd.Series([None, None, None])
        
    base_text = clean_base_text(full_title)
    year, clean_title = extract_tournament_year(base_text)
    if 'Yu-Gi-Oh! Championship Series' in clean_title or 'YCS' in clean_title:
        clean_title, category = process_ycs_event(clean_title, base_text)
    else:
        clean_title, category = identify_other_categories(clean_title)
        
    return pd.Series([clean_title, year, category])

In [199]:
filtered_df[["Clean Title", "Year", "Category"]] = filtered_df["Playlist Title"].apply(extract_title_and_year)
cleaned_df = filtered_df[["Clean Title", "Year", "Category", "Video Count", "Playlist ID", "Playlist Title"]]
cleaned_df = cleaned_df.dropna(subset=["Clean Title"])

# 3. Display your perfect table
display(cleaned_df)

,Clean Title,Year,Category,Video Count,Playlist ID,Playlist Title
96,YCS Bochum,2018,Advanced,78,PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl,YCS Bochum 2018 | Yu-Gi-Oh! Championship Series Bochum 2018
130,European WCQ,Unknown,Advanced,60,PLIm0Rt8gzRbss2nX1mixsDYj4CpmZ8ugW,WCQ: EC2015 | 2015 Yu-Gi-Oh! TCG WCQ: European Championship
116,European WCQ,Unknown,Advanced,57,PLIm0Rt8gzRbvYYuWPcfcb1ZNQLCoPT5vm,WCQ: EC2016 | 2016 WCQ: European Championship
106,European WCQ,2017,Advanced,54,PLIm0Rt8gzRbsHq8NXVNrIejQoUN3nMFfo,2017 WCQ: EC | 2017 WCQ: European Championship
86,YCS Milan,2018,Advanced,50,PLIm0Rt8gzRbvNmWVsRbgwdxXWcX1EXxh0,YCS Milan 2018 | Yu-Gi-Oh! Championship Series Milan 2018
13,YCS Bologna,2025,Advanced,46,PLIm0Rt8gzRbuI3ij0C4yrfAQb8tMbtCt8,YCS Bologna 2025
20,World Championship,2025,Advanced,44,PLIm0Rt8gzRbvUqBmSmnIEr9nTIFuqAW_F,"Yu-Gi-Oh! World Championship 2025 - Paris, France"
5,YCS Dortmund,2026,Advanced,41,PLIm0Rt8gzRbs70xRsspnrAuR1qgUDXl4e,YCS Dortmund 2026
84,YCS Düsseldorf,2019,Advanced,40,PLIm0Rt8gzRbue3Nu1Xy67JzYHUGRFFCSR,YCS Düsseldorf 2019 | Yu-Gi-Oh! Championship Series Düsseldorf 2019
94,European WCQ,2018,Advanced,39,PLIm0Rt8gzRbuLKQ294o73x9SXXT4S-8IO,2018 WCQ: European Championship
18,YCS Lille,2025,Advanced,38,PLIm0Rt8gzRbvpM61P9xfJEZoU558nP7Hw,YCS Lille 2025
131,YCS Bochum,Unknown,Advanced,38,PLIm0Rt8gzRbudSiIYYy2neWhQqecruQNU,YCS Bochum | Yu-Gi-Oh! Championship Series Bochum
35,YCS Bologna,2024,Advanced,38,PLIm0Rt8gzRbtnbZYH99PGTqCWtR6WZS77,YCS Bologna 2024
31,YCS Birmingham,2025,Advanced,37,PLIm0Rt8gzRbuSa9zamQ9XAqfN9f5wa0IM,YCS Birmingham 2025
108,German National Championship,2017,Advanced,37,PLIm0Rt8gzRbutxiGy8fJI0W3m4bcGg3-j,[DE] 2017 WCQ: German National Championship
38,YCS Lille,2024,Advanced,36,PLIm0Rt8gzRbsro5ChBPW-Jv8q2Potz2ll,275th Yu-Gi-Oh! Championship Series Lille 2024
115,YCS Rimini,2016,Advanced,34,PLIm0Rt8gzRbus2XHbGg1A0qef58bLUg9W,YCS Rimini 2016 | Yu-Gi-Oh! Championship Series Rimini 2016
110,YCS Prague,2017,Advanced,33,PLIm0Rt8gzRbvQIZ4LdDzsQcg05qD5-AfI,YCS Prague 2017 | Yu-Gi-Oh! Championship Series Prague 2017
102,YCS London,2017,Advanced,32,PLIm0Rt8gzRbvARnj3qZUwXVaN3WLiZu-G,YCS London 2017 | Yu-Gi-Oh! Championship Series London 2017
112,YCS Bochum,2016,Advanced,32,PLIm0Rt8gzRbsCXQnGZVhu2Acnfbi43uk6,YCS Bochum 2016 | Yu-Gi-Oh! Championship Series Bochum 2016
114,YCS Liverpool,2016,Advanced,32,PLIm0Rt8gzRbtPVaqIwILHqX2YvVk54upH,YCS Liverpool 2016 | Yu-Gi-Oh! Championship Series Liverpool 2016
107,UK National Championship,2017,Advanced,32,PLIm0Rt8gzRbtzapH_8KLPAehZVrHsALMR,2017 WCQ: UK National Championship
129,YCS Prague,Unknown,Advanced,32,PLIm0Rt8gzRbu5rDW3wVN5G_Zcg_G53RB9,YCS Prague | Yu-Gi-Oh! Championship Series Prague
39,World Championship,2024,Advanced,29,PLIm0Rt8gzRbsuyvjSAe5Zf9_CxIvEqsH2,Yu-Gi-Oh! World Championship Qualifier Berlin 2024
21,World Championship,2025,Advanced,29,PLIm0Rt8gzRbtzFNzn1ayewRiNuwNekWsq,Yu-Gi-Oh! World Championship Qualifier Berlin 2025
87,YCS London,2018,Advanced,29,PLIm0Rt8gzRbvdbAcXuDGBPDQ24dW5wjKc,YCS London 2018 | Yu-Gi-Oh! Championship Series London 2018
124,YCS London,Unknown,Advanced,28,PLIm0Rt8gzRbsM_eU_TVTTh8GJPA1ZCF0Z,YCS London | Yu-Gi-Oh! Championship Series London
122,YCS Rimini,Unknown,Advanced,28,PLIm0Rt8gzRbsmNqbYBR6ET0v82YLHs-Pk,YCS Rimini | Yu-Gi-Oh! Championship Series Rimini 2015
100,YCS Prague,2017,Advanced,28,PLIm0Rt8gzRbvOLxLL69WsUn1Q6jwbpDRo,YCS Prague 2017 | Yu-Gi-Oh! Championship Series Prague 2017 (November)
121,YCS Prague,2016,Advanced,25,PLIm0Rt8gzRbtuya5V5H6zeKwIlmbwyunI,YCS Prague 2016 | Yu-Gi-Oh! Championship Series Prague 2016
92,World Championship,2018,Advanced,23,PLIm0Rt8gzRbsNALbcx6KJ8V5a2-mYLUCn,2018 Yu-Gi-Oh! World Championship
118,UK National Championship,2016,Advanced,22,PLIm0Rt8gzRbsidpr96G4FFXf9GvdMh-lB,2016 WCQ: UK National Championship
103,YCS Rimini,2017,Advanced,21,PLIm0Rt8gzRbviW3duevd3e3C1QjalKtlj,YCS Rimini 2017 | Yu-Gi-Oh! Championship Series Rimini 2017
60,YCS Lyon,2023,Advanced,21,PLIm0Rt8gzRbsZ9pAhcQcggxgkcWsWZGni,YCS Lyon 2023
57,World Championship,2023,Advanced,21,PLIm0Rt8gzRbsGUTXNC05ktSQ_DbPLG0dL,2023 European World Championship Qualifier
59,YCS London,2023,Advanced,20,PLIm0Rt8gzRbvYDhxLPDUyBVNNPme534Pv,YCS London 2023
79,YCS Utrecht,2020,Advanced,20,PLIm0Rt8gzRbuO5Y9S6sLDEcy9ceIQpkHB,YCS Utrecht 2020 | Yu-Gi-Oh! Championship Series Utrecht 2020
88,YCS Utrecht,2018,Advanced,20,PLIm0Rt8gzRburE-D3lYnL5QL6INZRSHn2,YCS Utrecht 2018 | 200th YCS | Yu-Gi-Oh! Championship Series Utrecht 2018
55,YCS Dortmund,2023,Advanced,20,PLIm0Rt8gzRbsWWG_zEMA3iybOAd7TF1gc,Yu-Gi-Oh! Championship Series Dortmund 2023
47,YCS Bologna,2023,Advanced,20,PLIm0Rt8gzRbs_jPCYppMNC7TOCuibkYgy,Yu-Gi-Oh! Championship Series Bologna 2023
65,European WCQ,2022,Advanced,20,PLIm0Rt8gzRbtsvJLX5Jz3_XP401RpPNw_,European Yu-Gi-Oh! Championship 2022
81,YCS London,2019,Advanced,19,PLIm0Rt8gzRbt26wj5dH1-p7JP9PjmWFin,Yu-Gi-Oh! Championship Series in London 2019
82,YCS Ghent,2019,Advanced,19,PLIm0Rt8gzRbvQIL8kLAlzf2b1frm5P6jR,Yu-Gi-Oh! Championship Series in Ghent 2019
80,YCS Milan,2019,Advanced,18,PLIm0Rt8gzRbubZdC-3nwjMmf4XnBa3XcX,Yu-Gi-Oh! Championship Series in Milan 2019
128,YCS Milan,Unknown,Advanced,18,PLIm0Rt8gzRbu5uULuK4WArO6Ii3VRo12L,YCS Milan | Yu-Gi-Oh! Championship Series Milan
62,YCS Dortmund,2022,Advanced,18,PLIm0Rt8gzRbuAOWpBz67KbSptL4l-ZEXl,YCS Dortmund 2022
63,YCS Utrecht,2022,Advanced,18,PLIm0Rt8gzRbv6leYtBwsne1gGpiwbP9Yh,YCS Utrecht 2022
85,YCS Sydney,2019,Advanced,17,PLIm0Rt8gzRburNEkrpAZchPkgIHfvOhYf,YCS Sydney 2019 | Yu-Gi-Oh! Championship Series Sydney 2019
111,YCS Sydney,2017,Advanced,17,PLIm0Rt8gzRbuwoMC-m7OWUgD_Uuqt_5Km,YCS Sydney 2017 | Yu-Gi-Oh! Championship Series Sydney 2017 (175th YCS)
127,YCS Madrid,Unknown,Advanced,16,PLIm0Rt8gzRbtE1wXv0kUYBP4GeNUnpFdg,YCS Madrid | Yu-Gi-Oh! Championship Series Madrid
119,German National Championship,2016,Advanced,16,PLIm0Rt8gzRbtCvzE6j2-6uD5cfNqnIVw2,2016 WCQ: German National Championship
99,YCS Melbourne,2018,Advanced,15,PLIm0Rt8gzRbu8eb7UBCPY8jMkWSIfY5lZ,YCS Melbourne 2018 | Yu-Gi-Oh! Championship Series Melbourne 2018 (January)
126,World Championship,2014,Advanced,13,PLIm0Rt8gzRbuBwwHoazOzCj6s3_67kj8e,WCS 2014 | 2014 Yu-Gi-Oh! TCG World Championship
104,World Championship,2017,Advanced,13,PLIm0Rt8gzRbtF0raJMkgb_AVj7Kyqnwn7,2017 Yu-Gi-Oh! TRADING CARD GAME World Championship
109,Spanish National Championship,2017,Advanced,11,PLIm0Rt8gzRbsKkfRBUEAtYDGBlH8fVkud,[ES] 2017 WCQ: Spanish National Championship
95,UK National Championship,2018,Advanced,11,PLIm0Rt8gzRbtlF-ldXXFmhRTym7L5yk23,2018 WCQ: UK National Championship
32,YCS Bologna,2010,Time Wizard,11,PLIm0Rt8gzRbvoTO6w4CBrg0uOJmsPZYMQ,Ultimate Time Wizard 2010 - YCS Bologna 2024
98,UK Open,2018,Advanced,10,PLIm0Rt8gzRbtV4YAMY-tqJL3Ov2LMki68,2018 WCQ - UK Open - London II
91,World Championship,2018,Advanced,10,PLIm0Rt8gzRbvqW-711158U4fL3Mk_aZCh,2018 Yu-Gi-Oh! TCG World Championship
26,YCS Birmingham,2010,Time Wizard,9,PLIm0Rt8gzRbvP8EGZykEEQIzaZ2gK8FSF,Ultimate Time Wizard 2010 Format - YCS Birmingham 2025
41,Greek Open,2024,Advanced,9,PLIm0Rt8gzRbu0W_Ov0RLECOx8ZW6mIEKp,Yu-Gi-Oh! TCG Greek OPEN April 2024
40,Italian Open,2024,Advanced,9,PLIm0Rt8gzRbs9Msm9739PwTwCyMExCrdD,Yu-Gi-Oh! TCG Italian OPEN May 2024
33,Italian Open,2025,Advanced,9,PLIm0Rt8gzRbs0QeJ5UPKUXEMJ126KNK-b,Yu-Gi-Oh! TCG Italian OPEN January 2025
89,World Championship,2018,Advanced,8,PLIm0Rt8gzRbuqtZFz-Sv7x1li19vA-ynQ,2018 Yu-Gi-Oh! Duel Links World Championship
83,World Championship,2019,Advanced,7,PLIm0Rt8gzRbsxRacuVerQ4REzU6zRQFXt,Yu-Gi-Oh! World Championship 2019 - Berlin
72,Remote YCS (Top 8),2021,Advanced,7,PLIm0Rt8gzRbtMPDnLGYFII_tUVnRM5ScA,Remote Duel Yu-Gi-Oh! Championship Series 2021 – Top 8
90,World Championship,2018,Dragon Duel,7,PLIm0Rt8gzRbuauJOWCGiWGDMbOrK_4lZz,2018 Yu-Gi-Oh! TCG Dragon Duel World Championship
37,World Championship,2024,Advanced,6,PLIm0Rt8gzRbvlG2IvMeWgyI8VNEMLnuQ_,Yu-Gi-Oh! World Championship Series 2024
125,European WCQ,Unknown,Advanced,1,PLIm0Rt8gzRbtTio1RMkWdRH9bkRNmX-Gh,WCQ: EC2014 | Yu-Gi-Oh! TCG WCQ: European Championship 2014

# Get playlist IDs

In [185]:
playlist_ids = cleaned_df['Playlist ID'].astype(str).tolist()
playlist_ids

['PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl',
 'PLIm0Rt8gzRbss2nX1mixsDYj4CpmZ8ugW',
 'PLIm0Rt8gzRbvYYuWPcfcb1ZNQLCoPT5vm',
 'PLIm0Rt8gzRbsHq8NXVNrIejQoUN3nMFfo',
 'PLIm0Rt8gzRbvNmWVsRbgwdxXWcX1EXxh0',
 'PLIm0Rt8gzRbuI3ij0C4yrfAQb8tMbtCt8',
 'PLIm0Rt8gzRbvUqBmSmnIEr9nTIFuqAW_F',
 'PLIm0Rt8gzRbs70xRsspnrAuR1qgUDXl4e',
 'PLIm0Rt8gzRbue3Nu1Xy67JzYHUGRFFCSR',
 'PLIm0Rt8gzRbuLKQ294o73x9SXXT4S-8IO',
 'PLIm0Rt8gzRbvpM61P9xfJEZoU558nP7Hw',
 'PLIm0Rt8gzRbudSiIYYy2neWhQqecruQNU',
 'PLIm0Rt8gzRbtnbZYH99PGTqCWtR6WZS77',
 'PLIm0Rt8gzRbuSa9zamQ9XAqfN9f5wa0IM',
 'PLIm0Rt8gzRbutxiGy8fJI0W3m4bcGg3-j',
 'PLIm0Rt8gzRbsro5ChBPW-Jv8q2Potz2ll',
 'PLIm0Rt8gzRbus2XHbGg1A0qef58bLUg9W',
 'PLIm0Rt8gzRbvQIZ4LdDzsQcg05qD5-AfI',
 'PLIm0Rt8gzRbvARnj3qZUwXVaN3WLiZu-G',
 'PLIm0Rt8gzRbsCXQnGZVhu2Acnfbi43uk6',
 'PLIm0Rt8gzRbtPVaqIwILHqX2YvVk54upH',
 'PLIm0Rt8gzRbtzapH_8KLPAehZVrHsALMR',
 'PLIm0Rt8gzRbu5rDW3wVN5G_Zcg_G53RB9',
 'PLIm0Rt8gzRbsuyvjSAe5Zf9_CxIvEqsH2',
 'PLIm0Rt8gzRbtzFNzn1ayewRiNuwNekWsq',
 'PLIm0Rt8gzRbvdbAcXuDGBPDQ24dW5wjKc',
 'PLIm0Rt8gzRbsM_eU_TVTTh8GJPA1ZCF0Z',
 'PLIm0Rt8gzRbsmNqbYBR6ET0v82YLHs-Pk',
 'PLIm0Rt8gzRbvOLxLL69WsUn1Q6jwbpDRo',
 'PLIm0Rt8gzRbtuya5V5H6zeKwIlmbwyunI',
 'PLIm0Rt8gzRbsNALbcx6KJ8V5a2-mYLUCn',
 'PLIm0Rt8gzRbsidpr96G4FFXf9GvdMh-lB',
 'PLIm0Rt8gzRbviW3duevd3e3C1QjalKtlj',
 'PLIm0Rt8gzRbsZ9pAhcQcggxgkcWsWZGni',
 'PLIm0Rt8gzRbsGUTXNC05ktSQ_DbPLG0dL',
 'PLIm0Rt8gzRbvYDhxLPDUyBVNNPme534Pv',
 'PLIm0Rt8gzRbuO5Y9S6sLDEcy9ceIQpkHB',
 'PLIm0Rt8gzRburE-D3lYnL5QL6INZRSHn2',
 'PLIm0Rt8gzRbsWWG_zEMA3iybOAd7TF1gc',
 'PLIm0Rt8gzRbs_jPCYppMNC7TOCuibkYgy',
 'PLIm0Rt8gzRbtsvJLX5Jz3_XP401RpPNw_',
 'PLIm0Rt8gzRbt26wj5dH1-p7JP9PjmWFin',
 'PLIm0Rt8gzRbvQIL8kLAlzf2b1frm5P6jR',
 'PLIm0Rt8gzRbubZdC-3nwjMmf4XnBa3XcX',
 'PLIm0Rt8gzRbu5uULuK4WArO6Ii3VRo12L',
 'PLIm0Rt8gzRbuAOWpBz67KbSptL4l-ZEXl',
 'PLIm0Rt8gzRbv6leYtBwsne1gGpiwbP9Yh',
 'PLIm0Rt8gzRburNEkrpAZchPkgIHfvOhYf',
 'PLIm0Rt8gzRbuwoMC-m7OWUgD_Uuqt_5Km',
 'PLIm0Rt8gzRbtE1wXv0kUYBP4GeNUnpFdg',
 'PLIm0Rt8gzRbtCvzE6j2-6uD5cfNqnIVw2',
 'PLIm0Rt8gzRbu8eb7UBCPY8jMkWSIfY5lZ',
 'PLIm0Rt8gzRbuBwwHoazOzCj6s3_67kj8e',
 'PLIm0Rt8gzRbtF0raJMkgb_AVj7Kyqnwn7',
 'PLIm0Rt8gzRbsKkfRBUEAtYDGBlH8fVkud',
 'PLIm0Rt8gzRbtlF-ldXXFmhRTym7L5yk23',
 'PLIm0Rt8gzRbvoTO6w4CBrg0uOJmsPZYMQ',
 'PLIm0Rt8gzRbtV4YAMY-tqJL3Ov2LMki68',
 'PLIm0Rt8gzRbvqW-711158U4fL3Mk_aZCh',
 'PLIm0Rt8gzRbvP8EGZykEEQIzaZ2gK8FSF',
 'PLIm0Rt8gzRbu0W_Ov0RLECOx8ZW6mIEKp',
 'PLIm0Rt8gzRbs9Msm9739PwTwCyMExCrdD',
 'PLIm0Rt8gzRbs0QeJ5UPKUXEMJ126KNK-b',
 'PLIm0Rt8gzRbuqtZFz-Sv7x1li19vA-ynQ',
 'PLIm0Rt8gzRbsxRacuVerQ4REzU6zRQFXt',
 'PLIm0Rt8gzRbtMPDnLGYFII_tUVnRM5ScA',
 'PLIm0Rt8gzRbuauJOWCGiWGDMbOrK_4lZz',
 'PLIm0Rt8gzRbvlG2IvMeWgyI8VNEMLnuQ_',
 'PLIm0Rt8gzRbtTio1RMkWdRH9bkRNmX-Gh']

In [305]:
from googleapiclient.discovery import build
import pandas as pd

def get_playlists_videos(playlist_ids):
    """
    Iterates through a list of YouTube playlist IDs, fetches all video titles 
    and descriptions, and returns them in a pandas DataFrame.
    """
    # Initialize the YouTube API client
    # Replace 'YOUR_API_KEY' with your actual YouTube Data API v3 key
    youtube = build('youtube', 'v3', developerKey=os.getenv("YOUTUBE_API_KEY"))
    
    video_data = []
    
    for playlist_id in playlist_ids:
        next_page_token = None
        
        # Loop to handle pagination (playlists with more than 50 items)
        while True:
            # Request playlist items
            request = youtube.playlistItems().list(
                part="snippet",
                playlistId=playlist_id,
                maxResults=50,
                pageToken=next_page_token
            )
            response = request.execute()
            
            # Extract title and description from each video
            for item in response.get('items', []):
                title = item['snippet']['title']
                description = item['snippet']['description']
                
                video_data.append({
                    'Playlist ID': playlist_id,
                    'Title': title,
                    'Description': description
                })
            
            # Check if there's another page of videos
            next_page_token = response.get('nextPageToken')
            if not next_page_token:
                break
                
    # Convert the list of dictionaries into a Pandas DataFrame
    df = pd.DataFrame(video_data)
    return df

playlists = get_playlists_videos(playlist_ids)

In [306]:
playlists

                             Playlist ID  \
0     PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl
1     PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl
2     PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl
3     PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl
4     PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl
5     PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl
6     PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl
7     PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl
8     PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl
9     PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl
10    PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl
11    PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl
12    PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl
13    PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl
14    PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl
15    PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl
16    PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl
17    PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl
18    PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl
19    PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl
20    PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl
21    PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl
22    PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl
23    PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl
24    PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl
25    PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl
26    PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl
27    PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl
28    PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl
29    PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl
30    PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl
31    PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl
32    PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl
33    PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl
34    PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl
35    PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl
36    PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl
37    PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl
38    PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl
39    PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl
40    PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl
41    PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl
42    PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl
43    PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl
44    PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl
45    PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl
46    PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl
47    PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl
48    PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl
49    PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl
50    PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl
51    PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl
52    PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl
53    PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl
54    PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl
55    PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl
56    PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl
57    PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl
58    PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl
59    PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl
60    PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl
61    PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl
62    PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl
63    PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl
64    PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl
65    PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl
66    PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl
67    PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl
68    PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl
69    PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl
70    PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl
71    PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl
72    PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl
73    PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl
74    PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl
75    PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl
76    PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl
77    PLIm0Rt8gzRbv3fIxWySnaolII9TXeBGDl
78    PLIm0Rt8gzRbss2nX1mixsDYj4CpmZ8ugW
79    PLIm0Rt8gzRbss2nX1mixsDYj4CpmZ8ugW
80    PLIm0Rt8gzRbss2nX1mixsDYj4CpmZ8ugW
81    PLIm0Rt8gzRbss2nX1mixsDYj4CpmZ8ugW
82    PLIm0Rt8gzRbss2nX1mixsDYj4CpmZ8ugW
83    PLIm0Rt8gzRbss2nX1mixsDYj4CpmZ8ugW
84    PLIm0Rt8gzRbss2nX1mixsDYj4CpmZ8ugW
85    PLIm0Rt8gzRbss2nX1mixsDYj4CpmZ8ugW
86    PLIm0Rt8gzRbss2nX1mixsDYj4CpmZ8ugW
87    PLIm0Rt8gzRbss2nX1mixsDYj4CpmZ8ugW
88    PLIm0Rt8gzRbss2nX1mixsDYj4CpmZ8ugW
89    PLIm0Rt8gzRbss2nX1mixsDYj4CpmZ8ugW
90    PLIm0Rt8gzRbss2nX1mixsDYj4CpmZ8ugW
91    PLIm0Rt8gzRbss2nX1mixsDYj4CpmZ8ugW
92    PLIm0Rt8gzRbss2nX1mixsDYj4CpmZ8ugW
93    PLIm0Rt8gzRbss2nX1mixsDYj4CpmZ8ugW
94    PLIm0Rt8gzRbss2nX1mixsDYj4CpmZ8ugW
95    PLIm0Rt8gzRbss2nX1mixsDYj4CpmZ8ugW
96    PLIm0Rt8gzRbss2nX1mixsDYj4CpmZ8ugW
97    PLIm0Rt8gzRbss2nX1mixsDYj4CpmZ8ugW
98    PLIm0Rt8gzRbss2nX1mixsDYj4CpmZ8ugW
99    PLIm0Rt8gzRbss2nX1mixsDYj4CpmZ8ugW
100   PLIm0Rt8gzRbss2nX1mixsDYj4CpmZ8ugW
101   PLIm0Rt8gzRbss2nX1mixsDYj4CpmZ8ugW
102   PLIm0Rt8gzRbss2nX1mixsDYj4CpmZ8ugW
103   PLIm0Rt8gzRbss2nX1mixsDYj4CpmZ8ugW
104   PLIm0Rt8gzRbss2nX1mixsDYj4CpmZ8ugW
105   PLIm0Rt8gzRbss2nX1mixsDYj4CpmZ8ugW
106   PLIm0Rt8gzRbss2nX1mixsDYj4CpmZ8ugW
107   PLIm0Rt8gzRbss2nX1mixsDYj4CpmZ8ugW
108   PLIm0Rt8gzRbss2nX1mixsDYj4CpmZ8ugW
109   PLIm0Rt8gzRbss2nX1mixsDYj4CpmZ8ugW
110   PLIm0Rt8gzRbss2nX1mixsDYj4CpmZ8ugW
111   PLIm0Rt8gzRbss2nX1mixsDYj4CpmZ8ugW
112   PLIm0Rt8gzRbss2nX1mixsDYj4CpmZ8ugW
113   PLIm0Rt8gzRbss2nX1mixsDYj4CpmZ8ugW
114   PLIm0Rt8gzRbss2nX1mixsDYj4CpmZ8ugW
115   PLIm0Rt8gzRbss2nX1mixsDYj4CpmZ8ugW
116   PLIm0Rt8gzRbss2nX1mixsDYj4CpmZ8ugW
117   PLIm0Rt8gzRbss2nX1mixsDYj4CpmZ8ugW
118   PLIm0Rt8gzRbss2nX1mixsDYj4CpmZ8ugW
119   PLIm0Rt8gzRbss2nX1mixsDYj4CpmZ8ugW
120   PLIm0Rt8gzRbss2nX1mixsDYj4CpmZ8ugW
121   PLIm0Rt8gzRbss2nX1mixsDYj4CpmZ8ugW
122   PLIm0Rt8gzRbss2nX1mixsDYj4CpmZ8ugW
123   PLIm0Rt8gzRbss2nX1mixsDYj4CpmZ8ugW
124   PLIm0Rt8gzRbss2nX1mixsDYj4CpmZ8ugW
125   PLIm0Rt8gzRbss2nX1mixsDYj4CpmZ8ugW
126   PLIm0Rt8gzRbss2nX1mixsDYj4CpmZ8ugW
127   PLIm0Rt8gzRbss2nX1mixsDYj4CpmZ8ugW
128   PLIm0Rt8gzRbss2nX1mixsDYj4CpmZ8ugW
129   PLIm0Rt8gzRbss2nX1mixsDYj4CpmZ8ugW
130   PLIm0Rt8gzRbss2nX1mixsDYj4CpmZ8ugW
131   PLIm0Rt8gzRbss2nX1mixsDYj4CpmZ8ugW
132   PLIm0Rt8gzRbss2nX1mixsDYj4CpmZ8ugW
133   PLIm0Rt8gzRbss2nX1mixsDYj4CpmZ8ugW
134   PLIm0Rt8gzRbss2nX1mixsDYj4CpmZ8ugW
135   PLIm0Rt8gzRbss2nX1mixsDYj4CpmZ8ugW
136   PLIm0Rt8gzRbss2nX1mixsDYj4CpmZ8ugW
137   PLIm0Rt8gzRbss2nX1mixsDYj4CpmZ8ugW
138   PLIm0Rt8gzRbvYYuWPcfcb1ZNQLCoPT5vm
139   PLIm0Rt8gzRbvYYuWPcfcb1ZNQLCoPT5vm
140   PLIm0Rt8gzRbvYYuWPcfcb1ZNQLCoPT5vm
141   PLIm0Rt8gzRbvYYuWPcfcb1ZNQLCoPT5vm
142   PLIm0Rt8gzRbvYYuWPcfcb1ZNQLCoPT5vm
143   PLIm0Rt8gzRbvYYuWPcfcb1ZNQLCoPT5vm
144   PLIm0Rt8gzRbvYYuWPcfcb1ZNQLCoPT5vm
145   PLIm0Rt8gzRbvYYuWPcfcb1ZNQLCoPT5vm
146   PLIm0Rt8gzRbvYYuWPcfcb1ZNQLCoPT5vm
147   PLIm0Rt8gzRbvYYuWPcfcb1ZNQLCoPT5vm
148   PLIm0Rt8gzRbvYYuWPcfcb1ZNQLCoPT5vm
149   PLIm0Rt8gzRbvYYuWPcfcb1ZNQLCoPT5vm
150   PLIm0Rt8gzRbvYYuWPcfcb1ZNQLCoPT5vm
151   PLIm0Rt8gzRbvYYuWPcfcb1ZNQLCoPT5vm
152   PLIm0Rt8gzRbvYYuWPcfcb1ZNQLCoPT5vm
153   PLIm0Rt8gzRbvYYuWPcfcb1ZNQLCoPT5vm
154   PLIm0Rt8gzRbvYYuWPcfcb1ZNQLCoPT5vm
155   PLIm0Rt8gzRbvYYuWPcfcb1ZNQLCoPT5vm
156   PLIm0Rt8gzRbvYYuWPcfcb1ZNQLCoPT5vm
157   PLIm0Rt8gzRbvYYuWPcfcb1ZNQLCoPT5vm
158   PLIm0Rt8gzRbvYYuWPcfcb1ZNQLCoPT5vm
159   PLIm0Rt8gzRbvYYuWPcfcb1ZNQLCoPT5vm
160   PLIm0Rt8gzRbvYYuWPcfcb1ZNQLCoPT5vm
161   PLIm0Rt8gzRbvYYuWPcfcb1ZNQLCoPT5vm
162   PLIm0Rt8gzRbvYYuWPcfcb1ZNQLCoPT5vm
163   PLIm0Rt8gzRbvYYuWPcfcb1ZNQLCoPT5vm
164   PLIm0Rt8gzRbvYYuWPcfcb1ZNQLCoPT5vm
165   PLIm0Rt8gzRbvYYuWPcfcb1ZNQLCoPT5vm
166   PLIm0Rt8gzRbvYYuWPcfcb1ZNQLCoPT5vm
167   PLIm0Rt8gzRbvYYuWPcfcb1ZNQLCoPT5vm
168   PLIm0Rt8gzRbvYYuWPcfcb1ZNQLCoPT5vm
169   PLIm0Rt8gzRbvYYuWPcfcb1ZNQLCoPT5vm
170   PLIm0Rt8gzRbvYYuWPcfcb1ZNQLCoPT5vm
171   PLIm0Rt8gzRbvYYuWPcfcb1ZNQLCoPT5vm
172   PLIm0Rt8gzRbvYYuWPcfcb1ZNQLCoPT5vm
173   PLIm0Rt8gzRbvYYuWPcfcb1ZNQLCoPT5vm
174   PLIm0Rt8gzRbvYYuWPcfcb1ZNQLCoPT5vm
175   PLIm0Rt8gzRbvYYuWPcfcb1ZNQLCoPT5vm
176   PLIm0Rt8gzRbvYYuWPcfcb1ZNQLCoPT5vm
177   PLIm0Rt8gzRbvYYuWPcfcb1ZNQLCoPT5vm
178   PLIm0Rt8gzRbvYYuWPcfcb1ZNQLCoPT5vm
179   PLIm0Rt8gzRbvYYuWPcfcb1ZNQLCoPT5vm
180   PLIm0Rt8gzRbvYYuWPcfcb1ZNQLCoPT5vm
181   PLIm0Rt8gzRbvYYuWPcfcb1ZNQLCoPT5vm
182   PLIm0Rt8gzRbvYYuWPcfcb1ZNQLCoPT5vm
183   PLIm0Rt8gzRbvYYuWPcfcb1ZNQLCoPT5vm
184   PLIm0Rt8gzRbvYYuWPcfcb1ZNQLCoPT5vm
185   PLIm0Rt8gzRbvYYuWPcfcb1ZNQLCoPT5vm
186   PLIm0Rt8gzRbvYYuWPcfcb1ZNQLCoPT5vm
187   PLIm0Rt8gzRbvYYuWPcfcb1ZNQLCoPT5vm
188   PLIm0Rt8gzRbvYYuWPcfcb1ZNQLCoPT5vm
189   PLIm0Rt8gzRbvYYuWPcfcb1ZNQLCoPT5vm
190   PLIm0Rt8gzRbvYYuWPcfcb1ZNQLCoPT5vm
191   PLIm0Rt8gzRbvYYuWPcfcb1ZNQLCoPT5vm
192   PLIm0Rt8gzRbvYYuWPcfcb1ZNQLCoPT5vm
193   PLIm0Rt8gzRbvYYuWPcfcb1ZNQLCoPT5vm
194   PLIm0Rt8gzRbvYYuWPcfcb1ZNQLCoPT5vm
195   PLIm0Rt8gzRbsHq8NXVNrIejQoUN3nMFfo
196   PLIm0Rt8gzRbsHq8NXVNrIejQoUN3nMFfo
197   PLIm0Rt8gzRbsHq8NXVNrIejQoUN3nMFfo
198   PLIm0Rt8gzRbsHq8NXVNrIejQoUN3nMFfo
199   PLIm0Rt8gzRbsHq8NXVNrIejQoUN3nMFfo
200   PLIm0Rt8gzRbsHq8NXVNrIejQoUN3nMFfo
201   PLIm0Rt8gzRbsHq8NXVNrIejQoUN3nMFfo
202   PLIm0Rt8gzRbsHq8NXVNrIejQoUN3nMFfo
203   PLIm0Rt8gzRbsHq8NXVNrIejQoUN3nMFfo
204   PLIm0Rt8gzRbsHq8NXVNrIejQoUN3nMFfo
205   PLIm0Rt8gzRbsHq8NXVNrIejQoUN3nMFfo
206   PLIm0Rt8gzRbsHq8NXVNrIejQoUN3nMFfo
207   PLIm0Rt8gzRbsHq8NXVNrIejQoUN3nMFfo
208   PLIm0Rt8gzRbsHq8NXVNrIejQoUN3nMFfo
209   PLIm0Rt8gzRbsHq8NXVNrIejQoUN3nMFfo
210   PLIm0Rt8gzRbsHq8NXVNrIejQoUN3nMFfo
211   PLIm0Rt8gzRbsHq8NXVNrIejQoUN3nMFfo
212   PLIm0Rt8gzRbsHq8NXVNrIejQoUN3nMFfo
213   PLIm0Rt8gzRbsHq8NXVNrIejQoUN3nMFfo
214   PLIm0Rt8gzRbsHq8NXVNrIejQoUN3nMFfo
215   PLIm0Rt8gzRbsHq8NXVNrIejQoUN3nMFfo
216   PLIm0Rt8gzRbsHq8NXVNrIejQoUN3nMFfo
217   PLIm0Rt8gzRbsHq8NXVNrIejQoUN3nMFfo
218   PLIm0Rt8gzRbsHq8NXVNrIejQoUN3nMFfo
219   PLIm0Rt8gzRbsHq8NXVNrIejQoUN3nMFfo
220   PLIm0Rt8gzRbsHq8NXVNrIejQoUN3nMFfo
221   PLIm0Rt8gzRbsHq8NXVNrIejQoUN3nMFfo
222   PLIm0Rt8gzRbsHq8NXVNrIejQoUN3nMFfo
223   PLIm0Rt8gzRbsHq8NXVNrIejQoUN3nMFfo
224   PLIm0Rt8gzRbsHq8NXVNrIejQoUN3nMFfo
225   PLIm0Rt8gzRbsHq8NXVNrIejQoUN3nMFfo
226   PLIm0Rt8gzRbsHq8NXVNrIejQoUN3nMFfo
227   PLIm0Rt8gzRbsHq8NXVNrIejQoUN3nMFfo
228   PLIm0Rt8gzRbsHq8NXVNrIejQoUN3nMFfo
229   PLIm0Rt8gzRbsHq8NXVNrIejQoUN3nMFfo
230   PLIm0Rt8gzRbsHq8NXVNrIejQoUN3nMFfo
231   PLIm0Rt8gzRbsHq8NXVNrIejQoUN3nMFfo
232   PLIm0Rt8gzRbsHq8NXVNrIejQoUN3nMFfo
233   PLIm0Rt8gzRbsHq8NXVNrIejQoUN3nMFfo
234   PLIm0Rt8gzRbsHq8NXVNrIejQoUN3nMFfo
235   PLIm0Rt8gzRbsHq8NXVNrIejQoUN3nMFfo
236   PLIm0Rt8gzRbsHq8NXVNrIejQoUN3nMFfo
237   PLIm0Rt8gzRbsHq8NXVNrIejQoUN3nMFfo
238   PLIm0Rt8gzRbsHq8NXVNrIejQoUN3nMFfo
239   PLIm0Rt8gzRbsHq8NXVNrIejQoUN3nMFfo
240   PLIm0Rt8gzRbsHq8NXVNrIejQoUN3nMFfo
241   PLIm0Rt8gzRbsHq8NXVNrIejQoUN3nMFfo
242   PLIm0Rt8gzRbsHq8NXVNrIejQoUN3nMFfo
243   PLIm0Rt8gzRbsHq8NXVNrIejQoUN3nMFfo
244   PLIm0Rt8gzRbsHq8NXVNrIejQoUN3nMFfo
245   PLIm0Rt8gzRbsHq8NXVNrIejQoUN3nMFfo
246   PLIm0Rt8gzRbsHq8NXVNrIejQoUN3nMFfo
247   PLIm0Rt8gzRbsHq8NXVNrIejQoUN3nMFfo
248   PLIm0Rt8gzRbsHq8NXVNrIejQoUN3nMFfo
249   PLIm0Rt8gzRbvNmWVsRbgwdxXWcX1EXxh0
250   PLIm0Rt8gzRbvNmWVsRbgwdxXWcX1EXxh0
251   PLIm0Rt8gzRbvNmWVsRbgwdxXWcX1EXxh0
252   PLIm0Rt8gzRbvNmWVsRbgwdxXWcX1EXxh0
253   PLIm0Rt8gzRbvNmWVsRbgwdxXWcX1EXxh0
254   PLIm0Rt8gzRbvNmWVsRbgwdxXWcX1EXxh0
255   PLIm0Rt8gzRbvNmWVsRbgwdxXWcX1EXxh0
256   PLIm0Rt8gzRbvNmWVsRbgwdxXWcX1EXxh0
257   PLIm0Rt8gzRbvNmWVsRbgwdxXWcX1EXxh0
258   PLIm0Rt8gzRbvNmWVsRbgwdxXWcX1EXxh0
259   PLIm0Rt8gzRbvNmWVsRbgwdxXWcX1EXxh0
260   PLIm0Rt8gzRbvNmWVsRbgwdxXWcX1EXxh0
261   PLIm0Rt8gzRbvNmWVsRbgwdxXWcX1EXxh0
262   PLIm0Rt8gzRbvNmWVsRbgwdxXWcX1EXxh0
263   PLIm0Rt8gzRbvNmWVsRbgwdxXWcX1EXxh0
264   PLIm0Rt8gzRbvNmWVsRbgwdxXWcX1EXxh0
265   PLIm0Rt8gzRbvNmWVsRbgwdxXWcX1EXxh0
266   PLIm0Rt8gzRbvNmWVsRbgwdxXWcX1EXxh0
267   PLIm0Rt8gzRbvNmWVsRbgwdxXWcX1EXxh0
268   PLIm0Rt8gzRbvNmWVsRbgwdxXWcX1EXxh0
269   PLIm0Rt8gzRbvNmWVsRbgwdxXWcX1EXxh0
270   PLIm0Rt8gzRbvNmWVsRbgwdxXWcX1EXxh0
271   PLIm0Rt8gzRbvNmWVsRbgwdxXWcX1EXxh0
272   PLIm0Rt8gzRbvNmWVsRbgwdxXWcX1EXxh0
273   PLIm0Rt8gzRbvNmWVsRbgwdxXWcX1EXxh0
274   PLIm0Rt8gzRbvNmWVsRbgwdxXWcX1EXxh0
275   PLIm0Rt8gzRbvNmWVsRbgwdxXWcX1EXxh0
276   PLIm0Rt8gzRbvNmWVsRbgwdxXWcX1EXxh0
277   PLIm0Rt8gzRbvNmWVsRbgwdxXWcX1EXxh0
278   PLIm0Rt8gzRbvNmWVsRbgwdxXWcX1EXxh0
279   PLIm0Rt8gzRbvNmWVsRbgwdxXWcX1EXxh0
280   PLIm0Rt8gzRbvNmWVsRbgwdxXWcX1EXxh0
281   PLIm0Rt8gzRbvNmWVsRbgwdxXWcX1EXxh0
282   PLIm0Rt8gzRbvNmWVsRbgwdxXWcX1EXxh0
283   PLIm0Rt8gzRbvNmWVsRbgwdxXWcX1EXxh0
284   PLIm0Rt8gzRbvNmWVsRbgwdxXWcX1EXxh0
285   PLIm0Rt8gzRbvNmWVsRbgwdxXWcX1EXxh0
286   PLIm0Rt8gzRbvNmWVsRbgwdxXWcX1EXxh0
287   PLIm0Rt8gzRbvNmWVsRbgwdxXWcX1EXxh0
288   PLIm0Rt8gzRbvNmWVsRbgwdxXWcX1EXxh0
289   PLIm0Rt8gzRbvNmWVsRbgwdxXWcX1EXxh0
290   PLIm0Rt8gzRbvNmWVsRbgwdxXWcX1EXxh0
291   PLIm0Rt8gzRbvNmWVsRbgwdxXWcX1EXxh0
292   PLIm0Rt8gzRbvNmWVsRbgwdxXWcX1EXxh0
293   PLIm0Rt8gzRbvNmWVsRbgwdxXWcX1EXxh0
294   PLIm0Rt8gzRbvNmWVsRbgwdxXWcX1EXxh0
295   PLIm0Rt8gzRbvNmWVsRbgwdxXWcX1EXxh0
296   PLIm0Rt8gzRbvNmWVsRbgwdxXWcX1EXxh0
297   PLIm0Rt8gzRbvNmWVsRbgwdxXWcX1EXxh0
298   PLIm0Rt8gzRbvNmWVsRbgwdxXWcX1EXxh0
299   PLIm0Rt8gzRbuI3ij0C4yrfAQb8tMbtCt8
300   PLIm0Rt8gzRbuI3ij0C4yrfAQb8tMbtCt8
301   PLIm0Rt8gzRbuI3ij0C4yrfAQb8tMbtCt8
302   PLIm0Rt8gzRbuI3ij0C4yrfAQb8tMbtCt8
303   PLIm0Rt8gzRbuI3ij0C4yrfAQb8tMbtCt8
304   PLIm0Rt8gzRbuI3ij0C4yrfAQb8tMbtCt8
305   PLIm0Rt8gzRbuI3ij0C4yrfAQb8tMbtCt8
306   PLIm0Rt8gzRbuI3ij0C4yrfAQb8tMbtCt8
307   PLIm0Rt8gzRbuI3ij0C4yrfAQb8tMbtCt8
308   PLIm0Rt8gzRbuI3ij0C4yrfAQb8tMbtCt8
309   PLIm0Rt8gzRbuI3ij0C4yrfAQb8tMbtCt8
310   PLIm0Rt8gzRbuI3ij0C4yrfAQb8tMbtCt8
311   PLIm0Rt8gzRbuI3ij0C4yrfAQb8tMbtCt8
312   PLIm0Rt8gzRbuI3ij0C4yrfAQb8tMbtCt8
313   PLIm0Rt8gzRbuI3ij0C4yrfAQb8tMbtCt8
314   PLIm0Rt8gzRbuI3ij0C4yrfAQb8tMbtCt8
315   PLIm0Rt8gzRbuI3ij0C4yrfAQb8tMbtCt8
316   PLIm0Rt8gzRbuI3ij0C4yrfAQb8tMbtCt8
317   PLIm0Rt8gzRbuI3ij0C4yrfAQb8tMbtCt8
318   PLIm0Rt8gzRbuI3ij0C4yrfAQb8tMbtCt8
319   PLIm0Rt8gzRbuI3ij0C4yrfAQb8tMbtCt8
320   PLIm0Rt8gzRbuI3ij0C4yrfAQb8tMbtCt8
321   PLIm0Rt8gzRbuI3ij0C4yrfAQb8tMbtCt8
322   PLIm0Rt8gzRbuI3ij0C4yrfAQb8tMbtCt8
323   PLIm0Rt8gzRbuI3ij0C4yrfAQb8tMbtCt8
324   PLIm0Rt8gzRbuI3ij0C4yrfAQb8tMbtCt8
325   PLIm0Rt8gzRbuI3ij0C4yrfAQb8tMbtCt8
326   PLIm0Rt8gzRbuI3ij0C4yrfAQb8tMbtCt8
327   PLIm0Rt8gzRbuI3ij0C4yrfAQb8tMbtCt8
328   PLIm0Rt8gzRbuI3ij0C4yrfAQb8tMbtCt8
329   PLIm0Rt8gzRbuI3ij0C4yrfAQb8tMbtCt8
330   PLIm0Rt8gzRbuI3ij0C4yrfAQb8tMbtCt8
331   PLIm0Rt8gzRbuI3ij0C4yrfAQb8tMbtCt8
332   PLIm0Rt8gzRbuI3ij0C4yrfAQb8tMbtCt8
333   PLIm0Rt8gzRbuI3ij0C4yrfAQb8tMbtCt8
334   PLIm0Rt8gzRbuI3ij0C4yrfAQb8tMbtCt8
335   PLIm0Rt8gzRbuI3ij0C4yrfAQb8tMbtCt8
336   PLIm0Rt8gzRbuI3ij0C4yrfAQb8tMbtCt8
337   PLIm0Rt8gzRbuI3ij0C4yrfAQb8tMbtCt8
338   PLIm0Rt8gzRbuI3ij0C4yrfAQb8tMbtCt8
339   PLIm0Rt8gzRbuI3ij0C4yrfAQb8tMbtCt8
340   PLIm0Rt8gzRbuI3ij0C4yrfAQb8tMbtCt8
341   PLIm0Rt8gzRbuI3ij0C4yrfAQb8tMbtCt8
342   PLIm0Rt8gzRbuI3ij0C4yrfAQb8tMbtCt8
343   PLIm0Rt8gzRbuI3ij0C4yrfAQb8tMbtCt8
344   PLIm0Rt8gzRbuI3ij0C4yrfAQb8tMbtCt8
345   PLIm0Rt8gzRbvUqBmSmnIEr9nTIFuqAW_F
346   PLIm0Rt8gzRbvUqBmSmnIEr9nTIFuqAW_F
347   PLIm0Rt8gzRbvUqBmSmnIEr9nTIFuqAW_F
348   PLIm0Rt8gzRbvUqBmSmnIEr9nTIFuqAW_F
349   PLIm0Rt8gzRbvUqBmSmnIEr9nTIFuqAW_F
350   PLIm0Rt8gzRbvUqBmSmnIEr9nTIFuqAW_F
351   PLIm0Rt8gzRbvUqBmSmnIEr9nTIFuqAW_F
352   PLIm0Rt8gzRbvUqBmSmnIEr9nTIFuqAW_F
353   PLIm0Rt8gzRbvUqBmSmnIEr9nTIFuqAW_F
354   PLIm0Rt8gzRbvUqBmSmnIEr9nTIFuqAW_F
355   PLIm0Rt8gzRbvUqBmSmnIEr9nTIFuqAW_F
356   PLIm0Rt8gzRbvUqBmSmnIEr9nTIFuqAW_F
357   PLIm0Rt8gzRbvUqBmSmnIEr9nTIFuqAW_F
358   PLIm0Rt8gzRbvUqBmSmnIEr9nTIFuqAW_F
359   PLIm0Rt8gzRbvUqBmSmnIEr9nTIFuqAW_F
360   PLIm0Rt8gzRbvUqBmSmnIEr9nTIFuqAW_F
361   PLIm0Rt8gzRbvUqBmSmnIEr9nTIFuqAW_F
362   PLIm0Rt8gzRbvUqBmSmnIEr9nTIFuqAW_F
363   PLIm0Rt8gzRbvUqBmSmnIEr9nTIFuqAW_F
364   PLIm0Rt8gzRbvUqBmSmnIEr9nTIFuqAW_F
365   PLIm0Rt8gzRbvUqBmSmnIEr9nTIFuqAW_F
366   PLIm0Rt8gzRbvUqBmSmnIEr9nTIFuqAW_F
367   PLIm0Rt8gzRbvUqBmSmnIEr9nTIFuqAW_F
368   PLIm0Rt8gzRbvUqBmSmnIEr9nTIFuqAW_F
369   PLIm0Rt8gzRbvUqBmSmnIEr9nTIFuqAW_F
370   PLIm0Rt8gzRbvUqBmSmnIEr9nTIFuqAW_F
371   PLIm0Rt8gzRbvUqBmSmnIEr9nTIFuqAW_F
372   PLIm0Rt8gzRbvUqBmSmnIEr9nTIFuqAW_F
373   PLIm0Rt8gzRbvUqBmSmnIEr9nTIFuqAW_F
374   PLIm0Rt8gzRbvUqBmSmnIEr9nTIFuqAW_F
375   PLIm0Rt8gzRbvUqBmSmnIEr9nTIFuqAW_F
376   PLIm0Rt8gzRbvUqBmSmnIEr9nTIFuqAW_F
377   PLIm0Rt8gzRbvUqBmSmnIEr9nTIFuqAW_F
378   PLIm0Rt8gzRbvUqBmSmnIEr9nTIFuqAW_F
379   PLIm0Rt8gzRbvUqBmSmnIEr9nTIFuqAW_F
380   PLIm0Rt8gzRbvUqBmSmnIEr9nTIFuqAW_F
381   PLIm0Rt8gzRbvUqBmSmnIEr9nTIFuqAW_F
382   PLIm0Rt8gzRbvUqBmSmnIEr9nTIFuqAW_F
383   PLIm0Rt8gzRbvUqBmSmnIEr9nTIFuqAW_F
384   PLIm0Rt8gzRbvUqBmSmnIEr9nTIFuqAW_F
385   PLIm0Rt8gzRbvUqBmSmnIEr9nTIFuqAW_F
386   PLIm0Rt8gzRbvUqBmSmnIEr9nTIFuqAW_F
387   PLIm0Rt8gzRbvUqBmSmnIEr9nTIFuqAW_F
388   PLIm0Rt8gzRbvUqBmSmnIEr9nTIFuqAW_F
389   PLIm0Rt8gzRbs70xRsspnrAuR1qgUDXl4e
390   PLIm0Rt8gzRbs70xRsspnrAuR1qgUDXl4e
391   PLIm0Rt8gzRbs70xRsspnrAuR1qgUDXl4e
392   PLIm0Rt8gzRbs70xRsspnrAuR1qgUDXl4e
393   PLIm0Rt8gzRbs70xRsspnrAuR1qgUDXl4e
394   PLIm0Rt8gzRbs70xRsspnrAuR1qgUDXl4e
395   PLIm0Rt8gzRbs70xRsspnrAuR1qgUDXl4e
396   PLIm0Rt8gzRbs70xRsspnrAuR1qgUDXl4e
397   PLIm0Rt8gzRbs70xRsspnrAuR1qgUDXl4e
398   PLIm0Rt8gzRbs70xRsspnrAuR1qgUDXl4e
399   PLIm0Rt8gzRbs70xRsspnrAuR1qgUDXl4e
400   PLIm0Rt8gzRbs70xRsspnrAuR1qgUDXl4e
401   PLIm0Rt8gzRbs70xRsspnrAuR1qgUDXl4e
402   PLIm0Rt8gzRbs70xRsspnrAuR1qgUDXl4e
403   PLIm0Rt8gzRbs70xRsspnrAuR1qgUDXl4e
404   PLIm0Rt8gzRbs70xRsspnrAuR1qgUDXl4e
405   PLIm0Rt8gzRbs70xRsspnrAuR1qgUDXl4e
406   PLIm0Rt8gzRbs70xRsspnrAuR1qgUDXl4e
407   PLIm0Rt8gzRbs70xRsspnrAuR1qgUDXl4e
408   PLIm0Rt8gzRbs70xRsspnrAuR1qgUDXl4e
409   PLIm0Rt8gzRbs70xRsspnrAuR1qgUDXl4e
410   PLIm0Rt8gzRbs70xRsspnrAuR1qgUDXl4e
411   PLIm0Rt8gzRbs70xRsspnrAuR1qgUDXl4e
412   PLIm0Rt8gzRbs70xRsspnrAuR1qgUDXl4e
413   PLIm0Rt8gzRbs70xRsspnrAuR1qgUDXl4e
414   PLIm0Rt8gzRbs70xRsspnrAuR1qgUDXl4e
415   PLIm0Rt8gzRbs70xRsspnrAuR1qgUDXl4e
416   PLIm0Rt8gzRbs70xRsspnrAuR1qgUDXl4e
417   PLIm0Rt8gzRbs70xRsspnrAuR1qgUDXl4e
418   PLIm0Rt8gzRbs70xRsspnrAuR1qgUDXl4e
419   PLIm0Rt8gzRbs70xRsspnrAuR1qgUDXl4e
420   PLIm0Rt8gzRbs70xRsspnrAuR1qgUDXl4e
421   PLIm0Rt8gzRbs70xRsspnrAuR1qgUDXl4e
422   PLIm0Rt8gzRbs70xRsspnrAuR1qgUDXl4e
423   PLIm0Rt8gzRbs70xRsspnrAuR1qgUDXl4e
424   PLIm0Rt8gzRbs70xRsspnrAuR1qgUDXl4e
425   PLIm0Rt8gzRbs70xRsspnrAuR1qgUDXl4e
426   PLIm0Rt8gzRbs70xRsspnrAuR1qgUDXl4e
427   PLIm0Rt8gzRbs70xRsspnrAuR1qgUDXl4e
428   PLIm0Rt8gzRbs70xRsspnrAuR1qgUDXl4e
429   PLIm0Rt8gzRbs70xRsspnrAuR1qgUDXl4e
430   PLIm0Rt8gzRbue3Nu1Xy67JzYHUGRFFCSR
431   PLIm0Rt8gzRbue3Nu1Xy67JzYHUGRFFCSR
432   PLIm0Rt8gzRbue3Nu1Xy67JzYHUGRFFCSR
433   PLIm0Rt8gzRbue3Nu1Xy67JzYHUGRFFCSR
434   PLIm0Rt8gzRbue3Nu1Xy67JzYHUGRFFCSR
435   PLIm0Rt8gzRbue3Nu1Xy67JzYHUGRFFCSR
436   PLIm0Rt8gzRbue3Nu1Xy67JzYHUGRFFCSR
437   PLIm0Rt8gzRbue3Nu1Xy67JzYHUGRFFCSR
438   PLIm0Rt8gzRbue3Nu1Xy67JzYHUGRFFCSR
439   PLIm0Rt8gzRbue3Nu1Xy67JzYHUGRFFCSR
440   PLIm0Rt8gzRbue3Nu1Xy67JzYHUGRFFCSR
441   PLIm0Rt8gzRbue3Nu1Xy67JzYHUGRFFCSR
442   PLIm0Rt8gzRbue3Nu1Xy67JzYHUGRFFCSR
443   PLIm0Rt8gzRbue3Nu1Xy67JzYHUGRFFCSR
444   PLIm0Rt8gzRbue3Nu1Xy67JzYHUGRFFCSR
445   PLIm0Rt8gzRbue3Nu1Xy67JzYHUGRFFCSR
446   PLIm0Rt8gzRbue3Nu1Xy67JzYHUGRFFCSR
447   PLIm0Rt8gzRbue3Nu1Xy67JzYHUGRFFCSR
448   PLIm0Rt8gzRbue3Nu1Xy67JzYHUGRFFCSR
449   PLIm0Rt8gzRbue3Nu1Xy67JzYHUGRFFCSR
450   PLIm0Rt8gzRbue3Nu1Xy67JzYHUGRFFCSR
451   PLIm0Rt8gzRbue3Nu1Xy67JzYHUGRFFCSR
452   PLIm0Rt8gzRbue3Nu1Xy67JzYHUGRFFCSR
453   PLIm0Rt8gzRbue3Nu1Xy67JzYHUGRFFCSR
454   PLIm0Rt8gzRbue3Nu1Xy67JzYHUGRFFCSR
455   PLIm0Rt8gzRbue3Nu1Xy67JzYHUGRFFCSR
456   PLIm0Rt8gzRbue3Nu1Xy67JzYHUGRFFCSR
457   PLIm0Rt8gzRbue3Nu1Xy67JzYHUGRFFCSR
458   PLIm0Rt8gzRbue3Nu1Xy67JzYHUGRFFCSR
459   PLIm0Rt8gzRbue3Nu1Xy67JzYHUGRFFCSR
460   PLIm0Rt8gzRbue3Nu1Xy67JzYHUGRFFCSR
461   PLIm0Rt8gzRbue3Nu1Xy67JzYHUGRFFCSR
462   PLIm0Rt8gzRbue3Nu1Xy67JzYHUGRFFCSR
463   PLIm0Rt8gzRbue3Nu1Xy67JzYHUGRFFCSR
464   PLIm0Rt8gzRbue3Nu1Xy67JzYHUGRFFCSR
465   PLIm0Rt8gzRbue3Nu1Xy67JzYHUGRFFCSR
466   PLIm0Rt8gzRbue3Nu1Xy67JzYHUGRFFCSR
467   PLIm0Rt8gzRbue3Nu1Xy67JzYHUGRFFCSR
468   PLIm0Rt8gzRbue3Nu1Xy67JzYHUGRFFCSR
469   PLIm0Rt8gzRbue3Nu1Xy67JzYHUGRFFCSR
470   PLIm0Rt8gzRbuLKQ294o73x9SXXT4S-8IO
471   PLIm0Rt8gzRbuLKQ294o73x9SXXT4S-8IO
472   PLIm0Rt8gzRbuLKQ294o73x9SXXT4S-8IO
473   PLIm0Rt8gzRbuLKQ294o73x9SXXT4S-8IO
474   PLIm0Rt8gzRbuLKQ294o73x9SXXT4S-8IO
475   PLIm0Rt8gzRbuLKQ294o73x9SXXT4S-8IO
476   PLIm0Rt8gzRbuLKQ294o73x9SXXT4S-8IO
477   PLIm0Rt8gzRbuLKQ294o73x9SXXT4S-8IO
478   PLIm0Rt8gzRbuLKQ294o73x9SXXT4S-8IO
479   PLIm0Rt8gzRbuLKQ294o73x9SXXT4S-8IO
480   PLIm0Rt8gzRbuLKQ294o73x9SXXT4S-8IO
481   PLIm0Rt8gzRbuLKQ294o73x9SXXT4S-8IO
482   PLIm0Rt8gzRbuLKQ294o73x9SXXT4S-8IO
483   PLIm0Rt8gzRbuLKQ294o73x9SXXT4S-8IO
484   PLIm0Rt8gzRbuLKQ294o73x9SXXT4S-8IO
485   PLIm0Rt8gzRbuLKQ294o73x9SXXT4S-8IO

# Getting an LLM to do the tagging is easier than doing continuous regex changes with how Konami inconsistently tags their videos.

In [223]:
import json
import time
from pydantic import BaseModel
# Using the updated Google GenAI SDK imports
from google import genai
from google.genai import types

# Initialize your client (it automatically picks up GEMINI_API_KEY from environment)
client = genai.Client()

# 1. Update your Schema structure
class MatchRecord(BaseModel):
    is_match: bool
    round_name: str
    player_1: str
    deck_1: str
    player_2: str
    deck_2: str

# 2. Define the parser function with explicit logic for edge cases
def gemini_parse_match(title, description):
    prompt = f"""
    You are an expert tournament data extractor for the Yu-Gi-Oh! TCG. 
    Analyze the video title and description to extract match data.
    
    ### CRITICAL FILTERING RULES:
    1. A video is a valid match (`is_match`: true) ONLY if it is an official, standard multi-player tournament match featuring two active players and an explicitly stated round or top-cut designation (e.g., Round 1, Top 8, Finals).
    2. Set `is_match`: false if the video is:
       - A single-player focus or a single-deck highlight video that doesn't name both active competitors (e.g., "Mirror Match - Jesse Kotton").
       - An interview or a "Post Match Discussion and Interview" (talking *after* the match concluded).
       - An exhibition match, fun match, staff duel, or "Caster vs Master" challenge.
       - A "Deck Profile", "Spotlight", "Ceremony", "Vlog", "Highlights", or casual discussion.
       
    ### DATA EXTRACTION RULES (Only if `is_match` is true):
    - If a field is missing, use "Unknown". Do not guess.
    - Remove all flag emojis, country bracket prefixes (e.g., [DE], [UK]), and trailing tournament metadata from names.
    - DECK VS DECK MATCHES: If the title shows two archetypes fighting directly without player names (e.g., "Lunalight vs Psychic" or "Stardust Dragon vs Frogs"), map the archetypes to `deck_1` and `deck_2`, and set `player_1` and `player_2` to "Unknown".

    TITLE: {title}
    DESCRIPTION: {description}
    """
    
    # Using the correct SDK method for Structured JSON Outputs
    response = client.models.generate_content(
        model='gemini-2.5-flash',
        contents=prompt,
        config=types.GenerateContentConfig(
            response_mime_type="application/json",
            response_schema=MatchRecord,
            temperature=0.1
        ),
    )
    return json.loads(response.text)

# 3. Execution loop
processed_dataset = []

# Mock array assumed: replace `data` with your actual input data structure
for entry in data:
    try:
        title_snippet = entry.get('Video Title', '')[:40]
        print(f"Analyzing: {title_snippet}...")
        
        result = gemini_parse_match(entry.get('Video Title', ''), entry.get('Video Description', ''))
        
        # We only keep the clean records that are actual match gameplay
        if result.get("is_match"):
            # Add metadata for audit tracking
            result['original_title'] = entry.get('Video Title')
            processed_matches.append(result)
            print(f"   ✅ SUCCESS: Match found! {result['player_1']} vs {result['player_2']}")
        else:
            print("   ⏩ SKIPPED: Non-match content.")
            
        # --- THE SAFETY THROTTLE ---
        # 15 seconds keeps you well under the free-tier rate limit threshold
        time.sleep(15) 
            
    except Exception as e:
        print(f"❌ Error processing {title_snippet}: {e}")
        if "429" in str(e):
            print("⚠️ Resource exhausted (Rate limit). Pausing for 60 seconds...")
            time.sleep(60)

# 4. View results
print(f"\nProcessing complete. Successfully extracted {len(processed_matches)} live matches.")

Analyzing: YCS Bochum 2018: Welcome...
Analyzing: YCS Bochum 2018: Event Spotlight...
Analyzing: YCS Bochum 2018: Quick Questions...
Analyzing: YCS Bochum 2018: Meta Discussion...
Analyzing: YCS Bochum 2018: Giant Card Spotlight...
Analyzing: YCS Bochum 2018: Prizes Spotlight...
Analyzing: YCS Bochum 2018: Round 1 Feature Match...

KeyboardInterrupt: